"""Report service: deterministic, versioned JSON report generation."""

import json
from datetime import UTC, datetime
from pathlib import Path
from uuid import uuid4

from sqlalchemy.orm import Session

from app.core.config import Settings, get_settings
from app.core.version import ANALYZER_VERSION, REPORT_SCHEMA_VERSION, TOOL_VERSION
from app.models.analysis import AnalysisRun, Finding, ScoreResult
from app.models.audit import Report
from app.models.dataset import Dataset
from app.models.project import Project
from app.schemas.enums import AuditEventType
from app.services.audit import record_event

DISCLAIMER = (
    "This report is generated by an engineering support tool inspired by ML verification "
    "and data assurance principles. It is NOT a certification and does NOT assert ECSS "
    "compliance. Results depend on the dataset provided; automated checks do not replace "
    "engineering review; statistical anomalies are not necessarily errors; leakage "
    "indicators are heuristics only."
)

LIMITATIONS = [
    "Results depend on the dataset provided and on the automatic type inference used by the tool.",
    "Automated checks do not replace technical review, mission-specific validation, safety analysis "
    "or formal certification.",
    "Statistical anomalies (outliers, rare categories, irregular intervals) are flagged as possible "
    "anomalies and require engineering judgment.",
    "Leakage indicators are heuristic and must be confirmed by engineering review.",
    "The Data Readiness Score is a decision-support indicator, not a measure of safety or mission suitability.",
    "This tool does not certify ECSS compliance and does not claim any official classification.",
]


class ReportService:
    def __init__(self, db: Session, settings: Settings | None = None) -> None:
        self.db = db
        self.settings = settings or get_settings()

    @staticmethod
    def _finding_doc(f: Finding) -> dict:
        return {
            "id": f.id,
            "check_id": f.check_id,
            "category": f.category,
            "title": f.title,
            "description": f.description,
            "status": f.status,
            "severity": f.severity,
            "observed_value": f.observed_value,
            "threshold": f.threshold,
            "columns": f.columns,
            "evidence": f.evidence,
            "risk": f.risk,
            "recommendation": f.recommendation,
            "analyzer_version": f.analyzer_version,
            "timestamp": f.created_at.isoformat(),
        }

    def _document(
        self,
        project: Project,
        dataset: Dataset,
        run: AnalysisRun,
        score: ScoreResult,
        findings: list[Finding],
    ) -> dict:
        """Assemble the report document.

        Deterministic apart from report_id and generated_at (documented in the
        report itself). Findings are sorted by (category, check_id, title) and
        serialization uses sorted keys.
        """
        from app.analyzers.registry import category_rank

        findings_sorted = sorted(
            findings,
            key=lambda f: (category_rank(f.category), f.check_id, (f.columns and ",".join(f.columns)) or "", f.title),
        )
        return {
            "report_id": str(uuid4()),
            "report_schema_version": REPORT_SCHEMA_VERSION,
            "tool_version": TOOL_VERSION,
            "analyzer_version": ANALYZER_VERSION,
            "generated_at_utc": datetime.now(UTC).isoformat(),
            "project": {
                "id": project.id,
                "name": project.name,
                "description": project.description,
                "application_type": project.application_type,
                "target_platform": project.target_platform,
                "operating_context": project.operating_context,
                "criticality_level": project.criticality_level,
                "ml_function": project.ml_function,
                "status": project.status,
                "version": project.version,
            },
            "dataset": {
                "id": dataset.id,
                "original_filename": dataset.original_filename,
                "sha256": dataset.sha256,
                "size_bytes": dataset.size_bytes,
                "row_count": dataset.row_count,
                "column_count": dataset.column_count,
                "columns": json.loads(dataset.columns_json),
                "uploaded_at": dataset.uploaded_at.isoformat(),
            },
            "analysis": {
                "run_id": run.id,
                "started_at": run.started_at.isoformat(),
                "completed_at": run.completed_at.isoformat() if run.completed_at else None,
                "status": run.status,
                "config": run.config_snapshot,
            },
            "metrics": {
                "row_count": dataset.row_count,
                "column_count": dataset.column_count,
                "findings_total": len(findings),
                "pass_count": score.pass_count,
                "warning_count": score.warning_count,
                "fail_count": score.fail_count,
                "not_applicable_count": score.not_applicable_count,
                "not_evaluated_count": score.not_evaluated_count,
            },
            "data_readiness_score": {
                "overall_score": score.overall_score,
                "coverage_pct": score.coverage_pct,
                "method": "weighted-penalty v1.0.0",
                "score_method_version": score.score_method_version,
                "categories": score.category_scores,
                "weights": score.weights_json,
            },
            "findings": [self._finding_doc(f) for f in findings_sorted],
            "known_limitations": LIMITATIONS,
            "disclaimer": DISCLAIMER,
        }

    def generate(
        self, project: Project, run: AnalysisRun, dataset: Dataset, score: ScoreResult, findings: list[Finding]
    ) -> Report:
        document = self._document(project, dataset, run, score, findings)
        report_id = document["report_id"]
        text = json.dumps(document, indent=2, sort_keys=True, ensure_ascii=True)
        filename = f"report_{report_id}.json"
        path: Path = self.settings.reports_dir / filename
        path.write_text(text, encoding="utf-8")

        report = Report(
            id=report_id,
            project_id=project.id,
            run_id=run.id,
            schema_version=REPORT_SCHEMA_VERSION,
            filename=filename,
            size_bytes=len(text.encode("utf-8")),
            content=text,
        )
        self.db.add(report)
        record_event(
            self.db,
            AuditEventType.REPORT_EXPORTED,
            project_id=project.id,
            dataset_id=dataset.id,
            run_id=run.id,
            details={"report_id": report_id, "schema_version": REPORT_SCHEMA_VERSION},
        )
        self.db.commit()
        self.db.refresh(report)
        return report
