"""Lunar Landing Safety Cage — synthetic demonstration content (week 3)."""

from app.portfolio.datadefs.builders import DEC, FM, LIM, RISK, TC, TR, E, R

MODEL = "landing-safety-cage-v1"  # deterministic cage; ML part described separately
REQS: list[dict] = [
    R(
        "REQ-F-001",
        "Validate ML landing commands",
        "FUNCTIONAL",
        "The safety cage shall validate each ML landing command against physical and operational constraints before release.",
        "TEST",
        "Unsafe commands rejected; validation evidence per command.",
        "HIGH",
        "VERIFIED",
    ),
    R(
        "REQ-F-002",
        "Altitude ceiling check",
        "SAFETY",
        "Commands implying altitude below the ceiling shall be flagged.",
        "TEST",
        "violation detected on synthetic profile.",
        "HIGH",
        "VERIFIED",
    ),
    R(
        "REQ-F-003",
        "Vertical velocity bound",
        "SAFETY",
        "Vertical velocity commands beyond bound shall be rejected.",
        "TEST",
        "rejection demonstrated.",
        "HIGH",
        "VERIFIED",
    ),
    R(
        "REQ-F-004",
        "Horizontal velocity bound",
        "SAFETY",
        "Horizontal velocity commands beyond bound shall be rejected.",
        "TEST",
        "rejection demonstrated.",
        "HIGH",
        "VERIFIED",
    ),
    R(
        "REQ-F-005",
        "Fuel margin monitor",
        "SAFETY",
        "Landing profile shall preserve a fuel margin; insufficient margin triggers abort.",
        "TEST",
        "abort triggered in low-fuel scenario.",
        "HIGH",
        "VERIFIED",
    ),
    R(
        "REQ-F-006",
        "Touchdown velocity envelope",
        "SAFETY",
        "Projected touchdown velocity shall stay within the structural envelope.",
        "TEST",
        "envelope check verified.",
        "HIGH",
        "VERIFIED",
    ),
    R(
        "REQ-F-007",
        "Physics-estimator cross-check",
        "SAFETY",
        "ML output shall be compared with an independent physics estimate; divergence triggers rejection.",
        "TEST",
        "divergence rejection demonstrated.",
        "HIGH",
        "VERIFIED",
    ),
    R(
        "REQ-R-001",
        "OOD detection for landing inputs",
        "ROBUSTNESS",
        "Landing inputs outside the trained regime shall be detected and routed to fallback.",
        "TEST",
        "OOD detection rate >= 0.90.",
        "HIGH",
        "VERIFIED",
    ),
    R(
        "REQ-P-001",
        "Fallback activation time",
        "PERFORMANCE",
        "Fallback shall activate within 100 ms of an invalid command.",
        "TEST",
        "activation < 100 ms in simulation.",
        "HIGH",
        "VERIFIED",
    ),
    R(
        "REQ-M-001",
        "Cage logging",
        "MONITORING",
        "Every rejection, fallback activation and divergence shall be logged.",
        "TEST",
        "log completeness verified.",
        "MEDIUM",
        "VERIFIED",
    ),
    R(
        "REQ-R-002",
        "Graceful degradation",
        "ROBUSTNESS",
        "With incoherent sensors the cage shall degrade to a safe pre-planned profile.",
        "TEST",
        "degradation path verified (simulation).",
        "MEDIUM",
        "NOT_VERIFIED",
    ),
    R(
        "REQ-S-001",
        "Common-mode independence",
        "SAFETY",
        "The deterministic cage and physics estimator shall not share the ML failure modes.",
        "ANALYSIS",
        "independence argument + review.",
        "HIGH",
        "APPROVED",
    ),
]

TESTS: list[dict] = [
    {
        **TC(
            "TEST-LLS-001",
            "Nominal landing profile",
            "SCENARIO",
            "Nominal ML commands.",
            "no false rejection",
            ["REQ-F-001"],
            "HIGH",
        ),
        **TR(
            "TEST-LLS-001",
            "PASS",
            "RUN-LLS-001",
            "sim-landing-v2",
            MODEL,
            "lls-scenarios-v1.1",
            "0 unsafe commands accepted; 0 valid commands rejected (50 profiles).",
            {"false_rejection_rate": 0.0, "unsafe_command_rejection_rate": 1.0},
            evidence_ids=["EVID-LLS-001"],
        ),
    },
    {
        **TC(
            "TEST-LLS-002",
            "Sensor noise",
            "ROBUSTNESS",
            "Noisy sensor inputs.",
            "rejection still correct",
            ["REQ-F-001"],
            "MEDIUM",
        ),
        **TR(
            "TEST-LLS-002",
            "PASS",
            "RUN-LLS-002",
            "sim-landing-v2",
            MODEL,
            "lls-scenarios-v1.1",
            "Rejection rate stable under noise.",
            {"false_rejection_rate": 0.01},
        ),
    },
    {
        **TC(
            "TEST-LLS-003",
            "Sensor loss",
            "ROBUSTNESS",
            "Lost altimeter.",
            "safe fallback",
            ["REQ-R-002", "REQ-F-002"],
            "HIGH",
        ),
        **TR(
            "TEST-LLS-003",
            "PASS",
            "RUN-LLS-003",
            "sim-landing-v2",
            MODEL,
            "lls-scenarios-v1.1",
            "Fallback to pre-planned profile on altimeter loss.",
            {"fallback_activated": True},
        ),
    },
    {
        **TC(
            "TEST-LLS-004",
            "Unrepresented terrain",
            "ROBUSTNESS",
            "Terrain outside training.",
            "OOD flag or rejection",
            ["REQ-R-001", "REQ-S-001"],
            "HIGH",
        ),
        **TR(
            "TEST-LLS-004",
            "PASS",
            "RUN-LLS-004",
            "sim-landing-v2",
            MODEL,
            "lls-terrain-ood-v1.1",
            "OOD flagged; cage rejected diverging commands.",
            {"ood_detection_rate": 0.94},
        ),
    },
    {
        **TC(
            "TEST-LLS-005",
            "ML output out of range",
            "SCENARIO",
            "Absurd ML command.",
            "rejected",
            ["REQ-F-002", "REQ-F-003", "REQ-F-006"],
            "HIGH",
        ),
        **TR(
            "TEST-LLS-005",
            "PASS",
            "RUN-LLS-005",
            "sim-landing-v2",
            MODEL,
            "lls-scenarios-v1.1",
            "All 40 absurd commands rejected.",
            {"unsafe_command_rejection_rate": 1.0},
        ),
    },
    {
        **TC(
            "TEST-LLS-006",
            "ML/physics divergence",
            "SCENARIO",
            "Estimator disagreement.",
            "rejected when divergence > limit",
            ["REQ-F-007"],
            "HIGH",
        ),
        **TR(
            "TEST-LLS-006",
            "PASS",
            "RUN-LLS-006",
            "sim-landing-v2",
            MODEL,
            "lls-scenarios-v1.1",
            "Divergence rejection within limit.",
            {"max_divergence_accepted": 0.12},
            evidence_ids=["EVID-LLS-003"],
        ),
    },
    {
        **TC(
            "TEST-LLS-007",
            "Inference delay",
            "LATENCY",
            "Delayed ML output.",
            "fallback < 100 ms",
            ["REQ-P-001"],
            "HIGH",
        ),
        **TR(
            "TEST-LLS-007",
            "PASS",
            "RUN-LLS-007",
            "sim-landing-v2",
            MODEL,
            "lls-scenarios-v1.1",
            "Fallback in 74 ms median on delay injection.",
            {"fallback_activation_ms": 74},
        ),
    },
    {
        **TC(
            "TEST-LLS-008",
            "Fuel margin abort",
            "SCENARIO",
            "Insufficient fuel margin.",
            "abort triggered",
            ["REQ-F-005"],
            "HIGH",
        ),
        **TR(
            "TEST-LLS-008",
            "PASS",
            "RUN-LLS-008",
            "sim-landing-v2",
            MODEL,
            "lls-low-fuel-v1.1",
            "Abort triggered in low-fuel scenario.",
            {"abort_triggered": True},
        ),
    },
    {
        **TC(
            "TEST-LLS-009",
            "Hard constraint violation sweep",
            "MONTE_CARLO",
            "Monte Carlo over 500 synthetic profiles.",
            "no envelope violation released",
            ["REQ-F-002", "REQ-F-003", "REQ-F-004", "REQ-F-006"],
            "HIGH",
        ),
        **TR(
            "TEST-LLS-009",
            "PASS",
            "RUN-LLS-009",
            "sim-landing-v2",
            MODEL,
            "lls-mc-v1.1",
            "0 released violations in 500 profiles; 12 unsafe commands caught.",
            {"constraint_violation_count": 0, "profiles": 500},
            evidence_ids=["EVID-LLS-002"],
        ),
    },
    {
        **TC(
            "TEST-LLS-010",
            "Incoherent sensors",
            "ROBUSTNESS",
            "Conflicting sensor readings.",
            "graceful degradation",
            ["REQ-R-002"],
            "HIGH",
        ),
        **TR(
            "TEST-LLS-010",
            "FAIL",
            "RUN-LLS-010",
            "sim-landing-v2",
            MODEL,
            "lls-incoherent-v1.1",
            "Cage rejected commands correctly but fallback profile selection oscillated between two plans.",
            failure_reason="Selection logic lacks hysteresis for incoherent sensors.",
            reviewer_notes="ACT-LLS-01: add hysteresis + plan-lock.",
            evidence_ids=["EVID-LLS-004"],
        ),
    },
    {
        **TC(
            "TEST-LLS-011",
            "Common-mode independence review",
            "ANALYSIS",
            "Independence argument.",
            "review accepted",
            ["REQ-S-001"],
            "HIGH",
        ),
        **TR(
            "TEST-LLS-011",
            "INCONCLUSIVE",
            "RUN-LLS-011",
            "review",
            MODEL,
            "lls-scenarios-v1.1",
            "Review identified shared gyro pre-processing dependency between ML and physics estimator.",
            failure_reason="Shared sensor preprocessing weakens independence claim.",
            reviewer_notes="ACT-LLS-02: decouple preprocessing.",
            evidence_ids=["EVID-LLS-005"],
        ),
    },
]

EVIDENCE: list[dict] = [
    E(
        "EVID-LLS-001",
        "Nominal scenario campaign report",
        "TEST_RESULT",
        "Nominal landing profiles: no unsafe accepted, no valid rejected.",
        ["REQ-F-001"],
        ["TEST-LLS-001"],
        attachment="lls-nominal-campaign.txt",
    ),
    E(
        "EVID-LLS-002",
        "Monte Carlo sweep report",
        "TEST_RESULT",
        "500 synthetic profiles; 0 violations released.",
        ["REQ-F-002", "REQ-F-003", "REQ-F-004", "REQ-F-006"],
        ["TEST-LLS-009"],
        attachment="lls-monte-carlo.txt",
    ),
    E(
        "EVID-LLS-003",
        "Physics estimator log",
        "LOG",
        "Divergence checks between ML output and physics estimate.",
        ["REQ-F-007"],
        ["TEST-LLS-006"],
    ),
    E(
        "EVID-LLS-004",
        "Incoherent sensor failure log",
        "LOG",
        "Fallback oscillation evidence (failure).",
        ["REQ-R-002"],
        ["TEST-LLS-010"],
    ),
    E(
        "EVID-LLS-005",
        "Independence review record",
        "REVIEW_RECORD",
        "Common-mode review with finding on shared preprocessing.",
        ["REQ-S-001"],
        ["TEST-LLS-011"],
    ),
    E(
        "EVID-LLS-006",
        "OOD terrain detection report",
        "DATA_QUALITY_RESULT",
        "Terrain OOD detection results.",
        ["REQ-R-001"],
        ["TEST-LLS-004"],
    ),
    E(
        "EVID-LLS-007",
        "Fallback timing report",
        "BENCHMARK",
        "Fallback activation timing in simulation.",
        ["REQ-P-001"],
        ["TEST-LLS-007"],
    ),
    E(
        "EVID-LLS-008",
        "Cage log sample",
        "LOG",
        "Sample cage log with rejections and fallback events.",
        ["REQ-M-001"],
        ["TEST-LLS-001", "TEST-LLS-005"],
    ),
]

RISKS: list[dict] = [
    RISK(
        "RISK-LLS-001",
        "Common-mode failure ML and physics estimator",
        "Both paths fail from shared cause",
        "Shared sensor preprocessing/calibration",
        "Unsafe command released in degraded conditions",
        5,
        3,
        "Decouple preprocessing; independent sensor chains",
        "TEST-LLS-011 INCONCLUSIVE",
        5,
        2,
        "REQUIRES_MITIGATION",
        "Independence not yet demonstrated; blocking for real use.",
        ["REQ-S-001"],
        ["TEST-LLS-011"],
        ["FM-LLS-003"],
    ),
    RISK(
        "RISK-LLS-002",
        "False rejection of valid commands",
        "Valid landing command rejected",
        "Cage thresholds too tight",
        "Abort or degraded landing unnecessarily",
        4,
        3,
        "Threshold review + noise campaign",
        "TEST-LLS-002",
        3,
        2,
        "ACCEPTABLE_WITH_LIMITATIONS",
        "1% false-rejection in simulation accepted for demo with threshold review before any real use.",
        ["REQ-F-001"],
        ["TEST-LLS-002"],
        ["FM-LLS-002"],
    ),
    RISK(
        "RISK-LLS-003",
        "Simulator simplification",
        "Simulation misses flight dynamics detail",
        "Simplified terrain/fuel model",
        "Cage validated against wrong physics",
        4,
        4,
        "Hardware-in-the-loop and independent V&V",
        "Known limitation record",
        4,
        3,
        "REVIEW_REQUIRED",
        "Accepted only for simulation/demonstration; real use requires independent V&V + HIL.",
        [],
        [],
        ["FM-LLS-005"],
    ),
]

FMEA: list[dict] = [
    FM(
        "FM-LLS-001",
        "Release landing command",
        "Unsafe ML output accepted",
        "Command outside envelope released",
        "Hard constraint violation at touchdown",
        "Cage logic fault or bypass",
        "Constraint check + envelope monitor",
        "Deterministic cage",
        5,
        2,
        2,
        "Formal review of cage logic",
        "Cage + independent checks",
        "M",
        ["REQ-F-001", "REQ-F-006"],
        ["TEST-LLS-005", "TEST-LLS-009"],
        ["EVID-LLS-002"],
    ),
    FM(
        "FM-LLS-002",
        "Validate valid commands",
        "Valid command rejected",
        "False rejection",
        "Unnecessary abort",
        "Threshold too tight",
        "False rejection monitoring",
        "Noise campaign",
        3,
        3,
        3,
        "Threshold review",
        "Tuned thresholds",
        "M",
        ["REQ-F-001"],
        ["TEST-LLS-002"],
        ["EVID-LLS-001"],
    ),
    FM(
        "FM-LLS-003",
        "Cross-check ML vs physics",
        "Common-mode failure",
        "Both estimates agree but wrong",
        "Unsafe command validated",
        "Shared preprocessing",
        "Independence review",
        "Separate chains (planned)",
        5,
        3,
        3,
        "Decouple sensor chains",
        "Independent estimation",
        "H",
        ["REQ-S-001", "REQ-F-007"],
        ["TEST-LLS-011"],
        ["EVID-LLS-005"],
    ),
    FM(
        "FM-LLS-004",
        "Activate fallback",
        "Fallback delayed",
        "Late fallback",
        "Margin lost",
        "Slow decision path",
        "Timing test",
        "Fallback budget",
        4,
        2,
        2,
        "Keep fallback budget",
        "100 ms bound",
        "L",
        ["REQ-P-001"],
        ["TEST-LLS-007"],
        ["EVID-LLS-007"],
    ),
    FM(
        "FM-LLS-005",
        "Model environment",
        "OOD not detected",
        "Out-of-domain input scored normally",
        "Wrong guidance in novel terrain",
        "Incomplete ODD coverage",
        "OOD detector",
        "Terrain OOD set",
        4,
        2,
        2,
        "Extend terrain coverage",
        "OOD + cage rejection",
        "M",
        ["REQ-R-001"],
        ["TEST-LLS-004"],
        ["EVID-LLS-006"],
    ),
]

LIMITATIONS: list[dict] = [
    LIM(
        "LIM-LLS-001",
        "Simulator-only validation",
        "Cage validated on synthetic simulator only.",
        "environment",
        "Real dynamics not covered",
        "Hardware-in-the-loop",
        "Demo/simulation scope only",
        "HIGH",
        "OPEN",
        ["REQ-S-001"],
        ["RISK-LLS-003"],
    ),
    LIM(
        "LIM-LLS-002",
        "Common-mode dependency unresolved",
        "Shared preprocessing between ML and physics estimator.",
        "architecture",
        "Independence claim not supported",
        "Decouple chains (ACT-LLS-02)",
        "Resolve before real use",
        "HIGH",
        "OPEN",
        ["REQ-S-001"],
        ["RISK-LLS-001"],
    ),
    LIM(
        "LIM-LLS-003",
        "Fallback oscillation on incoherent sensors",
        "Plan selection oscillates without hysteresis.",
        "system",
        "Degraded behaviour during incoherence",
        "Hysteresis + plan-lock (ACT-LLS-01)",
        "Mitigation in progress",
        "MEDIUM",
        "MITIGATED",
        ["REQ-R-002"],
        ["RISK-LLS-002"],
    ),
    LIM(
        "LIM-LLS-004",
        "Synthetic landing dataset",
        "Scenarios generated, not from a real lander.",
        "dataset",
        "Coverage claims demo-only",
        "Ground campaign",
        "Demo scope only",
        "MEDIUM",
        "ACCEPTED",
        ["REQ-R-001"],
        [],
    ),
]

DEPLOYMENT = DEC(
    "DEC-LLS-001",
    "CONDITIONAL_GO",
    "Conditional go for simulation/demonstration environments only; no-go for real flight use.",
    "Safety cage rejects unsafe commands (Monte Carlo: 0 violations released) and activates fallback within the "
    "time budget. Common-mode independence is not demonstrated (INCONCLUSIVE) and validation is simulator-only, "
    "so real flight use is excluded.",
    blocking=["TEST-LLS-011"],
    accepted=["RISK-LLS-002"],
    mitigations=[
        "Decouple shared preprocessing (ACT-LLS-02)",
        "Hysteresis for incoherent sensors (ACT-LLS-01)",
        "Independent V&V + hardware-in-the-loop for any real use",
    ],
    constraints=["Simulation/demonstration only", "No real flight use"],
    monitoring=[
        "rejected_commands",
        "fallback_activation",
        "ml_physics_disagreement",
        "ood_events",
        "constraint_violations",
    ],
    rollback="Abort landing sequence; switch to fully deterministic pre-planned guidance.",
)

MONITORING = {
    "status": "PARTIAL",
    "objectives": ["Confirm cage rejects all unsafe commands", "Detect estimator disagreement trends"],
    "metrics": [
        {
            "name": "rejected_commands",
            "description": "Commands rejected by cage",
            "threshold": "expected ratio per scenario class",
        },
        {
            "name": "fallback_activation",
            "description": "Fallback activations",
            "threshold": "alert if no fallback within 100 ms",
        },
        {
            "name": "ml_physics_disagreement",
            "description": "Divergence between ML and physics estimate",
            "threshold": "alert > 0.12",
        },
        {"name": "ood_events", "description": "OOD events per run", "threshold": "alert on any"},
        {
            "name": "constraint_violations",
            "description": "Released constraint violations",
            "threshold": "alert > 0 (must be 0)",
        },
    ],
    "alert_thresholds": {"divergence_limit": 0.12, "constraint_violations": 0, "fallback_ms": 100},
    "sampling_frequency": "per guidance cycle",
    "retention": "full event log per demo run",
    "telemetry_budget": "within demo budget",
    "escalation": "Cage watchdog -> landing supervisor -> abort",
    "safe_state": "Deterministic pre-planned guidance (no ML)",
    "rollback_trigger": "Unsafe command released or divergence beyond limit",
    "retraining_trigger": "Sustained OOD events in target terrain class",
    "investigation_workflow": "Violation -> cage logic review -> scenario regression (Monte Carlo)",
    "ownership": "Landing demo team",
    "review_frequency": "per campaign + weekly",
}

ODD = {
    "status": "PARTIAL",
    "operational_objective": "Validate ML landing commands before release during simulated lunar descent.",
    "environment": "Synthetic lunar landing simulator (flat/rocky terrain classes).",
    "input_ranges": [
        {"dimension": "altitude", "range": "[5, 2000] m", "coverage": "VERIFIED"},
        {"dimension": "vertical_velocity", "range": "[-40, 10] m/s (reject beyond)", "coverage": "VERIFIED"},
        {"dimension": "horizontal_velocity", "range": "[0, 25] m/s (reject beyond)", "coverage": "VERIFIED"},
        {"dimension": "fuel_margin", "range": ">= 5% (abort below)", "coverage": "VERIFIED"},
        {"dimension": "terrain_class", "range": "flat, rocky (trained)", "coverage": "PARTIAL"},
        {
            "dimension": "sensor_coherence",
            "range": "coherent (incoherence handled via fallback)",
            "coverage": "PARTIAL",
        },
    ],
    "supported_modes": ["Nominal descent", "Noisy sensors (within bound)"],
    "unsupported_modes": ["Real flight", "Untrained terrain classes", "Radiated/hardware environment"],
    "nominal_region": "All inputs in range; ML/physics divergence <= 0.12.",
    "degraded_region": "One sensor lost or incoherent -> pre-planned fallback.",
    "prohibited_region": "Any command that would violate hard constraints; real use without independent V&V.",
    "transition_conditions": "Divergence or OOD -> cage rejection/fallback; re-entry only after verification.",
    "ood_detection_strategy": "Terrain-feature OOD score + input range checks.",
    "fallback": "Deterministic pre-planned guidance profile.",
    "assumptions": ["Physics estimator validated for demo terrain classes", "No engine-out dynamics modelled"],
    "boundaries_evidence": [{"dimension": "terrain_class", "evidence": "EVID-LLS-006"}],
}

MODEL_CARD = {
    "model_name": "Lunar landing guidance ML (protected by safety cage)",
    "model_type": "CNN guidance regressor",
    "task": "Generate landing guidance commands (subject of the cage)",
    "intended_use": "Generate candidate commands that are validated by the deterministic safety cage in simulation.",
    "users": ["Landing demo team", "Safety review (demonstration)"],
    "prohibited_uses": ["Direct command release without cage", "Real flight use"],
    "input": "camera + inertial state window",
    "output": "desired vertical/horizontal velocity + throttle",
    "training_data_summary": "Synthetic landing trajectories (v1.1).",
    "validation_data_summary": "15% reserved.",
    "test_data_summary": "nominal/noise/sensor-loss/terrain-OOD/low-fuel/incoherent subsets.",
    "preprocessing": "shared with physics estimator (identified as common-mode risk).",
    "metrics": {"unsafe_command_rejection_rate": 1.0, "false_rejection_rate": 0.01, "fallback_activation_ms": 74},
    "metric_thresholds": {"constraint_violations": 0, "fallback_ms": 100},
    "known_failure_modes": ["Divergent outputs in untrained terrain", "Sensitive to shared preprocessing"],
    "robustness": "See TEST-LLS-002/003/004/010.",
    "ood_behavior": "OOD flag -> cage rejection.",
    "uncertainty_handling": "Physics-estimator disagreement as proxy.",
    "quantization": "Not quantized.",
    "hardware_target": "Simulated lander computer",
    "inference_constraints": "Budget for cage fallback < 100 ms",
    "limitations": ["Simulator-only", "Common-mode dependency open"],
    "maintenance_owner": "Landing demo team",
    "version_history": [{"version": "v1", "change": "current"}],
}

DATA_QUALITY = {
    "dataset_name": "Lunar landing scenario suite",
    "dataset_version": "v1.1.0",
    "source": "Synthetic trajectory generator (declared synthetic)",
    "synthetic": True,
    "description": "Nominal, noisy, sensor-loss, terrain-OOD, low-fuel and incoherent-sensor scenarios.",
    "row_counts": {"scenarios": 320, "monte_carlo_profiles": 500},
    "columns": 12,
    "missing": "None",
    "duplicates": "None",
    "outliers": "OOD terrain subset intentionally extreme",
    "class_balance": "Scenario classes balanced by design",
    "time_coverage": "Full descent profiles",
    "representativeness": "Good for demo terrain; real terrain/fuel dynamics unverified",
    "split_strategy": "scenario-class split, not random (avoid leakage across profiles)",
    "leakage_indicators": "None identified (class-based split)",
    "quality_findings": ["Real dynamics not modelled", "Incoherent-sensor coverage partial"],
    "severity": "MEDIUM",
    "data_readiness_score": 91.0,
    "score_coverage": 88.0,
    "review_status": "Conditionally Ready",
    "limitations": ["Synthetic only", "Simplified fuel/terrain physics"],
}

PROJECT: dict = {
    "meta": {
        "id": "PRJ-LLS-001",
        "slug": "lunar-landing-safety-cage",
        "name": "Lunar Landing Safety Cage",
        "short_description": "Deterministic safety cage validating ML landing commands against physical and operational constraints with deterministic fallback.",
        "domain": "landing-safety",
        "use_case": "Safe validation of ML guidance commands",
        "operational_context": "Simulated lunar landing descent",
        "criticality": "Critical",
        "deployment_target": "Simulation/demonstration (real flight excluded)",
        "execution_environment": "Synthetic landing simulator",
        "lifecycle_status": "UNDER_VERIFICATION",
        "assurance_status": "REVIEW_REQUIRED",
        "owner": "Landing demo team",
        "version": "1.0.0",
        "model_version": MODEL,
        "dataset_version": "v1.1.0",
        "tags": ["safety-cage", "landing", "fallback", "synthetic"],
    },
    "requirements": REQS,
    "tests": TESTS,
    "evidence": EVIDENCE,
    "risks": RISKS,
    "fmea": FMEA,
    "limitations": LIMITATIONS,
    "deployment_decisions": [DEPLOYMENT],
    "monitoring": MONITORING,
    "odd": ODD,
    "model_card": MODEL_CARD,
    "data_quality": DATA_QUALITY,
}
