"""Onboard Vision Quantization Lab — synthetic demonstration content (week 3)."""

from app.portfolio.datadefs.builders import DEC, FM, LIM, RISK, TC, TR, E, R

MODEL = "vision-quant-studio-v1"
REQS: list[dict] = [
    R(
        "REQ-F-001",
        "Benchmark FP32/FP16/INT8 variants",
        "FUNCTIONAL",
        "The lab shall compare FP32, FP16 and INT8 variants of the vision model on accuracy, latency, memory and size.",
        "TEST",
        "Benchmark matrix produced for the three precisions.",
        "HIGH",
        "VERIFIED",
    ),
    R(
        "REQ-P-001",
        "Minimum top-1 accuracy",
        "PERFORMANCE",
        "FP32 baseline shall reach top-1 accuracy >= 0.90 on the validation split.",
        "TEST",
        "FP32 top-1 >= 0.90.",
        "HIGH",
        "VERIFIED",
    ),
    R(
        "REQ-P-002",
        "Maximum INT8 degradation",
        "PERFORMANCE",
        "INT8 top-1 accuracy shall stay within 1.0 point of the FP32 baseline.",
        "TEST",
        "INT8 top-1 >= FP32 top-1 - 1.0 point.",
        "HIGH",
        "VERIFIED",
    ),
    R(
        "REQ-P-003",
        "Latency envelope",
        "PERFORMANCE",
        "INT8 inference latency shall be below 20 ms p95 on the simulated target.",
        "TEST",
        "p95 < 20 ms on simulated target.",
        "MEDIUM",
        "VERIFIED",
    ),
    R(
        "REQ-R-001",
        "Operator compatibility",
        "EMBEDDED_RESOURCE",
        "All model operators shall be supported by the INT8 runtime (no fallback to FP32).",
        "TEST",
        "unsupported_operators == 0.",
        "HIGH",
        "VERIFIED",
    ),
    R(
        "REQ-R-002",
        "Peak memory bound",
        "EMBEDDED_RESOURCE",
        "INT8 inference peak RAM shall stay below 48 MB.",
        "TEST",
        "peak RAM < 48 MB.",
        "MEDIUM",
        "VERIFIED",
    ),
    R(
        "REQ-E-001",
        "Model size bound",
        "EMBEDDED_RESOURCE",
        "Quantized model size shall be below 6 MB.",
        "TEST",
        "INT8 model size < 6 MB.",
        "MEDIUM",
        "VERIFIED",
    ),
    R(
        "REQ-RB-001",
        "Robustness to illumination",
        "ROBUSTNESS",
        "Accuracy degradation under low illumination shall be bounded (top-1 drop <= 5 points).",
        "TEST",
        "top-1 drop <= 5 points on low-illumination subset.",
        "MEDIUM",
        "NOT_VERIFIED",
    ),
    R(
        "REQ-RB-002",
        "Robustness to noise",
        "ROBUSTNESS",
        "Accuracy degradation under sensor noise shall be bounded (top-1 drop <= 3 points).",
        "TEST",
        "top-1 drop <= 3 points on noisy subset.",
        "MEDIUM",
        "VERIFIED",
    ),
    R(
        "REQ-RB-003",
        "Low-contrast inputs",
        "ROBUSTNESS",
        "Low-contrast image handling shall be assessed and documented.",
        "TEST",
        "measured top-1 reported; regression vs baseline documented.",
        "LOW",
        "VERIFIED",
    ),
    R(
        "REQ-B-001",
        "Benchmark reproducibility",
        "DATA",
        "Benchmark runs shall be reproducible with fixed seeds and pinned versions.",
        "TEST",
        "two runs within 0.1 point accuracy.",
        "MEDIUM",
        "VERIFIED",
    ),
    R(
        "REQ-NF-001",
        "Estimated power envelope",
        "PERFORMANCE",
        "Estimated INT8 energy per inference shall be reported (simulated).",
        "ANALYSIS",
        "estimate attached and labelled simulated.",
        "LOW",
        "VERIFIED",
    ),
]

TESTS: list[dict] = [
    {
        **TC(
            "TEST-QNT-001",
            "FP32 baseline accuracy",
            "QUANTIZATION",
            "Reference precision.",
            "top-1 >= 0.90",
            ["REQ-P-001"],
            "HIGH",
        ),
        **TR(
            "TEST-QNT-001",
            "PASS",
            "RUN-QNT-001",
            "lab-x86",
            MODEL,
            "vision-ds-v1.3",
            "top-1 0.912.",
            {"top1": 0.912},
            evidence_ids=["EVID-QNT-001"],
        ),
    },
    {
        **TC(
            "TEST-QNT-002",
            "FP16 accuracy",
            "QUANTIZATION",
            "FP16 vs FP32.",
            "delta <= 0.2 points",
            ["REQ-P-001", "REQ-P-002"],
            "HIGH",
        ),
        **TR(
            "TEST-QNT-002",
            "PASS",
            "RUN-QNT-002",
            "lab-x86",
            MODEL,
            "vision-ds-v1.3",
            "top-1 0.910 (delta -0.2).",
            {"top1": 0.910, "delta_vs_fp32": -0.002},
            evidence_ids=["EVID-QNT-001"],
        ),
    },
    {
        **TC(
            "TEST-QNT-003",
            "INT8 accuracy",
            "QUANTIZATION",
            "INT8 vs FP32.",
            "delta >= -1.0 points",
            ["REQ-P-002"],
            "HIGH",
        ),
        **TR(
            "TEST-QNT-003",
            "PASS",
            "RUN-QNT-003",
            "lab-x86",
            MODEL,
            "vision-ds-v1.3",
            "top-1 0.905 (delta -0.7).",
            {"top1": 0.905, "delta_vs_fp32": -0.007},
            evidence_ids=["EVID-QNT-001", "EVID-QNT-002"],
        ),
    },
    {
        **TC(
            "TEST-QNT-004", "INT8 latency p95", "LATENCY", "On simulated target.", "p95 < 20 ms", ["REQ-P-003"], "HIGH"
        ),
        **TR(
            "TEST-QNT-004",
            "PASS",
            "RUN-QNT-004",
            "sim-target",
            MODEL,
            "vision-ds-v1.3",
            "p95 12.4 ms (INT8).",
            {"latency_p95_ms": 12.4, "latency_p50_ms": 9.1},
            evidence_ids=["EVID-QNT-003"],
        ),
    },
    {
        **TC(
            "TEST-QNT-005",
            "Operator compatibility",
            "INTEGRATION",
            "INT8 runtime operator check.",
            "0 unsupported operators",
            ["REQ-R-001"],
            "HIGH",
        ),
        **TR(
            "TEST-QNT-005",
            "PASS",
            "RUN-QNT-005",
            "lab-x86",
            MODEL,
            "vision-ds-v1.3",
            "unsupported_operators 0.",
            {"unsupported_operators": 0},
        ),
    },
    {
        **TC("TEST-QNT-006", "INT8 memory profile", "RESOURCE", "Peak RAM.", "< 48 MB", ["REQ-R-002"], "MEDIUM"),
        **TR(
            "TEST-QNT-006",
            "PASS",
            "RUN-QNT-006",
            "sim-target",
            MODEL,
            "vision-ds-v1.3",
            "peak 31 MB.",
            {"peak_ram_mb": 31},
            evidence_ids=["EVID-QNT-003"],
        ),
    },
    {
        **TC("TEST-QNT-007", "Model size", "RESOURCE", "INT8 artefact size.", "< 6 MB", ["REQ-E-001"], "MEDIUM"),
        **TR(
            "TEST-QNT-007",
            "PASS",
            "RUN-QNT-007",
            "lab-x86",
            MODEL,
            "vision-ds-v1.3",
            "size 4.8 MB.",
            {"model_size_mb": 4.8},
        ),
    },
    {
        **TC(
            "TEST-QNT-008",
            "Low illumination",
            "ROBUSTNESS",
            "Extreme dark inputs.",
            "top-1 drop <= 5 points",
            ["REQ-RB-001"],
            "HIGH",
        ),
        **TR(
            "TEST-QNT-008",
            "FAIL",
            "RUN-QNT-008",
            "lab-x86",
            MODEL,
            "vision-ds-dark-v1.3",
            "top-1 0.83 (drop -8.2 points).",
            {"top1": 0.83, "drop_vs_baseline": -0.082},
            failure_reason="Dark subset outside expected illumination range; pre-processing gain insufficient.",
            reviewer_notes="Open action ACT-QNT-01: illumination augmentation + gain calibration.",
            evidence_ids=["EVID-QNT-004"],
        ),
    },
    {
        **TC(
            "TEST-QNT-009",
            "Sensor noise robustness",
            "ROBUSTNESS",
            "Gaussian noise.",
            "top-1 drop <= 3 points",
            ["REQ-RB-002"],
            "MEDIUM",
        ),
        **TR(
            "TEST-QNT-009",
            "PASS",
            "RUN-QNT-009",
            "lab-x86",
            MODEL,
            "vision-ds-noise-v1.3",
            "drop -1.9 points.",
            {"drop_vs_baseline": -0.019},
        ),
    },
    {
        **TC(
            "TEST-QNT-010",
            "Low contrast",
            "ROBUSTNESS",
            "Contrast-reduced subset.",
            "reported; regression documented",
            ["REQ-RB-003"],
            "LOW",
        ),
        **TR(
            "TEST-QNT-010",
            "INCONCLUSIVE",
            "RUN-QNT-010",
            "lab-x86",
            MODEL,
            "vision-ds-lowcontrast-v1.3",
            "Result not stable across contrast levels; needs metric agreement.",
            failure_reason="Metric definition for low-contrast subset under discussion.",
            reviewer_notes="ACT-QNT-02: agree low-contrast metric.",
            evidence_ids=["EVID-QNT-005"],
        ),
    },
    {
        **TC(
            "TEST-QNT-011",
            "Benchmark reproducibility",
            "DATA",
            "Two identical runs.",
            "delta <= 0.1 points",
            ["REQ-B-001"],
            "MEDIUM",
        ),
        **TR(
            "TEST-QNT-011",
            "PASS",
            "RUN-QNT-011",
            "lab-x86",
            MODEL,
            "vision-ds-v1.3",
            "delta 0.04 points across runs.",
            {"delta_between_runs": 0.0004},
        ),
    },
]

EVIDENCE: list[dict] = [
    E(
        "EVID-QNT-001",
        "Accuracy comparison matrix",
        "MODEL_METRIC",
        "FP32/FP16/INT8 top-1 on validation split.",
        ["REQ-P-001", "REQ-P-002"],
        ["TEST-QNT-001", "TEST-QNT-002", "TEST-QNT-003"],
        attachment="qnt-accuracy-matrix.txt",
    ),
    E(
        "EVID-QNT-002",
        "Calibration dataset notes",
        "DOCUMENT",
        "INT8 calibration procedure and dataset.",
        ["REQ-P-002"],
        ["TEST-QNT-003"],
    ),
    E(
        "EVID-QNT-003",
        "Target benchmark run log",
        "LOG",
        "Latency + memory run on simulated target.",
        ["REQ-P-003", "REQ-R-002"],
        ["TEST-QNT-004", "TEST-QNT-006"],
        attachment="qnt-target-benchmark.log",
    ),
    E(
        "EVID-QNT-004",
        "Dark-subset evaluation log",
        "LOG",
        "Failure evidence for low-illumination subset.",
        ["REQ-RB-001"],
        ["TEST-QNT-008"],
    ),
    E(
        "EVID-QNT-005",
        "Low-contrast metric discussion",
        "REVIEW_RECORD",
        "Open metric question for low-contrast subset.",
        ["REQ-RB-003"],
        ["TEST-QNT-010"],
    ),
    E(
        "EVID-QNT-006",
        "Operator support matrix",
        "SOURCE_REFERENCE",
        "Runtime operator support check output.",
        ["REQ-R-001"],
        ["TEST-QNT-005"],
    ),
    E(
        "EVID-QNT-007",
        "Model size & RAM report",
        "BENCHMARK",
        "INT8 size and memory figures.",
        ["REQ-R-002", "REQ-E-001"],
        ["TEST-QNT-006", "TEST-QNT-007"],
    ),
    E(
        "EVID-QNT-008",
        "Reproducibility runs",
        "CONFIGURATION",
        "Pinned toolchain and seed record.",
        ["REQ-B-001"],
        ["TEST-QNT-011"],
    ),
]

RISKS: list[dict] = [
    RISK(
        "RISK-QNT-001",
        "Quantization accuracy loss beyond bound",
        "INT8 accuracy drops below threshold",
        "Representation limits on hard samples",
        "Task performance below requirement",
        3,
        3,
        "Calibration tuning + per-layer sensitivity analysis",
        "EVID-QNT-001/002; TEST-QNT-003",
        2,
        2,
        "ACCEPTABLE",
        "Delta -0.7 points within the 1.0 point budget with margin.",
        ["REQ-P-002"],
        ["TEST-QNT-003"],
        ["FM-QNT-001"],
    ),
    RISK(
        "RISK-QNT-002",
        "Low-illumination degradation",
        "Performance drops in dark scenes",
        "Inputs outside expected illumination",
        "Operational task failure in low light",
        4,
        3,
        "Gain calibration + augmentation (ACT-QNT-01)",
        "TEST-QNT-008 currently FAIL",
        4,
        2,
        "REQUIRES_MITIGATION",
        "Not acceptable without mitigation; limits low-light operation.",
        ["REQ-RB-001"],
        ["TEST-QNT-008"],
        ["FM-QNT-003"],
    ),
    RISK(
        "RISK-QNT-003",
        "Hardware benchmark gap",
        "Simulated target differs from real hardware",
        "No board available",
        "Latency/RAM figures not representative",
        3,
        3,
        "Target-specific benchmark before deployment",
        "RUN-QNT-004 (simulated target)",
        3,
        3,
        "REVIEW_REQUIRED",
        "Simulated-target results reviewed before any deployment decision.",
        ["REQ-P-003"],
        ["TEST-QNT-004"],
        ["FM-QNT-004"],
    ),
]

FMEA: list[dict] = [
    FM(
        "FM-QNT-001",
        "Provide INT8 model",
        "Quantization-induced accuracy loss",
        "Top-1 drop",
        "Task performance loss",
        "Calibration set not representative",
        "Accuracy delta monitoring",
        "Calibration on dev split",
        3,
        3,
        3,
        "Extend calibration set",
        "Calibration + per-layer sensitivity",
        "L",
        ["REQ-P-002"],
        ["TEST-QNT-003"],
        ["EVID-QNT-001"],
    ),
    FM(
        "FM-QNT-002",
        "Run quantized operators",
        "Unsupported operator fallback",
        "Silent FP32 fallback",
        "Latency/memory violation",
        "Operator unsupported",
        "Operator audit",
        "Static operator check",
        4,
        2,
        2,
        "Replace unsupported ops",
        "Operator compatibility check",
        "L",
        ["REQ-R-001"],
        ["TEST-QNT-005"],
        ["EVID-QNT-006"],
    ),
    FM(
        "FM-QNT-003",
        "Process low-light input",
        "Failure under low illumination",
        "Accuracy drop > 5 points",
        "Task miss in dark scenes",
        "Input gain mismatch",
        "Illumination robustness test",
        "Gain calibration (planned)",
        4,
        3,
        3,
        "Augment + calibrate",
        "Restrict low-light operation",
        "H",
        ["REQ-RB-001"],
        ["TEST-QNT-008"],
        ["EVID-QNT-004"],
    ),
    FM(
        "FM-QNT-004",
        "Serve inference within deadline",
        "Latency deadline exceeded",
        "Late output",
        "Control loop miss",
        "Target overload",
        "Latency p95 monitoring",
        "INT8 + resource headroom",
        4,
        2,
        3,
        "Target benchmark",
        "Time budget enforcement",
        "M",
        ["REQ-P-003"],
        ["TEST-QNT-004"],
        ["EVID-QNT-003"],
    ),
    FM(
        "FM-QNT-005",
        "Produce benchmark numbers",
        "Non-reproducible benchmark",
        "Metrics cannot be trusted",
        "Wrong deployment call",
        "Environment drift",
        "Reproducibility test",
        "Pinned toolchain + seeds",
        3,
        2,
        2,
        "Version pinning",
        "Seeded reproducible runs",
        "L",
        ["REQ-B-001"],
        ["TEST-QNT-011"],
        ["EVID-QNT-008"],
    ),
]

LIMITATIONS: list[dict] = [
    LIM(
        "LIM-QNT-001",
        "Hardware benchmark on simulator",
        "Latency/memory measured on simulated target only.",
        "deployment",
        "Figures may differ on real board",
        "Repeat on real target",
        "Target benchmark required before deployment",
        "HIGH",
        "OPEN",
        ["REQ-P-003"],
        ["RISK-QNT-003"],
    ),
    LIM(
        "LIM-QNT-002",
        "Low illumination not mitigated",
        "Dark subset fails by 8.2 points.",
        "model",
        "Limited low-light operation",
        "Gain calibration (ACT-QNT-01)",
        "Restrict low-light use",
        "HIGH",
        "OPEN",
        ["REQ-RB-001"],
        ["RISK-QNT-002"],
    ),
    LIM(
        "LIM-QNT-003",
        "Low-contrast metric unresolved",
        "INCONCLUSIVE test.",
        "test",
        "Coverage claim pending",
        "Agree metric (ACT-QNT-02)",
        "None",
        "MEDIUM",
        "UNDER_REVIEW",
        ["REQ-RB-003"],
        [],
    ),
]

DEPLOYMENT = DEC(
    "DEC-QNT-001",
    "CONDITIONAL_GO",
    "Conditional go for INT8 variant in laboratory/demonstration use.",
    "INT8 meets accuracy (delta -0.7), latency (p95 12.4 ms) and memory bounds. Low-illumination failure and "
    "simulator-only hardware results impose conditions.",
    blocking=["TEST-QNT-008"],
    accepted=["RISK-QNT-001"],
    mitigations=["Target-specific benchmark on real hardware", "Low-illumination mitigation before low-light use"],
    constraints=["Laboratory/demonstration only", "No low-light operation until mitigation verified"],
    monitoring=["latency_p95", "memory_peak", "operator_fallback", "image_quality_distribution", "accuracy_proxy"],
    rollback="Deploy FP16/FP32 variant; keep INT8 behind feature flag.",
)

MONITORING = {
    "status": "PARTIAL",
    "objectives": ["Watch quantization drift in operation", "Confirm latency and memory envelopes"],
    "metrics": [
        {"name": "latency_p95", "description": "Rolling p95 inference latency", "threshold": "alert > 18 ms"},
        {"name": "memory_peak", "description": "Peak RAM per run", "threshold": "alert > 44 MB"},
        {"name": "operator_fallback", "description": "Silent FP32 fallback count", "threshold": "alert > 0"},
        {
            "name": "image_quality_distribution",
            "description": "Brightness/contrast histogram distance",
            "threshold": "alert on shift > 2 sigma",
        },
        {
            "name": "accuracy_proxy",
            "description": "Heuristic accuracy proxy on labelled samples",
            "threshold": "alert if proxy drops > 1 point",
        },
    ],
    "alert_thresholds": {"latency_p95_ms": 18, "ram_mb": 44, "accuracy_delta": 0.01},
    "sampling_frequency": "per inference batch",
    "retention": "30 days aggregates",
    "telemetry_budget": "within onboard limit",
    "escalation": "Local monitor -> model owner",
    "safe_state": "Fallback to FP16 variant",
    "rollback_trigger": "Accuracy proxy drop or operator fallback",
    "retraining_trigger": "Sustained image distribution shift",
    "investigation_workflow": "Review inputs -> calibration drift -> recalibrate",
    "ownership": "Vision lab demo team",
    "review_frequency": "bi-weekly",
}

ODD = {
    "status": "PARTIAL",
    "operational_objective": "Onboard vision classification within quantized envelope.",
    "environment": "Simulated orbital lighting; onboard-class CPU target (simulated).",
    "input_ranges": [
        {"dimension": "illumination", "range": "moderate to bright (excludes extreme dark)", "coverage": "PARTIAL"},
        {"dimension": "sensor_noise", "range": "sigma <= 0.05", "coverage": "VERIFIED"},
        {"dimension": "contrast", "range": "metric under review", "coverage": "NOT_VERIFIED"},
        {"dimension": "frame_rate", "range": ">= 10 fps", "coverage": "VERIFIED"},
    ],
    "supported_modes": ["Day-side imaging", "Laboratory benchmarking"],
    "unsupported_modes": ["Extreme low light", "Real hardware target (not yet validated)"],
    "nominal_region": "Moderate lighting, noise within bound.",
    "degraded_region": "Noisy inputs (within bound); slight contrast loss.",
    "prohibited_region": "Real mission deployment without target validation.",
    "transition_conditions": "Distribution monitor triggers review; no autonomous mode switch in lab.",
    "ood_detection_strategy": "Input brightness/contrast monitor (proxy).",
    "fallback": "FP16/FP32 variant switch.",
    "assumptions": ["Imager response linear within range", "Calibration gain as per spec v1.2"],
    "boundaries_evidence": [{"dimension": "illumination", "evidence": "EVID-QNT-004"}],
}

MODEL_CARD = {
    "model_name": "Vision classification model (baseline FP32)",
    "model_type": "CNN classifier",
    "task": "Onboard image classification (demonstration)",
    "intended_use": "Compare FP32/FP16/INT8 variants; INT8 for onboard demo.",
    "users": ["Onboard AI demonstration team"],
    "prohibited_uses": ["Low-light operation", "Real mission flight use"],
    "input": "grayscale 224x224 image",
    "output": "class logits / top-1 label",
    "training_data_summary": "Synthetic image dataset v1.3 (lab renders + augmentations).",
    "validation_data_summary": "15% reserved split.",
    "test_data_summary": "clean, noise, dark, low-contrast subsets (v1.3).",
    "preprocessing": "mean/std normalisation fitted on train split.",
    "metrics": {"top1_fp32": 0.912, "top1_fp16": 0.910, "top1_int8": 0.905},
    "metric_thresholds": {"top1_min": 0.90, "int8_delta_max": 0.01},
    "known_failure_modes": ["Extreme dark images (-8.2 points)", "Low-contrast metric unresolved"],
    "robustness": "See TEST-QNT-008/009/010.",
    "ood_behavior": "Illumination monitor flags out-of-range inputs.",
    "uncertainty_handling": "Softmax confidence; no calibrated uncertainty in this version.",
    "quantization": {"fp16_delta": -0.002, "int8_delta": -0.007, "int8_size_mb": 4.8},
    "hardware_target": "Simulated onboard CPU",
    "inference_constraints": "INT8 p95 12.4 ms (simulated target)",
    "limitations": ["Simulator-only hardware figures", "Dark input failure open"],
    "maintenance_owner": "Vision lab demo team",
    "version_history": [{"version": "v1", "change": "current"}],
}

DATA_QUALITY = {
    "dataset_name": "Vision quantization benchmark suite",
    "dataset_version": "v1.3.0",
    "source": "Synthetic lab renders (declared synthetic)",
    "synthetic": True,
    "description": "Clean, noise, dark and low-contrast subsets with fixed seeds.",
    "row_counts": {"train": 4200, "validation": 750, "test": 750, "dark": 300, "noise": 300},
    "columns": 1,
    "missing": "None",
    "duplicates": "None",
    "outliers": "Dark subset intentionally extreme",
    "class_balance": "Balanced across classes",
    "time_coverage": "Not time-ordered",
    "representativeness": "Good for lab demo; low-light underrepresented vs expected ops",
    "split_strategy": "random 70/15/15, seed 42",
    "leakage_indicators": "None identified",
    "quality_findings": ["Dark subset reveals illumination gap", "Low-contrast metric unclear"],
    "severity": "MEDIUM",
    "data_readiness_score": 88.0,
    "score_coverage": 88.0,
    "review_status": "Conditionally Ready",
    "limitations": ["Synthetic renders only", "No on-orbit imagery"],
}

PROJECT: dict = {
    "meta": {
        "id": "PRJ-QNT-001",
        "slug": "onboard-vision-quantization-lab",
        "name": "Onboard Vision Quantization Lab",
        "short_description": "Laboratory comparing FP32/FP16/INT8 onboard vision variants for accuracy, latency, memory and size.",
        "domain": "onboard-computer-vision",
        "use_case": "Post-training quantization evaluation",
        "operational_context": "Laboratory and simulated onboard target",
        "criticality": "Medium",
        "deployment_target": "Laboratory / simulated onboard",
        "execution_environment": "Lab x86 + simulated onboard target",
        "lifecycle_status": "UNDER_VERIFICATION",
        "assurance_status": "PARTIALLY_SUPPORTED",
        "owner": "Vision lab demo team",
        "version": "0.9.0",
        "model_version": MODEL,
        "dataset_version": "v1.3.0",
        "tags": ["vision", "quantization", "onboard", "synthetic"],
    },
    "requirements": REQS,
    "tests": TESTS,
    "evidence": EVIDENCE,
    "risks": RISKS,
    "fmea": FMEA,
    "limitations": LIMITATIONS,
    "deployment_decisions": [DEPLOYMENT],
    "monitoring": MONITORING,
    "odd": ODD,
    "model_card": MODEL_CARD,
    "data_quality": DATA_QUALITY,
}
