"""SEU Fault Injector — synthetic demonstration content (week 3)."""

from app.portfolio.datadefs.builders import DEC, FM, LIM, RISK, TC, TR, E, R

MODEL = "tad-model-under-injection-v0.4.1"  # model subject to injection (not the injector)
REQS: list[dict] = [
    R(
        "REQ-F-001",
        "Reproducible fault injection",
        "FUNCTIONAL",
        "The injector shall flip bits in weights/activations/buffers deterministically for a given seed.",
        "TEST",
        "Same seed reproduces identical fault campaign.",
        "HIGH",
        "VERIFIED",
    ),
    R(
        "REQ-F-002",
        "Layer and bit selection",
        "FUNCTIONAL",
        "Campaigns shall support selecting layer index and bit position (including sign bit).",
        "TEST",
        "Selection applied as specified.",
        "HIGH",
        "VERIFIED",
    ),
    R(
        "REQ-F-003",
        "Quantized weight support",
        "FUNCTIONAL",
        "Injection shall support INT8 quantized weights.",
        "TEST",
        "INT8 campaign executed.",
        "HIGH",
        "VERIFIED",
    ),
    R(
        "REQ-P-001",
        "Degradation measurement",
        "PERFORMANCE",
        "Accuracy degradation per fault shall be measured and recorded.",
        "TEST",
        "degradation recorded for every injection.",
        "HIGH",
        "VERIFIED",
    ),
    R(
        "REQ-P-002",
        "Vulnerable layer identification",
        "PERFORMANCE",
        "Campaign results shall rank layers by vulnerability score.",
        "TEST",
        "ranking produced.",
        "MEDIUM",
        "VERIFIED",
    ),
    R(
        "REQ-R-001",
        "Error detection (checksum)",
        "ROBUSTNESS",
        "Model memory shall be protected by checksums so corruption is detected.",
        "TEST",
        "checksum detects injected corruption in 100% of check cases.",
        "HIGH",
        "VERIFIED",
    ),
    R(
        "REQ-R-002",
        "Voting / redundancy",
        "ROBUSTNESS",
        "A redundant voting scheme shall mask single faults.",
        "TEST",
        "voting masks single-fault cases; overhead measured.",
        "MEDIUM",
        "VERIFIED",
    ),
    R(
        "REQ-M-001",
        "Fault logging",
        "MONITORING",
        "Every injected fault, location and outcome shall be logged and exportable.",
        "TEST",
        "log completeness verified.",
        "MEDIUM",
        "VERIFIED",
    ),
    R(
        "REQ-S-001",
        "Catastrophic output containment",
        "SAFETY",
        "Faults causing catastrophic outputs shall be detected before use.",
        "TEST",
        "catastrophic outputs detected via sanity checks (subset).",
        "HIGH",
        "FAILED",
    ),
    R(
        "REQ-NF-001",
        "Injection overhead",
        "PERFORMANCE",
        "Checksum + logging execution overhead shall stay below 15%.",
        "TEST",
        "overhead measured on simulated target.",
        "MEDIUM",
        "NOT_VERIFIED",
    ),
]

TESTS: list[dict] = [
    {
        **TC(
            "TEST-SEU-001",
            "Single bit flip",
            "FAULT_INJECTION",
            "One weight bit flip.",
            "outcome logged; degradation measured",
            ["REQ-F-001", "REQ-P-001"],
            "HIGH",
        ),
        **TR(
            "TEST-SEU-001",
            "PASS",
            "RUN-SEU-001",
            "seu-harness",
            MODEL,
            "tad-model-weights-v0.4.1",
            "100 injections logged; mean degradation 0.4 points.",
            {"injection_count": 100, "mean_degradation": 0.004},
        ),
    },
    {
        **TC(
            "TEST-SEU-002",
            "Multiple bit flips",
            "FAULT_INJECTION",
            "3 bit flips per run.",
            "outcome logged",
            ["REQ-F-001", "REQ-P-001"],
            "MEDIUM",
        ),
        **TR(
            "TEST-SEU-002",
            "PASS",
            "RUN-SEU-002",
            "seu-harness",
            MODEL,
            "tad-model-weights-v0.4.1",
            "60 injections; degradation up to 3.1 points.",
            {"injection_count": 60},
        ),
    },
    {
        **TC(
            "TEST-SEU-003",
            "Sign bit flip",
            "FAULT_INJECTION",
            "Flip sign bit of weight.",
            "measured",
            ["REQ-F-002", "REQ-P-001"],
            "HIGH",
        ),
        **TR(
            "TEST-SEU-003",
            "PASS",
            "RUN-SEU-003",
            "seu-harness",
            MODEL,
            "tad-model-weights-v0.4.1",
            "Sign-bit flips cause worst degradation (up to 22 points).",
            {"max_degradation": 0.22},
        ),
    },
    {
        **TC(
            "TEST-SEU-004",
            "Layer-wise campaign",
            "FAULT_INJECTION",
            "Same bit per layer.",
            "vulnerability ranking",
            ["REQ-P-002"],
            "MEDIUM",
        ),
        **TR(
            "TEST-SEU-004",
            "PASS",
            "RUN-SEU-004",
            "seu-harness",
            MODEL,
            "tad-model-weights-v0.4.1",
            "Encoder layer 2 most vulnerable.",
            {"top_vulnerable_layer": "encoder_2"},
        ),
    },
    {
        **TC(
            "TEST-SEU-005",
            "INT8 fault injection",
            "FAULT_INJECTION",
            "Quantized weights.",
            "executed",
            ["REQ-F-003", "REQ-P-001"],
            "MEDIUM",
        ),
        **TR(
            "TEST-SEU-005",
            "PASS",
            "RUN-SEU-005",
            "seu-harness",
            MODEL,
            "tad-model-int8-v0.4.1",
            "INT8 campaign executed; sign-bit flips severe.",
            {"injection_count": 100},
        ),
    },
    {
        **TC(
            "TEST-SEU-006",
            "Checksum detection",
            "FAULT_INJECTION",
            "Corrupt then verify.",
            "100% detection",
            ["REQ-R-001"],
            "HIGH",
        ),
        **TR(
            "TEST-SEU-006",
            "PASS",
            "RUN-SEU-006",
            "seu-harness",
            MODEL,
            "tad-model-weights-v0.4.1",
            "Checksum detected 40/40 corrupted weights.",
            {"detection_rate": 1.0},
            evidence_ids=["EVID-SEU-003"],
        ),
    },
    {
        **TC(
            "TEST-SEU-007",
            "Triple-module voting",
            "FAULT_INJECTION",
            "Single fault in one replica.",
            "masked",
            ["REQ-R-002"],
            "MEDIUM",
        ),
        **TR(
            "TEST-SEU-007",
            "PASS",
            "RUN-SEU-007",
            "seu-harness",
            MODEL,
            "tad-model-weights-v0.4.1",
            "Voting masked 58/60 single faults; 2 consensus breaks (same sign-bit).",
            {"masked": 58, "consensus_breaks": 2},
            evidence_ids=["EVID-SEU-004"],
        ),
    },
    {
        **TC(
            "TEST-SEU-008",
            "Silent data corruption sweep",
            "FAULT_INJECTION",
            "Detect undetected corruption with significant degradation.",
            "SDC rate reported",
            ["REQ-S-001", "REQ-R-001"],
            "HIGH",
        ),
        **TR(
            "TEST-SEU-008",
            "FAIL",
            "RUN-SEU-008",
            "seu-harness",
            MODEL,
            "tad-model-weights-v0.4.1",
            "SDC rate 4.2% (undetected, degradation > 5 points); catastrophic outputs in 1.1% of injections.",
            {"sdc_rate": 0.042, "catastrophic_output_rate": 0.011},
            failure_reason="Checksums cover weights only; activation/buffer corruption undetected; no output sanity cage.",
            reviewer_notes="Blocking for unmitigated deployment.",
            evidence_ids=["EVID-SEU-002", "EVID-SEU-005"],
        ),
    },
    {
        **TC(
            "TEST-SEU-009",
            "Fault logging export",
            "INTEGRATION",
            "Complete campaign log.",
            "export schema complete",
            ["REQ-M-001"],
            "MEDIUM",
        ),
        **TR(
            "TEST-SEU-009",
            "PASS",
            "RUN-SEU-009",
            "seu-harness",
            MODEL,
            "tad-model-weights-v0.4.1",
            "Export schema verified.",
            {},
            evidence_ids=["EVID-SEU-001"],
        ),
    },
    {
        **TC(
            "TEST-SEU-010",
            "Reproducibility with same seed",
            "FAULT_INJECTION",
            "Same seed twice.",
            "identical outcomes",
            ["REQ-F-001"],
            "HIGH",
        ),
        **TR(
            "TEST-SEU-010",
            "PASS",
            "RUN-SEU-010",
            "seu-harness",
            MODEL,
            "tad-model-weights-v0.4.1",
            "Two runs identical (hash equal).",
            {"identical_runs": True},
        ),
    },
    {
        **TC(
            "TEST-SEU-011",
            "Injection overhead on target",
            "RESOURCE",
            "Checksum+logging overhead.",
            "< 15%",
            ["REQ-NF-001"],
            "MEDIUM",
        ),
        **TR(
            "TEST-SEU-011",
            "NOT_EXECUTED",
            "RUN-SEU-011",
            "sim-target (unavailable)",
            MODEL,
            "tad-model-weights-v0.4.1",
            "Not executed; target environment unavailable.",
            failure_reason="Simulated target not provisioned in week 3.",
            reviewer_notes="Overhead claim deferred.",
            evidence_ids=["EVID-SEU-006"],
        ),
    },
]

EVIDENCE: list[dict] = [
    E(
        "EVID-SEU-001",
        "Campaign export schema",
        "CONFIGURATION",
        "Fault campaign export schema and example.",
        ["REQ-M-001"],
        ["TEST-SEU-009"],
    ),
    E(
        "EVID-SEU-002",
        "SDC sweep raw results",
        "FAULT_INJECTION_RESULT",
        "Full silent-data-corruption sweep results.",
        ["REQ-S-001", "REQ-R-001"],
        ["TEST-SEU-008"],
        attachment="seu-sdc-sweep.txt",
    ),
    E(
        "EVID-SEU-003",
        "Checksum verification log",
        "FAULT_INJECTION_RESULT",
        "Checksum detection log (40/40).",
        ["REQ-R-001"],
        ["TEST-SEU-006"],
        attachment="seu-checksum.log",
    ),
    E(
        "EVID-SEU-004",
        "Voting experiment log",
        "FAULT_INJECTION_RESULT",
        "Triple-module voting results.",
        ["REQ-R-002"],
        ["TEST-SEU-007"],
    ),
    E(
        "EVID-SEU-005",
        "Catastrophic output analysis",
        "PLOT",
        "Degradation histogram incl. catastrophic tail.",
        ["REQ-S-001"],
        ["TEST-SEU-008"],
    ),
    E(
        "EVID-SEU-006",
        "Target availability note",
        "REVIEW_RECORD",
        "Note that simulated target was unavailable.",
        ["REQ-NF-001"],
        ["TEST-SEU-011"],
    ),
    E(
        "EVID-SEU-007",
        "Seed reproducibility record",
        "REVIEW_RECORD",
        "Same-seed determinism check.",
        ["REQ-F-001"],
        ["TEST-SEU-010"],
    ),
    E(
        "EVID-SEU-008",
        "INT8 campaign summary",
        "FAULT_INJECTION_RESULT",
        "INT8 weight campaign summary.",
        ["REQ-F-003"],
        ["TEST-SEU-005"],
    ),
]

RISKS: list[dict] = [
    RISK(
        "RISK-SEU-001",
        "Silent data corruption",
        "Corrupted model state produces plausible wrong output",
        "Bit flip in activations/buffers",
        "Wrong detection output without any alarm",
        5,
        4,
        "Weight checksums + voting + output sanity cage (planned)",
        "TEST-SEU-008 currently FAIL (SDC 4.2%)",
        5,
        3,
        "NOT_ACCEPTABLE",
        "Unmitigated deployment not acceptable; mitigation (sanity cage) not yet implemented.",
        ["REQ-S-001", "REQ-R-001"],
        ["TEST-SEU-008"],
        ["FM-SEU-001"],
    ),
    RISK(
        "RISK-SEU-002",
        "Fault campaign non-reproducibility",
        "Campaign results cannot be trusted",
        "Environment drift or non-determinism",
        "Wrong vulnerability ranking",
        2,
        2,
        "Fixed seeds + pinned harness",
        "TEST-SEU-010",
        1,
        1,
        "ACCEPTABLE",
        "Determinism verified; residual negligible for demo.",
        ["REQ-F-001"],
        ["TEST-SEU-010"],
        ["FM-SEU-003"],
    ),
    RISK(
        "RISK-SEU-003",
        "Simulation/radiation gap",
        "Software injection does not match real radiation behaviour",
        "Different upset physics",
        "Over-estimated resilience",
        4,
        3,
        "Document limitation; hardware test campaign required",
        "Known-limitation record",
        4,
        3,
        "REVIEW_REQUIRED",
        "Accepted only for demonstration; real deployment requires radiation testing.",
        ["REQ-R-001"],
        [],
        ["FM-SEU-005"],
    ),
]

FMEA: list[dict] = [
    FM(
        "FM-SEU-001",
        "Detect corruption before output",
        "Silent data corruption undetected",
        "Wrong logits",
        "Wrong anomaly decision",
        "Activation/buffer bit flip",
        "Checksum (weights only)",
        "Checksums on weights",
        5,
        4,
        3,
        "Add output sanity cage + activation checksums",
        "Sanity cage (planned)",
        "C",
        ["REQ-S-001", "REQ-R-001"],
        ["TEST-SEU-008"],
        ["EVID-SEU-002"],
    ),
    FM(
        "FM-SEU-002",
        "Mask single faults",
        "Voting consensus break",
        "Two replicas corrupted identically",
        "Unmasked error",
        "Correlated sign-bit flips",
        "Voting disagreement monitor",
        "TMR voting",
        4,
        2,
        2,
        "Diverse redundancy",
        "Watchdog on disagreement",
        "M",
        ["REQ-R-002"],
        ["TEST-SEU-007"],
        ["EVID-SEU-004"],
    ),
    FM(
        "FM-SEU-003",
        "Run fault campaign",
        "Fault injection not applied",
        "Campaign incomplete",
        "Coverage overestimated",
        "Harness error",
        "Campaign manifest check",
        "Deterministic harness",
        3,
        2,
        2,
        "Validate campaigns",
        "Manifest + seed checks",
        "L",
        ["REQ-F-001"],
        ["TEST-SEU-010"],
        [],
    ),
    FM(
        "FM-SEU-004",
        "Protect model memory",
        "Ineffective mitigation",
        "Corruption slips past checksum",
        "Wrong output with false confidence",
        "Checksum gaps",
        "Coverage audit",
        "Weight checksums",
        4,
        2,
        2,
        "Extend coverage",
        "Activation/buffer checksums",
        "M",
        ["REQ-R-001"],
        ["TEST-SEU-008"],
        [],
    ),
    FM(
        "FM-SEU-005",
        "Assess resilience",
        "Injection differs from radiation",
        "Resilience overestimated",
        "Under-protected system",
        "Physics mismatch",
        "Radiation test planning",
        "Documented limitation",
        4,
        3,
        3,
        "Radiation campaign",
        "Independent V&V",
        "M",
        ["REQ-R-001"],
        [],
        [],
    ),
]

LIMITATIONS: list[dict] = [
    LIM(
        "LIM-SEU-001",
        "No output sanity cage",
        "SDC rate 4.2%; catastrophic outputs in 1.1%.",
        "model",
        "Unsafe outputs reach decision path",
        "Output sanity cage (ACT-SEU-01)",
        "Mitigation required before deployment",
        "HIGH",
        "OPEN",
        ["REQ-S-001"],
        ["RISK-SEU-001"],
    ),
    LIM(
        "LIM-SEU-002",
        "Checksum coverage limited to weights",
        "Activations/buffers unprotected.",
        "system",
        "Corruption undetected",
        "Extend checksums + voting",
        "Coverage gap",
        "HIGH",
        "OPEN",
        ["REQ-R-001"],
        ["RISK-SEU-001"],
    ),
    LIM(
        "LIM-SEU-003",
        "Software injection only",
        "No radiation testing performed.",
        "environment",
        "Real upset behaviour unknown",
        "Radiation test campaign",
        "Demonstration scope only",
        "MEDIUM",
        "ACCEPTED",
        [],
        ["RISK-SEU-003"],
    ),
]

DEPLOYMENT = DEC(
    "DEC-SEU-001",
    "NO_GO",
    "No go for deployment without mitigations.",
    "Silent data corruption (SDC 4.2%) with catastrophic outputs (1.1%) is NOT_ACCEPTABLE. Checksum covers only "
    "weights; no output sanity cage exists. Deployment is possible only under CONDITIONAL_GO after implementing "
    "and verifying mitigations.",
    blocking=["TEST-SEU-008"],
    accepted=[],
    mitigations=[
        "Implement output sanity cage (ACT-SEU-01)",
        "Extend checksums to activations/buffers",
        "Re-run TEST-SEU-008 and TEST-SEU-006",
    ],
    constraints=["No unmitigated deployment"],
    monitoring=["checksum_failures", "voting_disagreement", "corruption_events", "recovery_rate"],
    rollback="Recompute model state from golden copy and re-verify checksums.",
)

MONITORING = {
    "status": "PARTIAL",
    "objectives": ["Detect any corruption event at runtime", "Track mitigation effectiveness"],
    "metrics": [
        {"name": "checksum_failures", "description": "Checksum mismatch count", "threshold": "alert > 0"},
        {"name": "voting_disagreement", "description": "Voting disagreement count", "threshold": "alert > 0"},
        {"name": "corruption_events", "description": "Corruption events detected", "threshold": "alert on any"},
        {"name": "recovery_rate", "description": "Successful recovery ratio", "threshold": "alert < 0.95"},
    ],
    "alert_thresholds": {"checksum_failures": 0, "recovery_rate": 0.95},
    "sampling_frequency": "per inference + periodic checksum sweep",
    "retention": "all events retained",
    "telemetry_budget": "within budget",
    "escalation": "Watchdog -> FDIR -> ground",
    "safe_state": "Golden model reload + verification before resume",
    "rollback_trigger": "Any undetected-corruption candidate",
    "retraining_trigger": "Not applicable (weight protection focus)",
    "investigation_workflow": "Corrupt event -> locate -> checksum coverage fix",
    "ownership": "Reliability demo team",
    "review_frequency": "per campaign",
}

ODD = {
    "status": "PARTIAL",
    "operational_objective": "Run onboard inference protected against single-event upsets.",
    "environment": "Simulated radiated environment; software fault injection only.",
    "input_ranges": [
        {"dimension": "fault_count", "range": "1-3 flips per run (campaign)", "coverage": "VERIFIED"},
        {"dimension": "bit_positions", "range": "all 8-bit positions incl. sign", "coverage": "VERIFIED"},
        {"dimension": "weight_quantization", "range": "FP32 and INT8", "coverage": "VERIFIED"},
        {"dimension": "activation_buffers", "range": "not yet covered", "coverage": "NOT_VERIFIED"},
    ],
    "supported_modes": ["Weight checksum active", "TMR voting active"],
    "unsupported_modes": [
        "Runtime radiation environment (not tested)",
        "Corruption of activations/buffers (undetected)",
    ],
    "nominal_region": "No faults; checksums verified periodically.",
    "degraded_region": "Single faults masked by voting or detected by checksum.",
    "prohibited_region": "Operation without mitigation after known SDC.",
    "transition_conditions": "Fault detected -> golden reload -> re-verify.",
    "ood_detection_strategy": "Not applicable (fault domain; detection via checksum/voting).",
    "fallback": "Golden model reload and verification.",
    "assumptions": ["Single-event upsets modelled as bit flips", "No multi-cell upsets considered"],
    "boundaries_evidence": [{"dimension": "activation_buffers", "evidence": "EVID-SEU-002"}],
}

MODEL_CARD = {
    "model_name": "Telemetry anomaly model under injection (subject of the SEU study)",
    "model_type": "GRU autoencoder (same as PRJ-TAD-001 model)",
    "task": "Telemetry anomaly detection (protected variant)",
    "intended_use": "Subject for SEU resilience assessment; not a deployment artefact of the injector.",
    "users": ["Reliability demo team"],
    "prohibited_uses": ["Treating the fault injector as an ML model", "Unmitigated deployment (NO_GO)"],
    "input": "8-channel telemetry window",
    "output": "anomaly score",
    "training_data_summary": "As per PRJ-TAD-001 model card (synthetic telemetry).",
    "validation_data_summary": "15% reserved.",
    "test_data_summary": "Fault-injection campaigns over weights (FP32/INT8).",
    "preprocessing": "Same as base model.",
    "metrics": {"sdc_rate": 0.042, "catastrophic_output_rate": 0.011, "checksum_detection_rate": 1.0},
    "metric_thresholds": {"sdc_rate_max": 0.0, "checksum_detection_min": 1.0},
    "known_failure_modes": ["Activation/buffer corruption undetected", "Sign-bit flips severe"],
    "robustness": "See SEU campaign tests.",
    "ood_behavior": "Not the focus of the injection study.",
    "uncertainty_handling": "Not applicable.",
    "quantization": {"int8_supported": True, "campaign_executed": True},
    "hardware_target": "Simulated OBC (protection study)",
    "inference_constraints": "Overhead to be measured (RUN-SEU-011 NOT_EXECUTED)",
    "limitations": ["Software injection only", "No radiation data"],
    "maintenance_owner": "Reliability demo team",
    "version_history": [{"version": "0.4.1", "change": "subject model"}],
}

DATA_QUALITY = {
    "dataset_name": "Fault campaign inputs (model weights + telemetry windows)",
    "dataset_version": "campaign-v0.4.1",
    "source": "Synthetic telemetry + exported model weights (declared synthetic)",
    "synthetic": True,
    "description": "Campaign inputs are bit-flip specifications over weight tensors and telemetry windows; not a "
    "conventional ML dataset.",
    "row_counts": {"fault_injections": 620, "telemetry_windows": 3000},
    "columns": 8,
    "missing": "None",
    "duplicates": "None (campaign manifest unique)",
    "outliers": "n/a",
    "class_balance": "n/a (fault study)",
    "time_coverage": "n/a",
    "representativeness": "Bit-flip model approximates SEU for weights only",
    "split_strategy": "n/a (campaign manifest)",
    "leakage_indicators": "None",
    "quality_findings": ["Activation/buffer corruption not modelled", "Radiation effects simplified to bit flips"],
    "severity": "MEDIUM",
    "data_readiness_score": None,
    "score_coverage": 0.0,
    "review_status": "Not Applicable (campaign artefacts)",
    "limitations": ["Fault campaign input treated as verification artefacts per week-3 rules"],
}

PROJECT: dict = {
    "meta": {
        "id": "PRJ-SEU-001",
        "slug": "seu-fault-injector",
        "name": "SEU Fault Injector",
        "short_description": "Deterministic bit-flip fault injector to assess resilience of an onboard ML model against single-event upsets.",
        "domain": "embedded-verification",
        "use_case": "Resilience and fault-injection assessment",
        "operational_context": "Software fault injection on model weights (simulated)",
        "criticality": "High",
        "deployment_target": "Verification lab / simulated target",
        "execution_environment": "Python harness + simulated target",
        "lifecycle_status": "UNDER_VERIFICATION",
        "assurance_status": "REVIEW_REQUIRED",
        "owner": "Reliability demo team",
        "version": "1.0.0",
        "model_version": MODEL,
        "dataset_version": "campaign-v0.4.1",
        "tags": ["fault-injection", "seu", "resilience", "synthetic"],
    },
    "requirements": REQS,
    "tests": TESTS,
    "evidence": EVIDENCE,
    "risks": RISKS,
    "fmea": FMEA,
    "limitations": LIMITATIONS,
    "deployment_decisions": [DEPLOYMENT],
    "monitoring": MONITORING,
    "odd": ODD,
    "model_card": MODEL_CARD,
    "data_quality": DATA_QUALITY,
}
