"""Telemetry Anomaly Detector — synthetic demonstration content (week 3)."""

from app.portfolio.datadefs.builders import DEC, FM, LIM, RISK, TC, TR, E, R

MODEL = "anomaly-detector-gru-v2"
REQS: list[dict] = [
    R(
        "REQ-F-001",
        "Detect telemetry anomalies",
        "FUNCTIONAL",
        "The ML constituent shall detect anomalies in spacecraft telemetry streams and emit an anomaly flag per sample window.",
        "TEST",
        "Detection demonstrated on nominal and injected-anomaly telemetry.",
        "HIGH",
        "VERIFIED",
        rationale="Supports onboard Fault Detection, Isolation and Recovery (FDIR) triage.",
    ),
    R(
        "REQ-F-002",
        "Classify anomaly type",
        "FUNCTIONAL",
        "Detected anomalies shall be tagged with a coarse category (sensor fault, drift, burst, unknown).",
        "TEST",
        "Category tags assigned on labelled demonstration set.",
        "MEDIUM",
        "APPROVED",
    ),
    R(
        "REQ-P-001",
        "False positive rate bound",
        "PERFORMANCE",
        "False positive rate on nominal telemetry shall not exceed 1.0% per day of simulated operations.",
        "TEST",
        "FPR <= 1.0% measured on the nominal dataset.",
        "HIGH",
        "VERIFIED",
    ),
    R(
        "REQ-P-002",
        "Missed anomaly bound",
        "PERFORMANCE",
        "True anomaly detection recall shall be at least 0.95 for anomalies inside the ODD.",
        "TEST",
        "Recall >= 0.95 on known-anomaly subset.",
        "HIGH",
        "NOT_VERIFIED",
        rationale="Drift and unseen-anomaly subsets currently violate this bound.",
    ),
    R(
        "REQ-P-003",
        "Inference latency",
        "PERFORMANCE",
        "Inference latency per telemetry window shall be below 50 ms on the target platform.",
        "TEST",
        "p95 latency < 50 ms on target; measured on simulated target in week 3.",
        "MEDIUM",
        "NOT_VERIFIED",
    ),
    R(
        "REQ-D-001",
        "Telemetry data quality gate",
        "DATA",
        "Training/verification datasets shall pass the Workbench Data Readiness gate (score coverage >= 70%).",
        "ANALYSIS",
        "Data Readiness report attached with decision Ready/Conditionally Ready.",
        "HIGH",
        "VERIFIED",
    ),
    R(
        "REQ-D-002",
        "Missing value handling",
        "DATA",
        "The pipeline shall tolerate up to 10% missing samples per window with explicit handling.",
        "TEST",
        "No crash and bounded degradation on missing-data subset.",
        "MEDIUM",
        "VERIFIED",
    ),
    R(
        "REQ-R-001",
        "Robustness to drift",
        "ROBUSTNESS",
        "The system shall flag gradual input drift and keep FPR within 2x nominal for moderate drift.",
        "TEST",
        "Drift indicator active; FPR within 2x nominal for moderate drift.",
        "HIGH",
        "FAILED",
    ),
    R(
        "REQ-R-002",
        "OOD handling",
        "ROBUSTNESS",
        "Out-of-distribution telemetry shall be detected or conservatively flagged, never silently scored.",
        "TEST",
        "OOD detector raises flag on OOD subset.",
        "HIGH",
        "APPROVED",
    ),
    R(
        "REQ-M-001",
        "Logging and monitoring hooks",
        "MONITORING",
        "The constituent shall expose logging of flags, scores, latency and drift indicators.",
        "REVIEW",
        "Interface inspection; sample logs present.",
        "MEDIUM",
        "VERIFIED",
    ),
    R(
        "REQ-S-001",
        "Fallback for degraded mode",
        "SAFETY",
        "When confidence is low or OOD is raised, the system shall fall back to deterministic threshold logic or request ground analysis.",
        "TEST",
        "Fallback activation demonstrated in simulation.",
        "HIGH",
        "VERIFIED",
    ),
    R(
        "REQ-E-001",
        "Embedded resource envelope",
        "EMBEDDED_RESOURCE",
        "Prototype shall fit the simulated OBC memory budget (RAM < 64 MB, model < 8 MB).",
        "ANALYSIS",
        "Profiling report attached (simulated target).",
        "MEDIUM",
        "VERIFIED",
    ),
]

TESTS: list[dict] = [
    {
        **TC(
            "TEST-TAD-001",
            "Nominal telemetry behaviour",
            "DATASET",
            "No false alarms on clean telemetry.",
            "FPR <= 1.0%",
            ["REQ-P-001", "REQ-F-001"],
            "MEDIUM",
        ),
        **TR(
            "TEST-TAD-001",
            "PASS",
            "RUN-TAD-001",
            "sim-env v1",
            MODEL,
            "tad-ds-nominal-v2.1",
            "FPR 0.4% on 3000 nominal windows.",
            {"false_positive_rate": 0.004, "windows": 3000},
            evidence_ids=["EVID-TAD-001"],
        ),
    },
    {
        **TC(
            "TEST-TAD-002",
            "Known anomaly detection",
            "DATASET",
            "Detect injected known anomalies.",
            "recall >= 0.95",
            ["REQ-P-002", "REQ-F-001"],
            "HIGH",
        ),
        **TR(
            "TEST-TAD-002",
            "PASS",
            "RUN-TAD-002",
            "sim-env v1",
            MODEL,
            "tad-ds-known-v2.1",
            "Recall 0.97 on known anomaly set.",
            {"recall": 0.97, "samples": 1200},
            evidence_ids=["EVID-TAD-001"],
        ),
    },
    {
        **TC(
            "TEST-TAD-003",
            "Unseen anomaly type",
            "SCENARIO",
            "Anomaly patterns absent from training set.",
            "recall >= 0.95 within ODD",
            ["REQ-P-002", "REQ-R-002"],
            "HIGH",
        ),
        **TR(
            "TEST-TAD-003",
            "FAIL",
            "RUN-TAD-003",
            "sim-env v1",
            MODEL,
            "tad-ds-unseen-v2.1",
            "Recall 0.61 on unseen patterns.",
            {"recall": 0.61, "samples": 500},
            failure_reason="Unseen pattern family not represented in training; OOD flag fired late.",
            reviewer_notes="Confirmed by second run with same seed.",
            evidence_ids=["EVID-TAD-003", "EVID-TAD-008"],
        ),
    },
    {
        **TC(
            "TEST-TAD-004",
            "Gradual drift detection",
            "SCENARIO",
            "Slow sensor drift over time.",
            "drift flagged; FPR <= 2x nominal",
            ["REQ-R-001", "REQ-M-001"],
            "HIGH",
        ),
        **TR(
            "TEST-TAD-004",
            "FAIL",
            "RUN-TAD-004",
            "sim-env v1",
            MODEL,
            "tad-ds-drift-v2.1",
            "Drift flagged after 38% of the run; FPR reached 3.1x nominal.",
            {"drift_latency_windows": 460, "fpr_multiplier": 3.1},
            failure_reason="Drift indicator threshold too insensitive for slow ramps.",
            reviewer_notes="Action ACT-TAD-01: retune drift threshold.",
            evidence_ids=["EVID-TAD-004"],
        ),
    },
    {
        **TC(
            "TEST-TAD-005",
            "Missing sensor stream",
            "ROBUSTNESS",
            "Entire sensor channel missing.",
            "graceful degradation; explicit missing flag",
            ["REQ-D-002", "REQ-S-001"],
            "HIGH",
        ),
        **TR(
            "TEST-TAD-005",
            "PASS",
            "RUN-TAD-005",
            "sim-env v1",
            MODEL,
            "tad-ds-missing-v2.1",
            "Missing-channel flag raised; recall on remaining channels 0.93.",
            {"recall": 0.93},
            evidence_ids=["EVID-TAD-002"],
        ),
    },
    {
        **TC(
            "TEST-TAD-006",
            "Noise robustness",
            "ROBUSTNESS",
            "Gaussian noise injection on inputs.",
            "recall drop < 5 points",
            ["REQ-P-002"],
            "MEDIUM",
        ),
        **TR(
            "TEST-TAD-006",
            "PASS",
            "RUN-TAD-006",
            "sim-env v1",
            MODEL,
            "tad-ds-noise-v2.1",
            "Recall drop 2 points at expected noise.",
            {"recall_drop": 0.02},
        ),
    },
    {
        **TC(
            "TEST-TAD-007",
            "Anomaly burst",
            "SCENARIO",
            "High-rate anomaly burst.",
            "detect >= 80% of burst events",
            ["REQ-F-001", "REQ-P-002"],
            "MEDIUM",
        ),
        **TR(
            "TEST-TAD-007",
            "PASS",
            "RUN-TAD-007",
            "sim-env v1",
            MODEL,
            "tad-ds-burst-v2.1",
            "Detected 86% of burst events.",
            {"burst_detection_rate": 0.86},
        ),
    },
    {
        **TC(
            "TEST-TAD-008",
            "Inference latency (target)",
            "LATENCY",
            "p95 latency on target-like board.",
            "p95 < 50 ms",
            ["REQ-P-003"],
            "HIGH",
        ),
        **TR(
            "TEST-TAD-008",
            "BLOCKED",
            "RUN-TAD-008",
            "simulated-target (unavailable)",
            MODEL,
            "tad-ds-nominal-v2.1",
            "Not executed: target board unavailable in week 3 environment.",
            failure_reason="Target hardware access not available; host-only estimate 41 ms p95.",
            reviewer_notes="Deployment condition: repeat on target.",
            evidence_ids=["EVID-TAD-005"],
        ),
    },
    {
        **TC(
            "TEST-TAD-009",
            "Logging verification",
            "INTEGRATION",
            "Log records contain flags, scores, latency.",
            "log schema complete",
            ["REQ-M-001"],
            "MEDIUM",
        ),
        **TR(
            "TEST-TAD-009",
            "PASS",
            "RUN-TAD-009",
            "sim-env v1",
            MODEL,
            "tad-ds-nominal-v2.1",
            "Log schema verified on sample run.",
            {},
            evidence_ids=["EVID-TAD-006"],
        ),
    },
    {
        **TC(
            "TEST-TAD-010",
            "Fallback activation",
            "SYSTEM",
            "Fallback deterministic logic on OOD window.",
            "fallback active < 100 ms",
            ["REQ-S-001"],
            "HIGH",
        ),
        **TR(
            "TEST-TAD-010",
            "PASS",
            "RUN-TAD-010",
            "sim-env v1",
            MODEL,
            "tad-ds-ood-v2.1",
            "Fallback activated in 62 ms median; ground-analysis request logged.",
            {"fallback_activation_ms": 62},
            evidence_ids=["EVID-TAD-007"],
        ),
    },
    {
        **TC(
            "TEST-TAD-011",
            "OOD detection rate",
            "ROBUSTNESS",
            "OOD window detection.",
            "detection rate >= 0.90",
            ["REQ-R-002"],
            "HIGH",
        ),
        **TR(
            "TEST-TAD-011",
            "PASS",
            "RUN-TAD-011",
            "sim-env v1",
            MODEL,
            "tad-ds-ood-v2.1",
            "OOD detection rate 0.93.",
            {"ood_detection_rate": 0.93},
            evidence_ids=["EVID-TAD-008"],
        ),
    },
]

EVIDENCE: list[dict] = [
    E(
        "EVID-TAD-001",
        "Known & nominal dataset evaluation",
        "TEST_RESULT",
        "FPR and recall results on nominal and known-anomaly datasets.",
        ["REQ-P-001", "REQ-P-002"],
        ["TEST-TAD-001", "TEST-TAD-002"],
        attachment="tad-eval-nominal-known.txt",
    ),
    E(
        "EVID-TAD-002",
        "Missing sensor handling report",
        "TEST_RESULT",
        "Missing-channel behaviour evidence.",
        ["REQ-D-002"],
        ["TEST-TAD-005"],
        attachment="tad-missing-sensor.txt",
    ),
    E(
        "EVID-TAD-003",
        "Unseen anomaly run log",
        "LOG",
        "Run log of unseen-anomaly evaluation (failure evidence).",
        ["REQ-P-002"],
        ["TEST-TAD-003"],
    ),
    E(
        "EVID-TAD-004",
        "Drift campaign log",
        "LOG",
        "Gradual drift run log; FPR multiplier 3.1x.",
        ["REQ-R-001"],
        ["TEST-TAD-004"],
    ),
    E(
        "EVID-TAD-005",
        "Host latency estimate",
        "BENCHMARK",
        "Host-only latency estimate; target measurement blocked.",
        ["REQ-P-003"],
        ["TEST-TAD-008"],
        status="STALE",
        limitations="Host estimate, not target evidence.",
    ),
    E(
        "EVID-TAD-006",
        "Log schema inspection",
        "REVIEW_RECORD",
        "Inspection of log interface.",
        ["REQ-M-001"],
        ["TEST-TAD-009"],
    ),
    E(
        "EVID-TAD-007",
        "Fallback simulation result",
        "TEST_RESULT",
        "Deterministic fallback activation in simulation.",
        ["REQ-S-001"],
        ["TEST-TAD-010"],
    ),
    E(
        "EVID-TAD-008",
        "OOD subset report",
        "DATA_QUALITY_RESULT",
        "OOD detection results on reserved subset.",
        ["REQ-R-002"],
        ["TEST-TAD-011"],
    ),
    E(
        "EVID-TAD-009",
        "Data readiness review",
        "REVIEW_RECORD",
        "Workbench Data Readiness decision for telemetry datasets.",
        ["REQ-D-001"],
        [],
        attachment="tad-data-readiness.txt",
    ),
]

RISKS: list[dict] = [
    RISK(
        "RISK-TAD-001",
        "Missed rare anomaly (false negative)",
        "A true anomaly is not flagged and propagates to FDIR",
        "Pattern outside training distribution",
        "Delayed FDIR reaction; mission impact unknown",
        5,
        3,
        "OOD flag + fallback to deterministic checks; ground analysis request",
        "EVID-TAD-008; TEST-TAD-011",
        4,
        2,
        "ACCEPTABLE_WITH_LIMITATIONS",
        "Accepted only with mandatory drift monitoring and ground review of missed anomalies.",
        ["REQ-P-002", "REQ-S-001"],
        ["TEST-TAD-003", "TEST-TAD-011"],
        ["FM-TAD-001"],
    ),
    RISK(
        "RISK-TAD-002",
        "Telemetry drift degrades FPR",
        "Gradual drift increases false alarms",
        "Slow sensor ageing/calibration change",
        "Operator alarm fatigue",
        3,
        4,
        "Drift indicator retuned (open action ACT-TAD-01)",
        "TEST-TAD-004 (currently FAIL)",
        3,
        2,
        "REQUIRES_MITIGATION",
        "Mitigation not yet verified; drift test currently fails.",
        ["REQ-R-001"],
        ["TEST-TAD-004"],
        ["FM-TAD-002"],
    ),
    RISK(
        "RISK-TAD-003",
        "Missing sensor channel bias",
        "Channel dropout biases detection",
        "Sensor interface fault",
        "Reduced coverage while channel is lost",
        3,
        3,
        "Explicit missing flags + per-channel confidence",
        "TEST-TAD-005",
        2,
        2,
        "ACCEPTABLE",
        "Within accepted tolerance for demonstration.",
        ["REQ-D-002"],
        ["TEST-TAD-005"],
        ["FM-TAD-003"],
    ),
    RISK(
        "RISK-TAD-004",
        "Target latency not verified",
        "Onboard latency exceeds budget",
        "Target board unavailable during week 3",
        "Anomaly detection too late for FDIR",
        4,
        3,
        "Repeat latency test on target before deployment",
        "RUN-TAD-008 BLOCKED",
        4,
        2,
        "REQUIRES_MITIGATION",
        "Latency verification is a deployment condition; cannot be waived on host estimates.",
        ["REQ-P-003"],
        ["TEST-TAD-008"],
        ["FM-TAD-004"],
    ),
]

FMEA: list[dict] = [
    FM(
        "FM-TAD-001",
        "Detect telemetry anomaly",
        "Missed anomaly",
        "Flag not raised",
        "Anomaly reaches FDIR undetected",
        "OOD pattern, decision threshold",
        "OOD flag + recall monitoring",
        "Threshold tuning; OOD detector",
        5,
        3,
        3,
        "Monitor missed-anomaly review; extend ODD coverage",
        "OOD flag + fallback",
        "M",
        ["REQ-P-002"],
        ["TEST-TAD-003", "TEST-TAD-011"],
        ["EVID-TAD-008"],
    ),
    FM(
        "FM-TAD-002",
        "Raise anomaly flag",
        "Excessive false alarms",
        "Operator alarm fatigue",
        "FDIR overwhelmed",
        "Drift or noise",
        "FPR telemetry",
        "FPR bound REQ-P-001",
        3,
        4,
        2,
        "Retune drift threshold",
        "Drift monitoring",
        "M",
        ["REQ-P-001", "REQ-R-001"],
        ["TEST-TAD-001", "TEST-TAD-004"],
        [],
    ),
    FM(
        "FM-TAD-003",
        "Handle telemetry input",
        "Missing telemetry unhandled",
        "Silent gaps in input",
        "Detection biased during gap",
        "Interface fault",
        "Missing flag per channel",
        "Gap handling policy",
        3,
        3,
        2,
        "Document per-channel policy",
        "Explicit missing flag",
        "L",
        ["REQ-D-002"],
        ["TEST-TAD-005"],
        ["EVID-TAD-002"],
    ),
    FM(
        "FM-TAD-004",
        "Emit anomaly score in time",
        "Latency exceeded",
        "Late flag",
        "FDIR window missed",
        "Target overload",
        "Latency monitoring",
        "Latency budget REQ-P-003",
        4,
        2,
        3,
        "Target latency test",
        "Resource headroom",
        "M",
        ["REQ-P-003"],
        ["TEST-TAD-008"],
        ["EVID-TAD-005"],
    ),
    FM(
        "FM-TAD-005",
        "Flag OOD input",
        "OOD not detected",
        "Silent low-confidence output",
        "Wrong anomaly tag",
        "Novel regime",
        "OOD score",
        "OOD detector",
        4,
        2,
        2,
        "Widen ODD coverage",
        "Fallback on OOD",
        "M",
        ["REQ-R-002"],
        ["TEST-TAD-011"],
        ["EVID-TAD-008"],
    ),
]

LIMITATIONS: list[dict] = [
    LIM(
        "LIM-TAD-001",
        "Unseen anomaly coverage",
        "Anomaly families not in training data underperform (recall 0.61).",
        "model",
        "Silent misses in novel regimes",
        "OOD flag + ground analysis",
        "Monitor drift; review misses",
        "HIGH",
        "OPEN",
        ["REQ-P-002"],
        ["RISK-TAD-001"],
    ),
    LIM(
        "LIM-TAD-002",
        "Drift threshold insensitive",
        "Slow drift detected late (38% of run).",
        "monitoring",
        "FPR growth",
        "Retune threshold (ACT-TAD-01)",
        "Drift within 2x nominal",
        "MEDIUM",
        "OPEN",
        ["REQ-R-001"],
        ["RISK-TAD-002"],
    ),
    LIM(
        "LIM-TAD-003",
        "Target latency unverified",
        "Host-only estimate 41 ms p95.",
        "deployment",
        "Latency budget unknown on target",
        "Repeat on target",
        "p95 < 50 ms on target",
        "HIGH",
        "OPEN",
        ["REQ-P-003"],
        ["RISK-TAD-004"],
    ),
    LIM(
        "LIM-TAD-004",
        "Synthetic demonstration data",
        "Datasets are simulated telemetry, not mission data.",
        "dataset",
        "Generalization to real telemetry unproven",
        "Ground validation campaign",
        "Demo scope only",
        "MEDIUM",
        "ACCEPTED",
        ["REQ-D-001"],
        [],
    ),
]

DEPLOYMENT = DEC(
    "DEC-TAD-001",
    "CONDITIONAL_GO",
    "Conditional go for simulated/ground demonstration only.",
    "Core detection verified (FPR 0.4%, known-anomaly recall 0.97) but unseen-anomaly recall (0.61) and drift "
    "handling are not yet compliant; target latency is blocked. Deployment is limited to ground/demonstration "
    "environments with mandatory drift monitoring and ground-analysis fallback.",
    blocking=["TEST-TAD-003", "TEST-TAD-004"],
    accepted=["RISK-TAD-001"],
    mitigations=["Retune drift indicator (ACT-TAD-01)", "Repeat latency test on target (RUN-TAD-008)"],
    constraints=["Ground/demonstration only", "No autonomous onboard FDIR action"],
    monitoring=["false_alarm_trend", "anomaly_rate_drift", "sensor_distribution_drift", "missed_anomaly_review"],
    rollback="Revert to deterministic threshold logic; disable ML flag path.",
)

MONITORING = {
    "status": "PARTIAL",
    "objectives": ["Detect drift before FPR degradation", "Track missed anomalies for review"],
    "metrics": [
        {
            "name": "false_alarm_trend",
            "description": "Weekly false alarm count",
            "threshold": "alert at 2x weekly baseline",
        },
        {
            "name": "anomaly_rate_drift",
            "description": "Anomaly rate relative to ODD baseline",
            "threshold": "alert if >3 sigma over 7 days",
        },
        {
            "name": "sensor_distribution_drift",
            "description": "Per-sensor distribution distance (PSI)",
            "threshold": "alert if PSI > 0.2",
        },
        {
            "name": "missed_anomaly_review",
            "description": "Ground review queue of missed anomalies",
            "threshold": "weekly review target",
        },
    ],
    "alert_thresholds": {"false_alarm_multiplier": 2.0, "psi_limit": 0.2, "drift_latency_windows": 100},
    "sampling_frequency": "per window (1 Hz)",
    "retention": "90 days of aggregate indicators",
    "telemetry_budget": "< 2% of daily telemetry budget",
    "escalation": "Onboard watchdog -> ground analyst -> FDIR review",
    "safe_state": "Fallback deterministic logic with ground-analysis request",
    "rollback_trigger": "FPR > 3x nominal for 24h or target latency breach",
    "retraining_trigger": "Sustained drift with confirmed misses",
    "investigation_workflow": "Review queue -> root cause -> update threshold/OOD -> retest TEST-TAD-004",
    "ownership": "Demo monitoring team",
    "review_frequency": "weekly",
}

ODD = {
    "status": "PARTIAL",
    "operational_objective": "Monitor satellite telemetry windows onboard and flag anomalies.",
    "environment": "Simulated LEO telemetry; 8 telemetry channels; 1 Hz window cadence.",
    "input_ranges": [
        {"dimension": "bus_voltage", "range": "[24.0, 32.0] V", "coverage": "VERIFIED"},
        {"dimension": "reaction_wheel_speed", "range": "[-3000, 3000] rpm", "coverage": "VERIFIED"},
        {"dimension": "battery_temperature", "range": "[-10, 45] C", "coverage": "VERIFIED"},
        {"dimension": "missing_samples", "range": "<= 10% per window", "coverage": "VERIFIED"},
        {"dimension": "drift_rate", "range": "slow ramps only", "coverage": "NOT_VERIFIED"},
        {"dimension": "anomaly_families", "range": "families present in training", "coverage": "PARTIAL"},
    ],
    "supported_modes": ["Nominal", "Standby", "Safe-hold telemetry"],
    "unsupported_modes": [
        "High-rate burst telemetry",
        "Rare fault signatures outside training",
        "Radiated/hardware environment",
    ],
    "nominal_region": "All inputs within ranges above; drift below threshold.",
    "degraded_region": "One channel missing; moderate drift (FPR up to 2x nominal).",
    "prohibited_region": "Autonomous FDIR action from ML flag (not allowed); onboard decision authority.",
    "transition_conditions": "OOD flag or confidence < 0.5 triggers fallback; re-entry when inputs in range.",
    "ood_detection_strategy": "OOD score on window + per-channel reconstruction error.",
    "fallback": "Deterministic threshold checks; ground-analysis request.",
    "assumptions": ["Telemetry format per FDIR interface v2", "Channels calibrated as per dataset v2.1"],
    "boundaries_evidence": [{"dimension": "missing_samples", "evidence": "EVID-TAD-002"}],
}

MODEL_CARD = {
    "model_name": "Anomaly Detector GRU",
    "model_type": "recurrent autoencoder + OOD score",
    "task": "Telemetry anomaly detection (window flags)",
    "intended_use": "Flag anomalies in simulated satellite telemetry for FDIR triage.",
    "users": ["FDIR engineers (demonstration)", "Ground analysts"],
    "prohibited_uses": ["Autonomous onboard FDIR action", "Mission-critical decisions without ground review"],
    "input": "8-channel telemetry window, 60 samples",
    "output": "anomaly score, flag, coarse category",
    "training_data_summary": "Synthetic nominal + injected anomalies (v2.1); see data quality report.",
    "validation_data_summary": "Reserved 15% of synthetic sets.",
    "test_data_summary": "nominal/known/unseen/missing/drift/noise/burst subsets (v2.1).",
    "preprocessing": "z-normalisation per channel fitted on train split only.",
    "metrics": {"f1": 0.91, "precision": 0.89, "recall": 0.93, "fpr": 0.004, "fnr": 0.07},
    "metric_thresholds": {"fpr_max": 0.01, "recall_min_odd": 0.95},
    "known_failure_modes": ["Unseen anomaly families", "Slow drift (FPR growth)", "Missing channels (biased scores)"],
    "robustness": "See tests TEST-TAD-005/006/011.",
    "ood_behavior": "OOD flag + fallback; never silent scoring (REQ-R-002).",
    "uncertainty_handling": "Confidence from reconstruction error; low confidence -> fallback.",
    "quantization": "Not quantized in this version (future INT8 study).",
    "hardware_target": "Simulated OBC (memory envelope 64 MB).",
    "inference_constraints": "p95 < 50 ms target (unverified, RUN-TAD-008 BLOCKED).",
    "limitations": ["Synthetic data only", "Target latency unverified"],
    "maintenance_owner": "Demo model team",
    "version_history": [{"version": "0.4.1", "change": "current"}],
}

DATA_QUALITY = {
    "dataset_name": "TAD synthetic telemetry suite",
    "dataset_version": "v2.1.0",
    "source": "Workbench sample-data generators (synthetic, fixed seed)",
    "synthetic": True,
    "description": "Nominal (3000 windows), degraded, known/unseen anomaly subsets; simulated telemetry, not mission data.",
    "row_counts": {"nominal": 3000, "known_anomaly": 1200, "unseen": 500},
    "columns": 8,
    "missing": "<= 10% per window on degraded subset (by design)",
    "duplicates": "None on nominal subset",
    "outliers": "Present on degraded subset as injected anomalies",
    "class_balance": "Imbalanced by design (anomaly ~2.5%); stratified splits used",
    "time_coverage": "Simulated continuous 10 s cadence",
    "representativeness": "Covers ODD nominal/degraded; drift subset partial (see ODD)",
    "split_strategy": "train/val/test 70/15/15, stratified; no temporal leakage (sorted windows)",
    "leakage_indicators": "None identified",
    "quality_findings": ["Drift subset coverage partial", "Unseen families underrepresented"],
    "severity": "MEDIUM",
    "data_readiness_score": 94.0,
    "score_coverage": 100.0,
    "review_status": "Conditionally Ready",
    "limitations": ["Synthetic only", "No real mission telemetry"],
}

PROJECT: dict = {
    "meta": {
        "id": "PRJ-TAD-001",
        "slug": "telemetry-anomaly-detector",
        "name": "Telemetry Anomaly Detector",
        "short_description": "ML-based detection of anomalies in satellite telemetry to support FDIR triage.",
        "domain": "onboard-telemetry-monitoring",
        "use_case": "Fault detection, isolation and recovery support",
        "operational_context": "Onboard telemetry windows (simulated LEO)",
        "criticality": "High",
        "deployment_target": "Simulated LEO OBC (demonstration)",
        "execution_environment": "Python prototype on simulated target",
        "lifecycle_status": "UNDER_VERIFICATION",
        "assurance_status": "SUPPORTED_WITH_LIMITATIONS",
        "owner": "Demo FDIR team",
        "version": "1.2.0",
        "model_version": MODEL,
        "dataset_version": "v2.1.0",
        "tags": ["telemetry", "anomaly-detection", "onboard", "synthetic"],
    },
    "requirements": REQS,
    "tests": TESTS,
    "evidence": EVIDENCE,
    "risks": RISKS,
    "fmea": FMEA,
    "limitations": LIMITATIONS,
    "deployment_decisions": [DEPLOYMENT],
    "monitoring": MONITORING,
    "odd": ODD,
    "model_card": MODEL_CARD,
    "data_quality": DATA_QUALITY,
}
