// AUTO-GENERATED by tools/train_model.py (numpy, fixed seed 20260101). Do not edit.
// Tiny anomaly model: 3 features -> hidden 8 (ReLU) -> 1 logistic output.
#ifndef RTEAI_GEN_MODEL_H
#define RTEAI_GEN_MODEL_H
#include <cstddef>
namespace rteai::gen {
constexpr std::size_t kInputDim = 3;
constexpr std::size_t kHiddenDim = 8;
constexpr float kModelVersion = 1.2f;
constexpr float kInputScale[3] = {1.0f, 0.05f, 1e-3f};
constexpr float kWeights1[24] = { 0.473360830f, 0.353601808f, 0.093152960f, -0.115770052f, -0.085249923f, -0.836753224f, 0.075229100f, -0.167543437f, 0.119971063f, 0.135177523f, 0.455910548f, -0.129965816f, 0.118255185f, 0.561123822f, -0.200103217f, 0.017218680f, 0.024132876f, -0.452078504f, 0.132061674f, -0.403684399f, 0.483974956f, -0.451852363f, 0.090487555f, -0.031876247f };
constexpr float kBias1[8] = { 0.043655595f, 0.055189691f, -0.102487966f, 0.048555687f, -0.070149592f, 0.076714772f, -0.137379391f, -0.086669712f };
constexpr float kWeights2[8] = { -0.051805485f, 0.672988197f, -0.287115707f, -0.124485804f, 1.266605017f, 0.655194834f, -0.016202577f, -0.521939064f };
constexpr float kBias2 = 0.0f;
constexpr double kGolden[5] = { 0.718633781, 0.705798615, 0.671757778, 0.709075958, 0.682764849 };
}
#endif
