/* ===================================================
   🗣️ QUOTESMITH — Database citazioni
   Formato per voce:
     ["testo", "autore", "categoria", "lingua", "difficolta"]
   Lingue: it | en   Categorie: film, serie, cartoni,
   canzoni, libri, storia, videogiochi, proverbi
   Difficolta: easy | medium | hard
   =================================================== */
(function (root, factory) {
  'use strict';
  if (typeof module === 'object' && module.exports) {
    module.exports = factory();
  } else {
    root.QUOTESMITH_DB = factory();
  }
})(typeof self !== 'undefined' ? self : this, function () {
  'use strict';

  var QUOTES = [];

  /* ============================== FILM / MOVIES ============================== */

  // --- Film · Italiano ---
  QUOTES.push(
    ["Tornerò.", "Terminator", "film", "it", "easy"],
    ["Hasta la vista, baby.", "Terminator 2", "film", "it", "easy"],
    ["Che la forza sia con te.", "Obi-Wan Kenobi (Star Wars)", "film", "it", "easy"],
    ["No, io sono tuo padre.", "Darth Vader (Star Wars)", "film", "it", "medium"],
    ["Corri, Forrest, corri!", "Forrest Gump", "film", "it", "easy"],
    ["La vita è come una scatola di cioccolatini: non sai mai quello che ti capita.", "Forrest Gump", "film", "it", "easy"],
    ["All'infinito e oltre!", "Buzz Lightyear (Toy Story)", "film", "it", "easy"],
    ["Ti servirà una barca più grande.", "Capitan Brody (Lo squalo)", "film", "it", "medium"],
    ["Ecco a te, ragazzo.", "Rick Blaine (Casablanca)", "film", "it", "hard"],
    ["Sono il re del mondo!", "Jack (Titanic)", "film", "it", "easy"],
    ["Houston, abbiamo un problema.", "Jim Lovell (Apollo 13)", "film", "it", "easy"],
    ["Perché tanto serio?", "Joker (Il cavaliere oscuro)", "film", "it", "medium"],
    ["Vedo gente morta.", "Cole (Il sesto senso)", "film", "it", "medium"],
    ["Nessuno mette Baby in un angolo.", "Johnny (Dirty Dancing)", "film", "it", "medium"],
    ["Tieni i tuoi amici vicini, ma i nemici ancora più vicini.", "Michael Corleone (Il Padrino)", "film", "it", "medium"],
    ["Mi parli con me?", "Travis Bickle (Taxi Driver)", "film", "it", "hard"],
    ["Carpe diem. Cogli l'attimo.", "John Keating (L'attimo fuggente)", "film", "it", "easy"],
    ["Non c'è posto come casa.", "Dorothy (Il mago di Oz)", "film", "it", "easy"],
    ["Saluta il mio piccolo amico!", "Tony Montana (Scarface)", "film", "it", "medium"],
    ["La prima regola del Fight Club è: non si parla del Fight Club.", "Tyler Durden (Fight Club)", "film", "it", "medium"],
    ["Gliene farò un'offerta che non potrà rifiutare.", "Vito Corleone (Il Padrino)", "film", "it", "easy"],
    ["La verità? Non puoi sopportare la verità!", "Colonnello Jessup (Codice d'onore)", "film", "it", "medium"],
    ["Francamente, cara mia, non me ne importa niente.", "Rhett Butler (Via col vento)", "film", "it", "medium"],
    ["E.T. telefono casa.", "E.T.", "film", "it", "easy"],
    ["Mi chiamo Bond. James Bond.", "James Bond", "film", "it", "easy"],
    ["Dopo tutto, domani è un altro giorno.", "Rossella O'Hara (Via col vento)", "film", "it", "medium"],
    ["Cera su, cera giù.", "Mr. Miyagi (Karate Kid)", "film", "it", "hard"],
    ["Mi hai conquistato con un ciao.", "Jerry Maguire", "film", "it", "hard"],
    ["Se lo costruisci, lui verrà.", "Field of Dreams", "film", "it", "hard"],
    ["Io bevo il tuo frappè!", "Daniel Plainview (Il petroliere)", "film", "it", "hard"],
    ["Non siamo più nel Kansas.", "Dorothy (Il mago di Oz)", "film", "it", "medium"],
    ["Apri le porte della stiva, HAL.", "David Bowman (2001: Odissea nello spazio)", "film", "it", "hard"],
    ["Signori, non potete combattere qui! Questa è la sala di guerra.", "Dottor Stranamore", "film", "it", "hard"],
    ["Hai scelto... male.", "Indiana Jones (L'ultima crociata)", "film", "it", "hard"],
    ["Non siete intrattenuti?", "Massimo Decimo Meridio (Il gladiatore)", "film", "it", "medium"],
    ["Il mio nome è Massimo Decimo Meridio.", "Massimo Decimo Meridio (Il gladiatore)", "film", "it", "medium"],
    ["Potranno toglierci la vita, ma non la libertà!", "William Wallace (Braveheart)", "film", "it", "medium"],
    ["Hanno massacrato il mio ragazzo.", "Vito Corleone (Il Padrino)", "film", "it", "hard"],
    ["Lascia la pistola. Prendi i cannoli.", "Clemenza (Il Padrino)", "film", "it", "hard"],
    ["Strade? Dove andiamo non serve la strada.", "Doc (Ritorno al futuro)", "film", "it", "medium"],
    ["Ciao, mi chiamo Inigo Montoya. Tu hai ucciso mio padre. Preparati a morire.", "Inigo Montoya (La principessa sposa)", "film", "it", "medium"],
    ["È una trappola!", "Ammiraglio Ackbar (Il ritorno dello Jedi)", "film", "it", "easy"],
    ["Ho visto cose che voi umani non potreste immaginare.", "Roy Batty (Blade Runner)", "film", "it", "hard"],
    ["La tua mamma era un criceto e tuo padre sapeva di sambuco!", "Cavaliere Nero (Monty Python)", "film", "it", "hard"],
    ["Benvenuto nel deserto del reale.", "Morpheus (Matrix)", "film", "it", "medium"],
    ["Svegliati, Neo...", "Morpheus (Matrix)", "film", "it", "hard"],
    ["Sono un miracolo della tecnologia.", "L'Avvocato del Diavolo", "film", "it", "hard"]
  );

  // --- Film · English ---
  QUOTES.push(
    ["I'll be back.", "Terminator", "film", "en", "easy"],
    ["Hasta la vista, baby.", "Terminator 2", "film", "en", "easy"],
    ["May the Force be with you.", "Obi-Wan Kenobi (Star Wars)", "film", "en", "easy"],
    ["No, I am your father.", "Darth Vader (Star Wars)", "film", "en", "medium"],
    ["To infinity and beyond!", "Buzz Lightyear (Toy Story)", "film", "en", "easy"],
    ["You're gonna need a bigger boat.", "Chief Brody (Jaws)", "film", "en", "medium"],
    ["Here's looking at you, kid.", "Rick Blaine (Casablanca)", "film", "en", "hard"],
    ["I'm the king of the world!", "Jack (Titanic)", "film", "en", "easy"],
    ["Houston, we have a problem.", "Jim Lovell (Apollo 13)", "film", "en", "easy"],
    ["Why so serious?", "Joker (The Dark Knight)", "film", "en", "medium"],
    ["I see dead people.", "Cole (The Sixth Sense)", "film", "en", "medium"],
    ["Nobody puts Baby in a corner.", "Johnny (Dirty Dancing)", "film", "en", "medium"],
    ["Keep your friends close, but your enemies closer.", "Michael Corleone (The Godfather)", "film", "en", "medium"],
    ["You talkin' to me?", "Travis Bickle (Taxi Driver)", "film", "en", "hard"],
    ["Carpe diem. Seize the day.", "John Keating (Dead Poets Society)", "film", "en", "easy"],
    ["There's no place like home.", "Dorothy (The Wizard of Oz)", "film", "en", "easy"],
    ["Say hello to my little friend!", "Tony Montana (Scarface)", "film", "en", "medium"],
    ["The first rule of Fight Club is: you do not talk about Fight Club.", "Tyler Durden (Fight Club)", "film", "en", "medium"],
    ["I'm gonna make him an offer he can't refuse.", "Don Vito Corleone (The Godfather)", "film", "en", "easy"],
    ["You can't handle the truth!", "Colonel Jessup (A Few Good Men)", "film", "en", "medium"],
    ["Frankly, my dear, I don't give a damn.", "Rhett Butler (Gone with the Wind)", "film", "en", "medium"],
    ["E.T. phone home.", "E.T.", "film", "en", "easy"],
    ["Bond. James Bond.", "James Bond", "film", "en", "easy"],
    ["Run, Forrest, run!", "Jenny Curran (Forrest Gump)", "film", "en", "easy"],
    ["Life is like a box of chocolates. You never know what you're gonna get.", "Forrest Gump", "film", "en", "easy"],
    ["Wax on, wax off.", "Mr. Miyagi (The Karate Kid)", "film", "en", "hard"],
    ["You had me at hello.", "Jerry Maguire", "film", "en", "hard"],
    ["If you build it, he will come.", "Ray Kinsella (Field of Dreams)", "film", "en", "hard"],
    ["I drink your milkshake!", "Daniel Plainview (There Will Be Blood)", "film", "en", "hard"],
    ["Toto, I've a feeling we're not in Kansas anymore.", "Dorothy (The Wizard of Oz)", "film", "en", "medium"],
    ["Open the pod bay doors, HAL.", "David Bowman (2001: A Space Odyssey)", "film", "en", "hard"],
    ["Gentlemen, you can't fight in here! This is the War Room.", "Dr. Strangelove", "film", "en", "hard"],
    ["He chose... poorly.", "Knight (Indiana Jones and the Last Crusade)", "film", "en", "hard"],
    ["Are you not entertained?", "Maximus (Gladiator)", "film", "en", "medium"],
    ["My name is Maximus Decimus Meridius.", "Maximus (Gladiator)", "film", "en", "medium"],
    ["They may take our lives, but they'll never take our freedom!", "William Wallace (Braveheart)", "film", "en", "medium"],
    ["Look how they massacred my boy.", "Vito Corleone (The Godfather)", "film", "en", "hard"],
    ["Leave the gun. Take the cannoli.", "Peter Clemenza (The Godfather)", "film", "en", "hard"],
    ["Roads? Where we're going, we don't need roads.", "Doc Brown (Back to the Future)", "film", "en", "medium"],
    ["Hello. My name is Inigo Montoya. You killed my father. Prepare to die.", "Inigo Montoya (The Princess Bride)", "film", "en", "medium"],
    ["It's a trap!", "Admiral Ackbar (Return of the Jedi)", "film", "en", "easy"],
    ["I've seen things you people wouldn't believe.", "Roy Batty (Blade Runner)", "film", "en", "hard"],
    ["Your mother was a hamster and your father smelt of elderberries!", "Black Knight (Monty Python)", "film", "en", "hard"],
    ["Welcome to the desert of the real.", "Morpheus (The Matrix)", "film", "en", "medium"],
    ["I'm going to make him an offer he can't refuse.", "Don Vito Corleone (The Godfather)", "film", "en", "easy"],
    ["As you wish.", "Westley (The Princess Bride)", "film", "en", "hard"],
    ["I have a feeling we're not in Kansas anymore.", "Dorothy (The Wizard of Oz)", "film", "en", "easy"],
    ["Show me the money!", "Rod Tidwell (Jerry Maguire)", "film", "en", "medium"],
    ["I'll have what she's having.", "Customer (When Harry Met Sally)", "film", "en", "hard"],
    ["There's no crying in baseball!", "Jimmy Dugan (A League of Their Own)", "film", "en", "medium"]
  );

  /* ============================== SERIE TV ============================== */

  // --- Serie TV · Italiano ---
  QUOTES.push(
    ["L'inverno sta arrivando.", "Ned Stark (Game of Thrones)", "serie", "it", "easy"],
    ["Io sono colui che bussa.", "Walter White (Breaking Bad)", "serie", "it", "medium"],
    ["Dì il mio nome.", "Walter White (Breaking Bad)", "serie", "it", "medium"],
    ["Come butta?", "Joey Tribbiani (Friends)", "serie", "it", "easy"],
    ["Eravamo in pausa!", "Ross Geller (Friends)", "serie", "it", "easy"],
    ["Pivot! Pivot! Pivot!", "Ross Geller (Friends)", "serie", "it", "easy"],
    ["Non sai niente, Jon Snow.", "Ygritte (Game of Thrones)", "serie", "it", "medium"],
    ["La notte è oscura e piena di terrori.", "Melisandre (Game of Thrones)", "serie", "it", "hard"],
    ["Valar morghulis.", "Daario Naharis (Game of Thrones)", "serie", "it", "medium"],
    ["Bevo e so le cose.", "Tyrion Lannister (Game of Thrones)", "serie", "it", "easy"],
    ["È quello che lei ha detto.", "Michael Scott (The Office)", "serie", "it", "medium"],
    ["Dichiaro bancarotta!", "Michael Scott (The Office)", "serie", "it", "easy"],
    ["Bazinga!", "Sheldon Cooper (The Big Bang Theory)", "serie", "it", "easy"],
    ["Non sono pazzo, mia madre mi ha fatto fare il test.", "Sheldon Cooper (The Big Bang Theory)", "serie", "it", "medium"],
    ["Un Lannister paga sempre i suoi debiti.", "Tyrion Lannister (Game of Thrones)", "serie", "it", "easy"],
    ["Quando giochi al gioco dei troni, o vinci o muori.", "Cersei Lannister (Game of Thrones)", "serie", "it", "medium"],
    ["Hodor.", "Hodor (Game of Thrones)", "serie", "it", "easy"],
    ["Vivi a lungo e prospera.", "Spock (Star Trek)", "serie", "it", "easy"],
    ["La resistenza è inutile.", "Borg (Star Trek)", "serie", "it", "medium"],
    ["Puro ma puro, il caos non è un pozzo. Il caos è una scala.", "Petyr Baelish (Game of Thrones)", "serie", "it", "hard"],
    ["Ti ho fatto un'offerta che non potevi rifiutare.", "Tony Soprano (I Soprano)", "serie", "it", "medium"],
    ["Stai zitto!", "Tony Soprano (I Soprano)", "serie", "it", "easy"],
    ["Mannaggia la miseria.", "Corrado Soprano (I Soprano)", "serie", "it", "hard"],
    ["Mi chiamo Barone, ma non sono barone.", "Il Commissario Montalbano (Il commissario Montalbano)", "serie", "it", "hard"],
    ["Questo lo sò io!", "Catarella (Il commissario Montalbano)", "serie", "it", "hard"],
    ["Cos'è? Il morto?", "Il Commissario Montalbano (Il commissario Montalbano)", "serie", "it", "medium"],
    ["Sette!", "George Costanza (Seinfeld)", "serie", "it", "hard"],
    ["Niente zuppa per te!", "Re dello Zuppa (Seinfeld)", "serie", "it", "medium"],
    ["Yada, yada, yada.", "Elaine Benes (Seinfeld)", "serie", "it", "medium"],
    ["Questi pretzel mi stanno facendo venire sete!", "Cosmo Kramer (Seinfeld)", "serie", "it", "medium"],
    ["Lo giuro sul gatto.", "Mallory (Archer)", "serie", "it", "hard"],
    ["O come lo dici tu: mercenario.", "Sterling Archer (Archer)", "serie", "it", "hard"],
    ["Il piano è semplice.", "Il Professore (La casa di carta)", "serie", "it", "hard"],
    ["Bella ciao, bella ciao, bella ciao ciao ciao.", "La casa di carta", "serie", "it", "medium"],
    ["Mi chiamo Sherlock Holmes. È mio compito sapere ciò che gli altri non sanno.", "Sherlock Holmes (Sherlock)", "serie", "it", "hard"],
    ["Il gioco è iniziato!", "Sherlock Holmes (Sherlock)", "serie", "it", "medium"],
    ["Non si mente mai tanto quanto prima di un'elezione.", "L'ispettore Derrick (Il commissario Ricciardi)", "serie", "it", "hard"],
    ["Questo è il momento in cui ci si conosce.", "Montalbano (Il commissario Montalbano)", "serie", "it", "hard"]
  );

  // --- Serie TV · English ---
  QUOTES.push(
    ["Winter is coming.", "Ned Stark (Game of Thrones)", "serie", "en", "easy"],
    ["I am the one who knocks.", "Walter White (Breaking Bad)", "serie", "en", "medium"],
    ["Say my name.", "Walter White (Breaking Bad)", "serie", "en", "medium"],
    ["How you doin'?", "Joey Tribbiani (Friends)", "serie", "en", "easy"],
    ["We were on a break!", "Ross Geller (Friends)", "serie", "en", "easy"],
    ["Pivot! Pivot! Pivot!", "Ross Geller (Friends)", "serie", "en", "easy"],
    ["You know nothing, Jon Snow.", "Ygritte (Game of Thrones)", "serie", "en", "medium"],
    ["The night is dark and full of terrors.", "Melisandre (Game of Thrones)", "serie", "en", "hard"],
    ["Valar morghulis.", "Daario Naharis (Game of Thrones)", "serie", "en", "medium"],
    ["I drink and I know things.", "Tyrion Lannister (Game of Thrones)", "serie", "en", "easy"],
    ["That's what she said.", "Michael Scott (The Office)", "serie", "en", "medium"],
    ["I declare bankruptcy!", "Michael Scott (The Office)", "serie", "en", "easy"],
    ["Bazinga!", "Sheldon Cooper (The Big Bang Theory)", "serie", "en", "easy"],
    ["I'm not crazy. My mother had me tested.", "Sheldon Cooper (The Big Bang Theory)", "serie", "en", "medium"],
    ["A Lannister always pays his debts.", "Tyrion Lannister (Game of Thrones)", "serie", "en", "easy"],
    ["A lion does not concern himself with the opinion of sheep.", "Tywin Lannister (Game of Thrones)", "serie", "en", "hard"],
    ["Hodor.", "Hodor (Game of Thrones)", "serie", "en", "easy"],
    ["Live long and prosper.", "Spock (Star Trek)", "serie", "en", "easy"],
    ["Resistance is futile.", "Borg (Star Trek)", "serie", "en", "medium"],
    ["Make it so.", "Captain Picard (Star Trek)", "serie", "en", "medium"],
    ["I'm the Doctor.", "The Doctor (Doctor Who)", "serie", "en", "easy"],
    ["Wibbly-wobbly, timey-wimey... stuff.", "Tenth Doctor (Doctor Who)", "serie", "en", "hard"],
    ["Have you tried turning it off and on again?", "Roy (The IT Crowd)", "serie", "en", "medium"],
    ["Chaos isn't a pit. Chaos is a ladder.", "Petyr Baelish (Game of Thrones)", "serie", "en", "hard"],
    ["When you play the game of thrones, you win or you die.", "Cersei Lannister (Game of Thrones)", "serie", "en", "medium"],
    ["I am not in danger, Skyler. I am the danger.", "Walter White (Breaking Bad)", "serie", "en", "medium"],
    ["Mr. Chips, meet Scarface.", "Walter White (Breaking Bad)", "serie", "en", "hard"],
    ["A guy opens his door and gets shot. And you think that of me? No. I am the one who knocks.", "Walter White (Breaking Bad)", "serie", "en", "hard"],
    ["Cool. Cool cool cool.", "Abed Nadir (Community)", "serie", "en", "medium"],
    ["Troy and Abed in the morning!", "Troy Barnes (Community)", "serie", "en", "hard"],
    ["Six seasons and a movie!", "Abed Nadir (Community)", "serie", "en", "hard"],
    ["I've made a huge mistake.", "Gob Bluth (Arrested Development)", "serie", "en", "hard"],
    ["There's always money in the banana stand.", "George Bluth (Arrested Development)", "serie", "en", "hard"],
    ["No touching!", "Tobias Fünke (Arrested Development)", "serie", "en", "hard"],
    ["Annyong.", "Annyong (Arrested Development)", "serie", "en", "hard"],
    ["No soup for you!", "The Soup Nazi (Seinfeld)", "serie", "en", "medium"],
    ["Yada, yada, yada.", "Elaine Benes (Seinfeld)", "serie", "en", "medium"],
    ["These pretzels are making me thirsty!", "Cosmo Kramer (Seinfeld)", "serie", "en", "medium"],
    ["The sea was angry that day, my friends.", "George Costanza (Seinfeld)", "serie", "en", "hard"],
    ["Seven!", "George Costanza (Seinfeld)", "serie", "en", "hard"],
    ["Dammit, Jim, I'm a doctor, not a physicist!", "Bones McCoy (Star Trek)", "serie", "en", "medium"],
    ["There's always time for another question.", "Alex Trebek (Jeopardy!)", "serie", "en", "hard"],
    ["I didn't do it.", "Bart Simpson (The Simpsons)", "serie", "en", "easy"],
    ["Danger zone!", "Sterling Archer (Archer)", "serie", "en", "hard"],
    ["The plan is simple.", "The Professor (Money Heist)", "serie", "en", "hard"],
    ["Bella ciao, bella ciao, bella ciao ciao ciao.", "Money Heist", "serie", "en", "medium"],
    ["My name is Sherlock Holmes. It is my business to know what other people don't know.", "Sherlock Holmes (Sherlock)", "serie", "en", "hard"],
    ["The game is on!", "Sherlock Holmes (Sherlock)", "serie", "en", "medium"],
    ["You underestimate the power of denial.", "Eric Cartman (South Park)", "serie", "en", "hard"]
  );

  /* ============================== CARTONI / ANIMATED ============================== */

  // --- Cartoni · Italiano ---
  QUOTES.push(
    ["Buone notizie, amici!", "Professor Farnsworth (Futurama)", "cartoni", "it", "easy"],
    ["Mordimi il lucido sedere di metallo!", "Bender (Futurama)", "cartoni", "it", "easy"],
    ["Zitto e prendi i miei soldi!", "Fry (Futurama)", "cartoni", "it", "easy"],
    ["Un'arte, per favore!", "Bender (Futurama)", "cartoni", "it", "medium"],
    ["Perché non Zoidberg?", "Dottor Zoidberg (Futurama)", "cartoni", "it", "easy"],
    ["Hai tecnicamente ragione, il che è il miglior tipo di ragione.", "Futurama", "cartoni", "it", "medium"],
    ["Lo spirito è pronto, ma la carne è spugnosa e ammaccata.", "Zapp Brannigan (Futurama)", "cartoni", "it", "hard"],
    ["Sono l'uomo senza nome, Zapp Brannigan al tuo servizio.", "Zapp Brannigan (Futurama)", "cartoni", "it", "hard"],
    ["Ah!", "Homer Simpson (I Simpson)", "cartoni", "it", "easy"],
    ["Ay, caramba!", "Bart Simpson (I Simpson)", "cartoni", "it", "easy"],
    ["Fatti una ragione, non farti una mucca!", "Bart Simpson (I Simpson)", "cartoni", "it", "easy"],
    ["Eccellente!", "Signor Burns (I Simpson)", "cartoni", "it", "easy"],
    ["Sfoderate i cani!", "Signor Burns (I Simpson)", "cartoni", "it", "medium"],
    ["Woo-hoo!", "Homer Simpson (I Simpson)", "cartoni", "it", "easy"],
    ["Piano dentistico!", "Homer Simpson (I Simpson)", "cartoni", "it", "medium"],
    ["Lisa ha bisogno dell'apparecchio!", "Homer Simpson (I Simpson)", "cartoni", "it", "medium"],
    ["Bruttissimo. Il peggiore di sempre.", "Comic Book Guy (I Simpson)", "cartoni", "it", "medium"],
    ["Gli occhiali non servono a niente!", "Rainier Wolfcastle (I Simpson)", "cartoni", "it", "hard"],
    ["Perché tu, ragazzino testone?", "Nelson Muntz (I Simpson)", "cartoni", "it", "medium"],
    ["Niente può andare storto, il che significa che andrà tutto storto.", "Marge Simpson (I Simpson)", "cartoni", "it", "hard"],
    ["Giggity giggity goo!", "Glenn Quagmire (I Griffin)", "cartoni", "it", "easy"],
    ["Che figata!", "Chris Griffin (I Griffin)", "cartoni", "it", "easy"],
    ["La vittoria è mia!", "Stewie Griffin (I Griffin)", "cartoni", "it", "easy"],
    ["Mamma, mamma, mamma...", "Stewie Griffin (I Griffin)", "cartoni", "it", "easy"],
    ["Questo è peggio di quella volta che...", "Peter Griffin (I Griffin)", "cartoni", "it", "medium"],
    ["Siamo qui per salvare la situazione!", "Peter Griffin (I Griffin)", "cartoni", "it", "hard"],
    ["Se solo fossi stato un pianoforte...", "Brian Griffin (I Griffin)", "cartoni", "it", "hard"],
    ["Niente di personale, ma sei un fallito.", "Stewie Griffin (I Griffin)", "cartoni", "it", "hard"],
    ["Ricky Spanish!", "Roger (American Dad)", "cartoni", "it", "hard"],
    ["Cosa potrebbe mai andare storto?", "Stan Smith (American Dad)", "cartoni", "it", "medium"],
    ["Mi chiamo Stan Smith.", "Stan Smith (American Dad)", "cartoni", "it", "easy"],
    ["Sono il tuo nuovo migliore amico!", "Roger (American Dad)", "cartoni", "it", "hard"],
    ["La mia vita è una lunga serie di decisioni sbagliate.", "Bender (Futurama)", "cartoni", "it", "medium"],
    ["Non capisco cosa succede, ma va bene così.", "Fry (Futurama)", "cartoni", "it", "hard"],
    ["Non è la mia natura essere gentile.", "Roger (American Dad)", "cartoni", "it", "hard"],
    ["Questo è il momento peggiore della mia vita.", "Peter Griffin (I Griffin)", "cartoni", "it", "medium"]
  );

  // --- Cartoni · English ---
  QUOTES.push(
    ["Good news, everyone!", "Professor Farnsworth (Futurama)", "cartoni", "en", "easy"],
    ["Bite my shiny metal ass!", "Bender (Futurama)", "cartoni", "en", "easy"],
    ["Shut up and take my money!", "Fry (Futurama)", "cartoni", "en", "easy"],
    ["One art, please!", "Bender (Futurama)", "cartoni", "en", "medium"],
    ["Why not Zoidberg?", "Dr. Zoidberg (Futurama)", "cartoni", "en", "easy"],
    ["You are technically correct, the best kind of correct.", "Futurama", "cartoni", "en", "medium"],
    ["The spirit is willing, but the flesh is spongy and bruised.", "Zapp Brannigan (Futurama)", "cartoni", "en", "hard"],
    ["I am the man with no name, Zapp Brannigan at your service.", "Zapp Brannigan (Futurama)", "cartoni", "en", "hard"],
    ["D'oh!", "Homer Simpson (The Simpsons)", "cartoni", "en", "easy"],
    ["Ay, caramba!", "Bart Simpson (The Simpsons)", "cartoni", "en", "easy"],
    ["Eat my shorts!", "Bart Simpson (The Simpsons)", "cartoni", "en", "easy"],
    ["Don't have a cow, man.", "Bart Simpson (The Simpsons)", "cartoni", "en", "easy"],
    ["Excellent!", "Mr. Burns (The Simpsons)", "cartoni", "en", "easy"],
    ["Release the hounds!", "Mr. Burns (The Simpsons)", "cartoni", "en", "medium"],
    ["Everything's coming up Milhouse!", "Milhouse Van Houten (The Simpsons)", "cartoni", "en", "medium"],
    ["Worst. Episode. Ever.", "Comic Book Guy (The Simpsons)", "cartoni", "en", "medium"],
    ["The goggles! They do nothing!", "Rainier Wolfcastle (The Simpsons)", "cartoni", "en", "hard"],
    ["Why you little...!", "Homer Simpson (The Simpsons)", "cartoni", "en", "easy"],
    ["Meh.", "The Simpsons", "cartoni", "en", "easy"],
    ["Dental plan!", "Homer Simpson (The Simpsons)", "cartoni", "en", "medium"],
    ["Lisa needs braces!", "Homer Simpson (The Simpsons)", "cartoni", "en", "medium"],
    ["I choo-choo-choose you.", "Ralph Wiggum (The Simpsons)", "cartoni", "en", "hard"],
    ["Giggity giggity goo!", "Glenn Quagmire (Family Guy)", "cartoni", "en", "easy"],
    ["Freakin' sweet!", "Chris Griffin (Family Guy)", "cartoni", "en", "easy"],
    ["Victory is mine!", "Stewie Griffin (Family Guy)", "cartoni", "en", "easy"],
    ["Mom, mom, mom, mom...", "Stewie Griffin (Family Guy)", "cartoni", "en", "easy"],
    ["The bird is the word!", "Peter Griffin (Family Guy)", "cartoni", "en", "medium"],
    ["Roadhouse!", "Peter Griffin (Family Guy)", "cartoni", "en", "hard"],
    ["This is worse than the time I...", "Peter Griffin (Family Guy)", "cartoni", "en", "medium"],
    ["What the hell, Brian?", "Stewie Griffin (Family Guy)", "cartoni", "en", "hard"],
    ["Ricky Spanish!", "Roger (American Dad)", "cartoni", "en", "hard"],
    ["What could possibly go wrong?", "Stan Smith (American Dad)", "cartoni", "en", "medium"],
    ["Wheels and the Legman!", "Steve Smith (American Dad)", "cartoni", "en", "hard"],
    ["I am Roger, master of disguise.", "Roger (American Dad)", "cartoni", "en", "hard"],
    ["That's a nice boat, Steve.", "Klaus (American Dad)", "cartoni", "en", "hard"],
    ["Good morning, Smith family!", "Roger (American Dad)", "cartoni", "en", "easy"]
  );

  /* ============================== CANZONI / SONGS ============================== */

  // --- Canzoni · Italiano ---
  QUOTES.push(
    ["Vita spericolata!", "Vasco Rossi (Vita spericolata)", "canzoni", "it", "easy"],
    ["Siamo solo noi.", "Vasco Rossi (Siamo solo noi)", "canzoni", "it", "easy"],
    ["Certe notti la mia mente vaga.", "Ligabue (Certe notti)", "canzoni", "it", "medium"],
    ["La donna cannone.", "Francesco De Gregori (La donna cannone)", "canzoni", "it", "medium"],
    ["Buonanotte fiorellino.", "Francesco De Gregori (Buonanotte fiorellino)", "canzoni", "it", "medium"],
    ["Il pescatore.", "Fabrizio De André (Il pescatore)", "canzoni", "it", "easy"],
    ["La canzone di Marinella.", "Fabrizio De André (La canzone di Marinella)", "canzoni", "it", "easy"],
    ["Qui dove il mare luccica e tira forte il vento.", "Lucio Dalla (Caruso)", "canzoni", "it", "medium"],
    ["Piazza Grande.", "Lucio Dalla (Piazza Grande)", "canzoni", "it", "easy"],
    ["Sapore di sale.", "Gino Paoli (Sapore di sale)", "canzoni", "it", "easy"],
    ["Il cielo in una stanza.", "Gino Paoli (Il cielo in una stanza)", "canzoni", "it", "easy"],
    ["Lasciatemi cantare con la chitarra in mano.", "Toto Cutugno (L'italiano)", "canzoni", "it", "medium"],
    ["Sarà perché ti amo.", "Ricchi e Poveri (Sarà perché ti amo)", "canzoni", "it", "easy"],
    ["Che sarà, che sarà, che sarà.", "Ricchi e Poveri (Che sarà)", "canzoni", "it", "easy"],
    ["Volare, oh oh! Cantare, oh oh oh oh!", "Domenico Modugno (Nel blu dipinto di blu)", "canzoni", "it", "easy"],
    ["Tintarella di luna.", "Mina (Tintarella di luna)", "canzoni", "it", "medium"],
    ["Io che amo solo te.", "Sergio Endrigo (Io che amo solo te)", "canzoni", "it", "easy"],
    ["Con te partirò.", "Andrea Bocelli (Con te partirò)", "canzoni", "it", "easy"],
    ["Tu vuo' fa' l'americano.", "Renato Carosone (Tu vuo' fa' l'americano)", "canzoni", "it", "easy"],
    ["Sei bello e impossibile.", "Gianna Nannini (Bello e impossibile)", "canzoni", "it", "medium"],
    ["Ma il cielo è sempre più blu.", "Rino Gaetano (Ma il cielo è sempre più blu)", "canzoni", "it", "medium"],
    ["Penso positivo.", "Jovanotti (Penso positivo)", "canzoni", "it", "easy"],
    ["Ragazzo fortunato.", "Jovanotti (Ragazzo fortunato)", "canzoni", "it", "easy"],
    ["Maledetta primavera.", "Loretta Goggi (Maledetta primavera)", "canzoni", "it", "medium"],
    ["Vado al massimo.", "Vasco Rossi (Vado al massimo)", "canzoni", "it", "easy"],
    ["Gloria.", "Umberto Tozzi (Gloria)", "canzoni", "it", "medium"],
    ["Ti amo.", "Umberto Tozzi (Ti amo)", "canzoni", "it", "medium"],
    ["Non voglio mica la luna.", "Fiordaliso (Non voglio mica la luna)", "canzoni", "it", "hard"],
    ["L'italiano medio?", "Ligabue (Non è nel pacco regalo)", "canzoni", "it", "hard"],
    ["Ho voglia di una donna, non di una ragazzina.", "Lucio Battisti (Si, viaggiare)", "canzoni", "it", "hard"],
    ["Il mio nome è nessuno, il mio posto è nessun luogo.", "Mina (Il mio nome è nessuno)", "canzoni", "it", "hard"],
    ["Resta lì, non ti muovere, sei troppo bella così.", "Eros Ramazzotti (L'aurora)", "canzoni", "it", "hard"],
    ["Un'altra volta insieme non lo so se ci sarà.", "Adriano Celentano (Il ragazzo della via Gluck)", "canzoni", "it", "medium"],
    ["Azzurro, il pomeriggio è troppo azzurro e lungo per me.", "Adriano Celentano (Azzurro)", "canzoni", "it", "easy"],
    ["Il nostro amore è un fulmine a ciel sereno.", "Lucio Battisti (Fiori rosa, fiori di pesco)", "canzoni", "it", "hard"],
    ["Vendo i miei ricordi, chi li vuole?", "Lucio Dalla (4/3/1943)", "canzoni", "it", "hard"],
    ["E la nave va.", "Lucio Dalla (E la nave va)", "canzoni", "it", "medium"],
    ["Il cielo è di tutti.", "Ivano Fossati (Il cielo è di tutti)", "canzoni", "it", "hard"],
    ["Napule è mille culure.", "Pino Daniele (Napule è)", "canzoni", "it", "hard"],
    ["Io vagabondo, che son io, povero diavolo che se ne va.", "Riccardo Fogli (Vagabondo)", "canzoni", "it", "hard"],
    ["Sono solo canzonette.", "Edoardo Bennato (Sono solo canzonette)", "canzoni", "it", "medium"],
    ["Ho visto un re e quel re mi ha detto: 'Canta'." , "Rino Gaetano (Aida)", "canzoni", "it", "hard"]
  );

  // --- Canzoni · English ---
  QUOTES.push(
    ["I can't get no satisfaction.", "The Rolling Stones (Satisfaction)", "canzoni", "en", "easy"],
    ["Imagine all the people living life in peace.", "John Lennon (Imagine)", "canzoni", "en", "easy"],
    ["Yesterday, all my troubles seemed so far away.", "The Beatles (Yesterday)", "canzoni", "en", "easy"],
    ["Hello, is it me you're looking for?", "Lionel Richie (Hello)", "canzoni", "en", "easy"],
    ["I just called to say I love you.", "Stevie Wonder (I Just Called to Say I Love You)", "canzoni", "en", "easy"],
    ["We will, we will rock you!", "Queen (We Will Rock You)", "canzoni", "en", "easy"],
    ["Is this the real life? Is this just fantasy?", "Queen (Bohemian Rhapsody)", "canzoni", "en", "easy"],
    ["Don't stop believin'!", "Journey (Don't Stop Believin')", "canzoni", "en", "easy"],
    ["Sweet dreams are made of this.", "Eurythmics (Sweet Dreams)", "canzoni", "en", "easy"],
    ["I'm on the highway to hell!", "AC/DC (Highway to Hell)", "canzoni", "en", "easy"],
    ["Back in black!", "AC/DC (Back in Black)", "canzoni", "en", "easy"],
    ["Simply the best.", "Tina Turner (The Best)", "canzoni", "en", "easy"],
    ["I will always love you.", "Whitney Houston (I Will Always Love You)", "canzoni", "en", "easy"],
    ["Thriller! Thriller night!", "Michael Jackson (Thriller)", "canzoni", "en", "easy"],
    ["Beat it!", "Michael Jackson (Beat It)", "canzoni", "en", "easy"],
    ["Billie Jean is not my lover.", "Michael Jackson (Billie Jean)", "canzoni", "en", "easy"],
    ["Like a virgin, touched for the very first time.", "Madonna (Like a Virgin)", "canzoni", "en", "medium"],
    ["I'm sexy and I know it.", "LMFAO (Sexy and I Know It)", "canzoni", "en", "medium"],
    ["Don't worry, be happy.", "Bobby McFerrin (Don't Worry, Be Happy)", "canzoni", "en", "easy"],
    ["I feel good! I knew that I would now!", "James Brown (I Got You)", "canzoni", "en", "easy"],
    ["We could be heroes, just for one day.", "David Bowie (Heroes)", "canzoni", "en", "medium"],
    ["Born to be wild.", "Steppenwolf (Born to Be Wild)", "canzoni", "en", "easy"],
    ["School's out for summer!", "Alice Cooper (School's Out)", "canzoni", "en", "medium"],
    ["I love rock and roll.", "Joan Jett (I Love Rock 'n' Roll)", "canzoni", "en", "easy"],
    ["We are family!", "Sister Sledge (We Are Family)", "canzoni", "en", "easy"],
    ["Sing us a song, you're the piano man.", "Billy Joel (Piano Man)", "canzoni", "en", "medium"],
    ["I'm still standing.", "Elton John (I'm Still Standing)", "canzoni", "en", "easy"],
    ["Take me home, country roads.", "John Denver (Take Me Home, Country Roads)", "canzoni", "en", "easy"],
    ["I walk the line.", "Johnny Cash (I Walk the Line)", "canzoni", "en", "medium"],
    ["Born in the U.S.A.!", "Bruce Springsteen (Born in the U.S.A.)", "canzoni", "en", "easy"],
    ["You shook me all night long.", "AC/DC (You Shook Me All Night Long)", "canzoni", "en", "medium"],
    ["There's a lady who's sure all that glitters is gold.", "Led Zeppelin (Stairway to Heaven)", "canzoni", "en", "medium"],
    ["You can check out any time you like, but you can never leave.", "Eagles (Hotel California)", "canzoni", "en", "medium"],
    ["Welcome to the jungle!", "Guns N' Roses (Welcome to the Jungle)", "canzoni", "en", "medium"],
    ["Exit light, enter night.", "Metallica (Enter Sandman)", "canzoni", "en", "hard"],
    ["Here we are now, entertain us.", "Nirvana (Smells Like Teen Spirit)", "canzoni", "en", "medium"],
    ["What's in your head? Zombie, zombie, zombie-ie-ie.", "The Cranberries (Zombie)", "canzoni", "en", "medium"],
    ["Woah, we're halfway there!", "Bon Jovi (Livin' on a Prayer)", "canzoni", "en", "easy"],
    ["Bye bye, Miss American Pie.", "Don McLean (American Pie)", "canzoni", "en", "medium"],
    ["Starry, starry night.", "Don McLean (Vincent)", "canzoni", "en", "hard"],
    ["Goodbye Norma Jean.", "Elton John (Candle in the Wind)", "canzoni", "en", "hard"],
    ["I'm having such a good time, I'm having a ball.", "Queen (Don't Stop Me Now)", "canzoni", "en", "medium"],
    ["We don't need no education.", "Pink Floyd (Another Brick in the Wall)", "canzoni", "en", "medium"],
    ["Take a sad song and make it better.", "The Beatles (Hey Jude)", "canzoni", "en", "medium"],
    ["All you need is love.", "The Beatles (All You Need Is Love)", "canzoni", "en", "easy"],
    ["Rolling in the deep.", "Adele (Rolling in the Deep)", "canzoni", "en", "easy"],
    ["Hello, it's me.", "Adele (Hello)", "canzoni", "en", "easy"],
    ["If you liked it, then you should have put a ring on it.", "Beyoncé (Single Ladies)", "canzoni", "en", "medium"],
    ["Shake it off!", "Taylor Swift (Shake It Off)", "canzoni", "en", "easy"],
    ["Rah, rah-ah-ah-ah, roma, roma-ma.", "Lady Gaga (Bad Romance)", "canzoni", "en", "hard"],
    ["Hit me baby one more time!", "Britney Spears (...Baby One More Time)", "canzoni", "en", "easy"],
    ["If you wanna be my lover, you gotta get with my friends.", "Spice Girls (Wannabe)", "canzoni", "en", "medium"],
    ["Never gonna give you up, never gonna let you down.", "Rick Astley (Never Gonna Give You Up)", "canzoni", "en", "medium"],
    ["It's the final countdown!", "Europe (The Final Countdown)", "canzoni", "en", "medium"],
    ["Take on me, take me on.", "a-ha (Take On Me)", "canzoni", "en", "medium"],
    ["I want it that way.", "Backstreet Boys (I Want It That Way)", "canzoni", "en", "easy"],
    ["Whoa, we're half way there." , "Bon Jovi (Livin' on a Prayer)", "canzoni", "en", "easy"],
    ["We're not gonna take it anymore!", "Twisted Sister (We're Not Gonna Take It)", "canzoni", "en", "hard"],
    ["I wanna rock and roll all night, and party every day.", "KISS (I Was Made for Lovin' You)", "canzoni", "en", "hard"],
    ["Wake me up before you go-go!", "Wham! (Wake Me Up Before You Go-Go)", "canzoni", "en", "hard"],
    ["You spin me right round, baby, right round.", "Dead or Alive (You Spin Me Round)", "canzoni", "en", "hard"],
    ["I'm gonna be (500 miles).", "The Proclaimers (I'm Gonna Be)", "canzoni", "en", "hard"],
    ["Somebody once told me the world is gonna roll me.", "Smash Mouth (All Star)", "canzoni", "en", "hard"],
    ["Sweet Caroline, buh-buh-buh!", "Neil Diamond (Sweet Caroline)", "canzoni", "en", "hard"],
    ["I want to break free!", "Queen (I Want to Break Free)", "canzoni", "en", "hard"],
    ["Another one bites the dust!", "Queen (Another One Bites the Dust)", "canzoni", "en", "hard"],
    ["Under pressure!", "Queen & David Bowie (Under Pressure)", "canzoni", "en", "hard"]
  );

  /* ============================== LIBRI / BOOKS ============================== */

  // --- Libri · Italiano ---
  QUOTES.push(
    ["Nel mezzo del cammin di nostra vita.", "Dante Alighieri (Divina Commedia)", "libri", "it", "easy"],
    ["Lasciate ogne speranza, voi ch'intrate.", "Dante Alighieri (Divina Commedia)", "libri", "it", "easy"],
    ["Amor, ch'a nullo amato amar perdona.", "Dante Alighieri (Divina Commedia)", "libri", "it", "hard"],
    ["E quindi uscimmo a riveder le stelle.", "Dante Alighieri (Divina Commedia)", "libri", "it", "medium"],
    ["Quel ramo del lago di Como, che volge a mezzogiorno...", "Alessandro Manzoni (I promessi sposi)", "libri", "it", "easy"],
    ["Addio, monti sorgenti dall'acque.", "Alessandro Manzoni (I promessi sposi)", "libri", "it", "medium"],
    ["L'essenziale è invisibile agli occhi.", "Antoine de Saint-Exupéry (Il piccolo principe)", "libri", "it", "easy"],
    ["Tutti i grandi sono stati bambini una volta.", "Antoine de Saint-Exupéry (Il piccolo principe)", "libri", "it", "medium"],
    ["L'uomo non è fatto per la sconfitta.", "Ernest Hemingway (Il vecchio e il mare)", "libri", "it", "medium"],
    ["Chi controlla il passato controlla il futuro.", "George Orwell (1984)", "libri", "it", "medium"],
    ["Tutti gli animali sono uguali, ma alcuni sono più uguali degli altri.", "George Orwell (La fattoria degli animali)", "libri", "it", "easy"],
    ["Un Anello per domarli tutti.", "J.R.R. Tolkien (Il Signore degli Anelli)", "libri", "it", "easy"],
    ["Non sono le nostre capacità che mostrano chi siamo davvero, ma le nostre scelte.", "Albus Silente (Harry Potter)", "libri", "it", "medium"],
    ["Oggi mamma è morta.", "Albert Camus (Lo straniero)", "libri", "it", "medium"],
    ["È una verità universalmente riconosciuta che uno scapolo in possesso di un buon patrimonio debba cercare moglie.", "Jane Austen (Orgoglio e pregiudizio)", "libri", "it", "hard"],
    ["L'unico modo per liberarsi di una tentazione è cedervi.", "Oscar Wilde (Il ritratto di Dorian Gray)", "libri", "it", "hard"],
    ["Qui siamo tutti matti.", "Lewis Carroll (Alice nel Paese delle Meraviglie)", "libri", "it", "easy"],
    ["C'era una volta... un pezzo di legno.", "Carlo Collodi (Pinocchio)", "libri", "it", "medium"],
    ["Sono io, il fu Mattia Pascal.", "Luigi Pirandello (Il fu Mattia Pascal)", "libri", "it", "hard"],
    ["Attendere e sperare.", "Alexandre Dumas (Il conte di Montecristo)", "libri", "it", "medium"],
    ["La guerra è pace. La libertà è schiavitù. L'ignoranza è forza.", "George Orwell (1984)", "libri", "it", "medium"],
    ["Stat rosa pristina nomine, nomina nuda tenemus.", "Umberto Eco (Il nome della rosa)", "libri", "it", "hard"],
    ["Una catena è forte quanto il suo anello più debole.", "Conan Doyle (Sherlock Holmes)", "libri", "it", "hard"],
    ["Quando elimini l'impossibile, ciò che resta, per quanto improbabile, deve essere la verità.", "Sherlock Holmes (Il segno dei Quattro)", "libri", "it", "medium"],
    ["Vivere pericolosamente.", "Friedrich Nietzsche (Il crepuscolo degli idoli)", "libri", "it", "hard"],
    ["Mi chiamo Sherlock Holmes. È mio lavoro sapere ciò che gli altri non sanno.", "Arthur Conan Doyle (Una questione personale)", "libri", "it", "hard"],
    ["Tutto ciò che è necessario è che tu non abbia paura della tua mente.", "J.D. Salinger (Il giovane Holden)", "libri", "it", "hard"],
    ["Il mondo è una mela e noi siamo i vermi.", "John Fante (Chiedi alla polvere)", "libri", "it", "hard"],
    ["Non tutti coloro che vagano sono perduti.", "J.R.R. Tolkien (Il Signore degli Anelli)", "libri", "it", "easy"],
    ["Uno per tutti, tutti per uno!", "Alexandre Dumas (I tre moschettieri)", "libri", "it", "easy"],
    ["Quindici uomini sulla cassa del morto!", "R.L. Stevenson (L'isola del tesoro)", "libri", "it", "easy"]
  );

  // --- Libri · English ---
  QUOTES.push(
    ["Call me Ishmael.", "Herman Melville (Moby Dick)", "libri", "en", "easy"],
    ["It was the best of times, it was the worst of times.", "Charles Dickens (A Tale of Two Cities)", "libri", "en", "medium"],
    ["It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.", "Jane Austen (Pride and Prejudice)", "libri", "en", "hard"],
    ["All animals are equal, but some animals are more equal than others.", "George Orwell (Animal Farm)", "libri", "en", "easy"],
    ["Big Brother is watching you.", "George Orwell (1984)", "libri", "en", "easy"],
    ["War is peace. Freedom is slavery. Ignorance is strength.", "George Orwell (1984)", "libri", "en", "medium"],
    ["To be, or not to be: that is the question.", "William Shakespeare (Hamlet)", "libri", "en", "easy"],
    ["All the world's a stage, and all the men and women merely players.", "William Shakespeare (As You Like It)", "libri", "en", "medium"],
    ["Romeo, Romeo! Wherefore art thou Romeo?", "William Shakespeare (Romeo and Juliet)", "libri", "en", "easy"],
    ["A rose by any other name would smell as sweet.", "William Shakespeare (Romeo and Juliet)", "libri", "en", "medium"],
    ["Friends, Romans, countrymen, lend me your ears.", "William Shakespeare (Julius Caesar)", "libri", "en", "medium"],
    ["Et tu, Brute? Then fall, Caesar.", "William Shakespeare (Julius Caesar)", "libri", "en", "easy"],
    ["It was a dark and stormy night.", "Edward Bulwer-Lytton (Paul Clifford)", "libri", "en", "hard"],
    ["Happy families are all alike; every unhappy family is unhappy in its own way.", "Leo Tolstoy (Anna Karenina)", "libri", "en", "medium"],
    ["Whatever our souls are made of, his and mine are the same.", "Emily Brontë (Wuthering Heights)", "libri", "en", "hard"],
    ["It does not do to dwell on dreams and forget to live.", "Albus Dumbledore (Harry Potter)", "libri", "en", "medium"],
    ["It is our choices, Harry, that show what we truly are.", "Albus Dumbledore (Harry Potter)", "libri", "en", "medium"],
    ["Mischief managed.", "The Marauder's Map (Harry Potter)", "libri", "en", "hard"],
    ["One Ring to rule them all, One Ring to find them.", "J.R.R. Tolkien (The Lord of the Rings)", "libri", "en", "easy"],
    ["Not all those who wander are lost.", "J.R.R. Tolkien (The Lord of the Rings)", "libri", "en", "medium"],
    ["Even the smallest person can change the course of the future.", "Galadriel (The Lord of the Rings)", "libri", "en", "hard"],
    ["So it goes.", "Kurt Vonnegut (Slaughterhouse-Five)", "libri", "en", "medium"],
    ["So we beat on, boats against the current.", "F. Scott Fitzgerald (The Great Gatsby)", "libri", "en", "hard"],
    ["I have always depended on the kindness of strangers.", "Blanche DuBois (A Streetcar Named Desire)", "libri", "en", "medium"],
    ["We're all mad here.", "Cheshire Cat (Alice in Wonderland)", "libri", "en", "easy"],
    ["I'm late, I'm late, for a very important date!", "The White Rabbit (Alice in Wonderland)", "libri", "en", "easy"],
    ["Off with their heads!", "The Queen of Hearts (Alice in Wonderland)", "libri", "en", "medium"],
    ["Reader, I married him.", "Charlotte Brontë (Jane Eyre)", "libri", "en", "hard"],
    ["It is a far, far better thing that I do, than I have ever done.", "Charles Dickens (A Tale of Two Cities)", "libri", "en", "hard"],
    ["Marley was dead: to begin with.", "Charles Dickens (A Christmas Carol)", "libri", "en", "medium"],
    ["God bless us, every one!", "Tiny Tim (A Christmas Carol)", "libri", "en", "medium"],
    ["The horror! The horror!", "Kurtz (Heart of Darkness)", "libri", "en", "medium"],
    ["Everything was beautiful and nothing hurt.", "Kurt Vonnegut (Slaughterhouse-Five)", "libri", "en", "hard"],
    ["Do not go gentle into that good night.", "Dylan Thomas (poem)", "libri", "en", "easy"],
    ["Two roads diverged in a yellow wood.", "Robert Frost (The Road Not Taken)", "libri", "en", "easy"],
    ["Hope is the thing with feathers.", "Emily Dickinson (poem)", "libri", "en", "hard"],
    ["Because I could not stop for Death, He kindly stopped for me.", "Emily Dickinson (poem)", "libri", "en", "hard"],
    ["In my younger and more vulnerable years my father gave me some advice.", "F. Scott Fitzgerald (The Great Gatsby)", "libri", "en", "hard"],
    ["The only way out is through.", "Robert Frost (Servants of Servants)", "libri", "en", "hard"],
    ["O, what a world of unseen possibilities!", "H.G. Wells (The Time Machine)", "libri", "en", "hard"],
    ["You are braver than you believe, stronger than you seem, and smarter than you think.", "A.A. Milne (Winnie the Pooh)", "libri", "en", "easy"]
  );

  /* ============================== STORIA / HISTORY ============================== */

  // --- Storia · Italiano ---
  QUOTES.push(
    ["Veni, vidi, vici.", "Giulio Cesare", "storia", "it", "easy"],
    ["Il dado è tratto.", "Giulio Cesare", "storia", "it", "easy"],
    ["Sono venuto, ho visto, ho vinto.", "Giulio Cesare", "storia", "it", "medium"],
    ["Lo Stato sono io.", "Luigi XIV", "storia", "it", "easy"],
    ["Eppur si muove.", "Galileo Galilei", "storia", "it", "easy"],
    ["Obbedisco!", "Giuseppe Garibaldi", "storia", "it", "medium"],
    ["Libera Chiesa in libero Stato.", "Camillo Benso di Cavour", "storia", "it", "medium"],
    ["Non ho nulla da offrire se non sangue, fatica, lacrime e sudore.", "Winston Churchill", "storia", "it", "medium"],
    ["Hasta la victoria siempre.", "Che Guevara", "storia", "it", "easy"],
    ["Non chiedere cosa può fare il tuo paese per te, chiedi cosa puoi fare tu per il tuo paese.", "John F. Kennedy", "storia", "it", "medium"],
    ["Ho un sogno.", "Martin Luther King", "storia", "it", "easy"],
    ["Impossibile è una parola che si trova solo nel dizionario degli sciocchi.", "Napoleone Bonaparte", "storia", "it", "medium"],
    ["O tempora, o mores!", "Cicerone", "storia", "it", "hard"],
    ["Carpe diem.", "Quinto Orazio Flacco", "storia", "it", "easy"],
    ["So di non sapere.", "Socrate", "storia", "it", "medium"],
    ["Potrete bruciare me, ma non la verità.", "Giordano Bruno", "storia", "it", "hard"],
    ["La mente si adatta a ogni cosa.", "Marco Aurelio", "storia", "it", "hard"],
    ["La semplicità è la massima sofisticazione.", "Leonardo da Vinci", "storia", "it", "hard"],
    ["È meglio essere temuti che amati.", "Niccolò Machiavelli (Il Principe)", "storia", "it", "medium"],
    ["Il fine giustifica i mezzi.", "Niccolò Machiavelli (Il Principe)", "storia", "it", "easy"],
    ["Penso, quindi sono.", "René Descartes", "storia", "it", "easy"],
    ["Il cuore ha le sue ragioni che la ragione non conosce.", "Blaise Pascal", "storia", "it", "medium"],
    ["Dio è morto.", "Friedrich Nietzsche", "storia", "it", "easy"],
    ["Ciò che non mi uccide mi fortifica.", "Friedrich Nietzsche", "storia", "it", "easy"],
    ["La fantasia è più importante della conoscenza.", "Albert Einstein", "storia", "it", "medium"],
    ["Dio non gioca a dadi con l'universo.", "Albert Einstein", "storia", "it", "medium"],
    ["Sii tu il cambiamento che vuoi vedere nel mondo.", "Mahatma Gandhi", "storia", "it", "easy"],
    ["Occhio per occhio lascia il mondo intero cieco.", "Mahatma Gandhi", "storia", "it", "medium"],
    ["Resta affamato, resta sciocco.", "Steve Jobs", "storia", "it", "easy"],
    ["Il futuro appartiene a chi crede nella bellezza dei propri sogni.", "Eleanor Roosevelt", "storia", "it", "hard"],
    ["La forza non deriva dalla capacità fisica, ma da una volontà indomabile.", "Mahatma Gandhi", "storia", "it", "hard"],
    ["Se vedi un uomo buono, imita; se vedi un uomo cattivo, esamina te stesso.", "Confucio", "storia", "it", "hard"],
    ["Il coraggio è la paura che dice le sue preghiere.", "Publilio Siro", "storia", "it", "hard"],
    ["Navigare necesse est, vivere non necesse est.", "Pompeo", "storia", "it", "hard"],
    ["Ancora imparo.", "Michelangelo Buonarroti", "storia", "it", "hard"],
    ["Non posso sopravvivere senza ambizione." , "Napoleone Bonaparte", "storia", "it", "hard"],
    ["Volevo solo che si ricordassero di me.", "Napoleone Bonaparte", "storia", "it", "hard"]
  );

  // --- Storia · English ---
  QUOTES.push(
    ["Veni, vidi, vici.", "Julius Caesar", "storia", "en", "easy"],
    ["The die is cast.", "Julius Caesar", "storia", "en", "easy"],
    ["I came, I saw, I conquered.", "Julius Caesar", "storia", "en", "medium"],
    ["I am the state.", "Louis XIV", "storia", "en", "hard"],
    ["And yet it moves.", "Galileo Galilei", "storia", "en", "medium"],
    ["I have not yet begun to fight!", "John Paul Jones", "storia", "en", "hard"],
    ["Give me liberty, or give me death!", "Patrick Henry", "storia", "en", "medium"],
    ["These are the times that try men's souls.", "Thomas Paine", "storia", "en", "hard"],
    ["We hold these truths to be self-evident.", "Thomas Jefferson", "storia", "en", "easy"],
    ["Ask not what your country can do for you — ask what you can do for your country.", "John F. Kennedy", "storia", "en", "medium"],
    ["Ich bin ein Berliner.", "John F. Kennedy", "storia", "en", "easy"],
    ["We choose to go to the Moon.", "John F. Kennedy", "storia", "en", "hard"],
    ["The only thing we have to fear is fear itself.", "Franklin D. Roosevelt", "storia", "en", "easy"],
    ["I am not a crook.", "Richard Nixon", "storia", "en", "medium"],
    ["Float like a butterfly, sting like a bee.", "Muhammad Ali", "storia", "en", "medium"],
    ["I am the greatest.", "Muhammad Ali", "storia", "en", "easy"],
    ["I have a dream.", "Martin Luther King Jr.", "storia", "en", "easy"],
    ["The time is always right to do what is right.", "Martin Luther King Jr.", "storia", "en", "medium"],
    ["Never, never, never give up.", "Winston Churchill", "storia", "en", "easy"],
    ["We shall fight on the beaches.", "Winston Churchill", "storia", "en", "medium"],
    ["An iron curtain has descended across the Continent.", "Winston Churchill", "storia", "en", "hard"],
    ["Give me your tired, your poor, your huddled masses.", "Emma Lazarus (Statue of Liberty)", "storia", "en", "hard"],
    ["That's one small step for a man, one giant leap for mankind.", "Neil Armstrong", "storia", "en", "easy"],
    ["Houston, we've had a problem.", "Jim Lovell (Apollo 13)", "storia", "en", "medium"],
    ["The British are coming!", "Paul Revere", "storia", "en", "medium"],
    ["Don't shoot until you see the whites of their eyes!", "William Prescott (Bunker Hill)", "storia", "en", "hard"],
    ["Eureka!", "Archimedes", "storia", "en", "easy"],
    ["Give me a lever long enough and I shall move the world.", "Archimedes", "storia", "en", "medium"],
    ["I think, therefore I am.", "René Descartes", "storia", "en", "easy"],
    ["God is dead.", "Friedrich Nietzsche", "storia", "en", "medium"],
    ["That which does not kill us makes us stronger.", "Friedrich Nietzsche", "storia", "en", "easy"],
    ["The heart has its reasons which reason knows not.", "Blaise Pascal", "storia", "en", "hard"],
    ["I disapprove of what you say, but I will defend to the death your right to say it.", "Voltaire", "storia", "en", "medium"],
    ["The end justifies the means.", "Niccolò Machiavelli (The Prince)", "storia", "en", "easy"],
    ["It is better to be feared than loved.", "Niccolò Machiavelli (The Prince)", "storia", "en", "medium"],
    ["The unexamined life is not worth living.", "Socrates", "storia", "en", "medium"],
    ["I know that I know nothing.", "Socrates", "storia", "en", "easy"],
    ["Carpe diem.", "Horace", "storia", "en", "easy"],
    ["When you look long into an abyss, the abyss also looks into you.", "Friedrich Nietzsche", "storia", "en", "hard"],
    ["Imagination is more important than knowledge.", "Albert Einstein", "storia", "en", "medium"],
    ["God does not play dice with the universe.", "Albert Einstein", "storia", "en", "medium"],
    ["If you can't explain it simply, you don't understand it well enough.", "Albert Einstein", "storia", "en", "medium"],
    ["Be the change you wish to see in the world.", "Mahatma Gandhi", "storia", "en", "easy"],
    ["An eye for an eye only ends up making the whole world blind.", "Mahatma Gandhi", "storia", "en", "medium"],
    ["The only way to do great work is to love what you do.", "Steve Jobs", "storia", "en", "medium"],
    ["Stay hungry, stay foolish.", "Steve Jobs", "storia", "en", "easy"],
    ["Mr. Gorbachev, tear down this wall!", "Ronald Reagan", "storia", "en", "hard"],
    ["Education is the most powerful weapon which you can use to change the world.", "Nelson Mandela", "storia", "en", "medium"],
    ["It always seems impossible until it's done.", "Nelson Mandela", "storia", "en", "hard"],
    ["The secret of getting ahead is getting started.", "Mark Twain", "storia", "en", "medium"],
    ["Never let school interfere with your education.", "Mark Twain", "storia", "en", "hard"],
    ["If you tell the truth, you don't have to remember anything.", "Mark Twain", "storia", "en", "medium"],
    ["Choose a job you love, and you will never have to work a day in your life.", "Confucius", "storia", "en", "easy"],
    ["It does not matter how slowly you go as long as you do not stop.", "Confucius", "storia", "en", "medium"],
    ["Great minds discuss ideas; average minds discuss events; small minds discuss people.", "Eleanor Roosevelt", "storia", "en", "hard"],
    ["The greatest glory in living lies not in never falling, but in rising every time we fall.", "Nelson Mandela", "storia", "en", "medium"]
  );

  /* ============================== VIDEOGIOCHI / VIDEO GAMES ============================== */

  // --- Videogiochi · Italiano ---
  QUOTES.push(
    ["It's-a me, Mario!", "Mario (Super Mario)", "videogiochi", "it", "easy"],
    ["Devo prenderli tutti!", "Pokémon (motto)", "videogiochi", "it", "easy"],
    ["È superefficace!", "Pokémon (messaggio di battaglia)", "videogiochi", "it", "easy"],
    ["La torta è una bugia.", "GLaDOS (Portal)", "videogiochi", "it", "medium"],
    ["Ehi, ascolta!", "Navi (The Legend of Zelda)", "videogiochi", "it", "easy"],
    ["Ti sei finalmente svegliato.", "Imperiale (The Elder Scrolls V: Skyrim)", "videogiochi", "it", "hard"],
    ["La guerra non cambia mai.", "Ron Perlman (Fallout)", "videogiochi", "it", "easy"],
    ["È pericoloso andare da soli! Prendi questo.", "Vecchio (The Legend of Zelda)", "videogiochi", "it", "medium"],
    ["Svegliati, samurai!", "Johnny Silverhand (Cyberpunk 2077)", "videogiochi", "it", "medium"],
    ["Fermati un attimo e ascolta.", "Deckard Cain (Diablo)", "videogiochi", "it", "medium"],
    ["Un uomo sceglie, uno schiavo obbedisce.", "Andrew Ryan (BioShock)", "videogiochi", "it", "hard"],
    ["Faresti per favore...?", "Andrew Ryan (BioShock)", "videogiochi", "it", "hard"],
    ["Sono le dodici in punto.", "Cassidy (Overwatch)", "videogiochi", "it", "easy"],
    ["Mi serve un'arma.", "Master Chief (Halo)", "videogiochi", "it", "medium"],
    ["Svegliami quando avrai bisogno di me.", "Master Chief (Halo 3)", "videogiochi", "it", "hard"],
    ["Non osare diventare Hollow.", "Laurence (Dark Souls)", "videogiochi", "it", "hard"],
    ["Ragazzo.", "Kratos (God of War)", "videogiochi", "it", "medium"],
    ["Devo andare veloce!", "Sonic the Hedgehog", "videogiochi", "it", "easy"],
    ["Ah, merda, ci risiamo.", "CJ (Grand Theft Auto: San Andreas)", "videogiochi", "it", "medium"],
    ["Ti ho fatto aspettare, eh?", "Big Boss (Metal Gear Solid)", "videogiochi", "it", "hard"],
    ["Sul sul!", "I Sim (The Sims)", "videogiochi", "it", "medium"],
    ["Squarcia e lacera.", "Doom Slayer (DOOM)", "videogiochi", "it", "hard"],
    ["Fuori c'è una bella giornata.", "Flowey (Undertale)", "videogiochi", "it", "hard"],
    ["Resta determinato.", "Undertale", "videogiochi", "it", "hard"],
    ["Ti serve più vespene gas.", "Protoss (StarCraft)", "videogiochi", "it", "medium"],
    ["Servono più minerali.", "Terran (StarCraft)", "videogiochi", "it", "medium"],
    ["Wololo!", "Monaco (Age of Empires)", "videogiochi", "it", "easy"],
    ["Per poco non diventi una Jill sandwich!", "Barry Burton (Resident Evil)", "videogiochi", "it", "hard"],
    ["Hmm.", "Geralt of Rivia (The Witcher)", "videogiochi", "it", "hard"],
    ["La pattuglia del Mojave quasi ti fa desiderare un inverno nucleare.", "Ranger NCR (Fallout: New Vegas)", "videogiochi", "it", "hard"],
    ["Continua a trovare qualcosa per cui combattere.", "Joel (The Last of Us)", "videogiochi", "it", "hard"],
    ["Ti ho dato tutto quello che avevo.", "Arthur Morgan (Red Dead Redemption 2)", "videogiochi", "it", "hard"],
    ["Pika pika!", "Pikachu (Pokémon)", "videogiochi", "it", "easy"],
    ["Wow! Una moneta!", "Toad (Super Mario)", "videogiochi", "it", "easy"],
    ["Splendido!", "Bowser (Super Mario)", "videogiochi", "it", "easy"],
    ["Gioco finito!", "Game over (diversi giochi)", "videogiochi", "it", "easy"]
  );

  // --- Videogiochi · English ---
  QUOTES.push(
    ["It's-a me, Mario!", "Mario (Super Mario)", "videogiochi", "en", "easy"],
    ["Gotta catch 'em all!", "Pokémon (motto)", "videogiochi", "en", "easy"],
    ["It's super effective!", "Pokémon (battle message)", "videogiochi", "en", "easy"],
    ["The cake is a lie.", "GLaDOS (Portal)", "videogiochi", "en", "medium"],
    ["Hey! Listen!", "Navi (The Legend of Zelda)", "videogiochi", "en", "easy"],
    ["Hey, you. You're finally awake.", "Imperial (The Elder Scrolls V: Skyrim)", "videogiochi", "en", "hard"],
    ["War. War never changes.", "Ron Perlman (Fallout)", "videogiochi", "en", "easy"],
    ["It's dangerous to go alone! Take this.", "Old Man (The Legend of Zelda)", "videogiochi", "en", "medium"],
    ["Wake up, Samurai!", "Johnny Silverhand (Cyberpunk 2077)", "videogiochi", "en", "medium"],
    ["Stay a while and listen.", "Deckard Cain (Diablo)", "videogiochi", "en", "medium"],
    ["A man chooses, a slave obeys.", "Andrew Ryan (BioShock)", "videogiochi", "en", "hard"],
    ["Would you kindly...?", "Andrew Ryan (BioShock)", "videogiochi", "en", "hard"],
    ["It's high noon.", "Cassidy (Overwatch)", "videogiochi", "en", "easy"],
    ["I need a weapon.", "Master Chief (Halo)", "videogiochi", "en", "medium"],
    ["Wake me when you need me.", "Master Chief (Halo 3)", "videogiochi", "en", "hard"],
    ["Don't you dare go Hollow.", "Laurence (Dark Souls)", "videogiochi", "en", "hard"],
    ["Boy.", "Kratos (God of War)", "videogiochi", "en", "medium"],
    ["Gotta go fast!", "Sonic the Hedgehog", "videogiochi", "en", "easy"],
    ["Ah shit, here we go again.", "CJ (Grand Theft Auto: San Andreas)", "videogiochi", "en", "medium"],
    ["Kept you waiting, huh?", "Big Boss (Metal Gear Solid)", "videogiochi", "en", "hard"],
    ["Sul sul!", "The Sims", "videogiochi", "en", "medium"],
    ["Rip and tear.", "Doom Slayer (DOOM)", "videogiochi", "en", "hard"],
    ["It's a beautiful day outside.", "Flowey (Undertale)", "videogiochi", "en", "hard"],
    ["Stay determined.", "Undertale", "videogiochi", "en", "hard"],
    ["You require more vespene gas.", "Protoss (StarCraft)", "videogiochi", "en", "medium"],
    ["You require more minerals.", "Terran (StarCraft)", "videogiochi", "en", "medium"],
    ["Wololo!", "Monk (Age of Empires)", "videogiochi", "en", "easy"],
    ["You were almost a Jill sandwich!", "Barry Burton (Resident Evil)", "videogiochi", "en", "hard"],
    ["Hmm.", "Geralt of Rivia (The Witcher)", "videogiochi", "en", "hard"],
    ["Patrolling the Mojave almost makes you wish for a nuclear winter.", "NCR Ranger (Fallout: New Vegas)", "videogiochi", "en", "hard"],
    ["You keep finding something to fight for.", "Joel (The Last of Us)", "videogiochi", "en", "hard"],
    ["I gave you all I had.", "Arthur Morgan (Red Dead Redemption 2)", "videogiochi", "en", "hard"],
    ["It's not about winning or losing. It's about how hard you try.", "Sonic the Hedgehog", "videogiochi", "en", "hard"],
    ["A winner is a dreamer who never gives up.", "Nelson (The Legend of Zelda)", "videogiochi", "en", "medium"],
    ["Wait! You can't spell 'slaughter' without laughter.", "Sans (Undertale)", "videogiochi", "en", "hard"],
    ["Pika pika!", "Pikachu (Pokémon)", "videogiochi", "en", "easy"],
    ["Yahoo!", "Mario (Super Mario)", "videogiochi", "en", "easy"],
    ["It's a-me, Mario!", "Mario (Super Mario 64)", "videogiochi", "en", "easy"],
    ["Game over!", "Game over (vari giochi)", "videogiochi", "en", "easy"]
  );

  /* ============================== PROVERBI / PROVERBS ============================== */

  // --- Proverbi · Italiano ---
  QUOTES.push(
    ["Chi va piano va sano e va lontano.", "Proverbio italiano", "proverbi", "it", "easy"],
    ["Meglio un uovo oggi che una gallina domani.", "Proverbio italiano", "proverbi", "it", "easy"],
    ["Non è tutto oro ciò che luccica.", "Proverbio italiano", "proverbi", "it", "easy"],
    ["Chi dorme non piglia pesci.", "Proverbio italiano", "proverbi", "it", "easy"],
    ["L'abito non fa il monaco.", "Proverbio italiano", "proverbi", "it", "easy"],
    ["Il lupo perde il pelo ma non il vizio.", "Proverbio italiano", "proverbi", "it", "easy"],
    ["Can che abbaia non morde.", "Proverbio italiano", "proverbi", "it", "easy"],
    ["Tanto va la gatta al lardo che ci lascia lo zampino.", "Proverbio toscano", "proverbi", "it", "medium"],
    ["Tra il dire e il fare c'è di mezzo il mare.", "Proverbio italiano", "proverbi", "it", "easy"],
    ["L'appetito vien mangiando.", "Proverbio francese", "proverbi", "it", "easy"],
    ["Roma non è stata fatta in un giorno.", "Proverbio italiano", "proverbi", "it", "easy"],
    ["Tutte le strade portano a Roma.", "Proverbio italiano", "proverbi", "it", "easy"],
    ["Errare humanum est, perseverare autem diabolicum.", "Proverbio latino", "proverbi", "it", "medium"],
    ["Uomo avvisato, mezzo salvato.", "Proverbio italiano", "proverbi", "it", "easy"],
    ["Chi trova un amico trova un tesoro.", "Proverbio italiano", "proverbi", "it", "easy"],
    ["Chi non risica non rosica.", "Proverbio italiano", "proverbi", "it", "easy"],
    ["Il mattino ha l'oro in bocca.", "Proverbio italiano", "proverbi", "it", "easy"],
    ["Nella botte piccola c'è il vino buono.", "Proverbio italiano", "proverbi", "it", "medium"],
    ["Al contadino non far sapere quanto è buono il cacio con le pere.", "Proverbio toscano", "proverbi", "it", "hard"],
    ["Volere è potere.", "Proverbio italiano", "proverbi", "it", "easy"],
    ["Meglio tardi che mai.", "Proverbio italiano", "proverbi", "it", "easy"],
    ["Chi ben comincia è a metà dell'opera.", "Proverbio italiano", "proverbi", "it", "easy"],
    ["L'unione fa la forza.", "Proverbio italiano", "proverbi", "it", "easy"],
    ["A caval donato non si guarda in bocca.", "Proverbio italiano", "proverbi", "it", "medium"],
    ["Paese che vai, usanze che trovi.", "Proverbio italiano", "proverbi", "it", "easy"],
    ["Patti chiari, amicizia lunga.", "Proverbio italiano", "proverbi", "it", "easy"],
    ["La speranza è l'ultima a morire.", "Proverbio italiano", "proverbi", "it", "easy"],
    ["Fidarsi è bene, non fidarsi è meglio.", "Proverbio italiano", "proverbi", "it", "easy"],
    ["Occhio non vede, cuore non duole.", "Proverbio italiano", "proverbi", "it", "easy"],
    ["Rosso di sera, bel tempo si spera.", "Proverbio italiano", "proverbi", "it", "medium"],
    ["Quando il gatto non c'è, i topi ballano.", "Proverbio italiano", "proverbi", "it", "easy"],
    ["Chi semina vento raccoglie tempesta.", "Proverbio italiano", "proverbi", "it", "easy"],
    ["Una mano lava l'altra e tutte e due lavano il viso.", "Proverbio italiano", "proverbi", "it", "medium"],
    ["Non dire gatto se non l'hai nel sacco.", "Proverbio italiano", "proverbi", "it", "hard"],
    ["Chi troppo vuole nulla stringe.", "Proverbio italiano", "proverbi", "it", "easy"],
    ["Meglio un giorno da leone che cento da pecora.", "Proverbio italiano", "proverbi", "it", "medium"],
    ["Una mela al giorno toglie il medico di torno.", "Proverbio inglese", "proverbi", "it", "easy"],
    ["Gallina vecchia fa buon brodo.", "Proverbio italiano", "proverbi", "it", "medium"],
    ["Prendere due piccioni con una fava.", "Proverbio italiano", "proverbi", "it", "easy"],
    ["Piove sempre sul bagnato.", "Proverbio italiano", "proverbi", "it", "medium"],
    ["Non si può avere la botte piena e la moglie ubriaca.", "Proverbio italiano", "proverbi", "it", "medium"],
    ["Traduttore, traditore.", "Proverbio italiano", "proverbi", "it", "hard"],
    ["La goccia scava la roccia.", "Proverbio latino", "proverbi", "it", "hard"],
    ["Chi va a letto senza cena, tutta notte sogna ad altro.", "Proverbio italiano", "proverbi", "it", "hard"],
    ["Il riso abbonda sulla bocca degli sciocchi.", "Proverbio italiano", "proverbi", "it", "medium"],
    ["A poco a poco l'uccellino fa il nido.", "Proverbio italiano", "proverbi", "it", "hard"],
    ["La botte piena e la moglie ubriaca.", "Proverbio italiano", "proverbi", "it", "medium"],
    ["Chi ben comincia, a metà dell'opera è.", "Proverbio toscano", "proverbi", "it", "medium"],
    ["L'acqua corre al mare.", "Proverbio italiano", "proverbi", "it", "hard"],
    ["Ogni scarafone è bello a mamma sua.", "Proverbio napoletano", "proverbi", "it", "hard"],
    ["La pratica è la vera scuola di ognuno.", "Proverbio italiano", "proverbi", "it", "hard"],
    ["A ogni uccello il suo nido è bello.", "Proverbio italiano", "proverbi", "it", "hard"],
    ["Prima il dovere, poi il piacere.", "Proverbio italiano", "proverbi", "it", "medium"],
    ["L'occasione fa l'uomo ladro.", "Proverbio italiano", "proverbi", "it", "easy"],
    ["Il buon giorno si vede dal mattino.", "Proverbio italiano", "proverbi", "it", "hard"],
    ["A chi non ha nulla da perdere, niente fa paura.", "Proverbio italiano", "proverbi", "it", "hard"],
    ["Meglio pochi ma buoni.", "Proverbio italiano", "proverbi", "it", "medium"]
  );

  // --- Proverbi · English ---
  QUOTES.push(
    ["The early bird catches the worm.", "English proverb", "proverbi", "en", "easy"],
    ["Better late than never.", "English proverb", "proverbi", "en", "easy"],
    ["Every cloud has a silver lining.", "English proverb", "proverbi", "en", "easy"],
    ["When in Rome, do as the Romans do.", "English proverb", "proverbi", "en", "medium"],
    ["All that glitters is not gold.", "English proverb", "proverbi", "en", "easy"],
    ["Actions speak louder than words.", "English proverb", "proverbi", "en", "easy"],
    ["Don't count your chickens before they hatch.", "English proverb", "proverbi", "en", "medium"],
    ["A penny saved is a penny earned.", "Benjamin Franklin", "proverbi", "en", "medium"],
    ["Practice makes perfect.", "English proverb", "proverbi", "en", "easy"],
    ["Rome wasn't built in a day.", "English proverb", "proverbi", "en", "easy"],
    ["The grass is always greener on the other side.", "English proverb", "proverbi", "en", "easy"],
    ["A picture is worth a thousand words.", "English proverb", "proverbi", "en", "easy"],
    ["Necessity is the mother of invention.", "English proverb", "proverbi", "en", "medium"],
    ["The pen is mightier than the sword.", "Edward Bulwer-Lytton", "proverbi", "en", "medium"],
    ["You can't judge a book by its cover.", "English proverb", "proverbi", "en", "easy"],
    ["Don't bite the hand that feeds you.", "English proverb", "proverbi", "en", "easy"],
    ["Two heads are better than one.", "English proverb", "proverbi", "en", "easy"],
    ["Curiosity killed the cat.", "English proverb", "proverbi", "en", "easy"],
    ["Blood is thicker than water.", "English proverb", "proverbi", "en", "easy"],
    ["Birds of a feather flock together.", "English proverb", "proverbi", "en", "easy"],
    ["Absence makes the heart grow fonder.", "English proverb", "proverbi", "en", "medium"],
    ["Out of sight, out of mind.", "English proverb", "proverbi", "en", "easy"],
    ["Look before you leap.", "English proverb", "proverbi", "en", "easy"],
    ["Don't put all your eggs in one basket.", "English proverb", "proverbi", "en", "easy"],
    ["Where there's a will, there's a way.", "English proverb", "proverbi", "en", "easy"],
    ["No pain, no gain.", "English proverb", "proverbi", "en", "easy"],
    ["Better safe than sorry.", "English proverb", "proverbi", "en", "easy"],
    ["The proof of the pudding is in the eating.", "English proverb", "proverbi", "en", "hard"],
    ["A rolling stone gathers no moss.", "English proverb", "proverbi", "en", "medium"],
    ["Great minds think alike.", "English proverb", "proverbi", "en", "easy"],
    ["Fortune favors the bold.", "Latin proverb", "proverbi", "en", "medium"],
    ["Still waters run deep.", "English proverb", "proverbi", "en", "medium"],
    ["Too many cooks spoil the broth.", "English proverb", "proverbi", "en", "medium"],
    ["An apple a day keeps the doctor away.", "English proverb", "proverbi", "en", "easy"],
    ["Honesty is the best policy.", "English proverb", "proverbi", "en", "easy"],
    ["Every dog has his day.", "English proverb", "proverbi", "en", "easy"],
    ["Haste makes waste.", "English proverb", "proverbi", "en", "medium"],
    ["If the shoe fits, wear it.", "English proverb", "proverbi", "en", "hard"],
    ["Money doesn't grow on trees.", "English proverb", "proverbi", "en", "easy"],
    ["A bird in the hand is worth two in the bush.", "English proverb", "proverbi", "en", "medium"],
    ["Barking dogs seldom bite.", "English proverb", "proverbi", "en", "medium"],
    ["Don't cry over spilt milk.", "English proverb", "proverbi", "en", "easy"],
    ["Kill two birds with one stone.", "English proverb", "proverbi", "en", "easy"],
    ["Let sleeping dogs lie.", "English proverb", "proverbi", "en", "medium"],
    ["Make hay while the sun shines.", "English proverb", "proverbi", "en", "medium"],
    ["Once bitten, twice shy.", "English proverb", "proverbi", "en", "hard"],
    ["Waste not, want not.", "English proverb", "proverbi", "en", "medium"],
    ["When the going gets tough, the tough get going.", "English proverb", "proverbi", "en", "medium"],
    ["You can lead a horse to water, but you can't make it drink.", "English proverb", "proverbi", "en", "medium"],
    ["Good things come to those who wait.", "English proverb", "proverbi", "en", "easy"],
    ["If it ain't broke, don't fix it.", "American proverb", "proverbi", "en", "medium"],
    ["One man's trash is another man's treasure.", "English proverb", "proverbi", "en", "easy"],
    ["Time heals all wounds.", "English proverb", "proverbi", "en", "easy"],
    ["Two wrongs don't make a right.", "English proverb", "proverbi", "en", "easy"],
    ["Where there's smoke, there's fire.", "English proverb", "proverbi", "en", "medium"],
    ["You reap what you sow.", "English proverb", "proverbi", "en", "medium"],
    ["Speak of the devil, and he shall appear.", "English proverb", "proverbi", "en", "medium"],
    ["A watched pot never boils.", "English proverb", "proverbi", "en", "hard"],
    ["All's fair in love and war.", "English proverb", "proverbi", "en", "medium"],
    ["Beggars can't be choosers.", "English proverb", "proverbi", "en", "hard"],
    ["Don't judge a man until you've walked a mile in his shoes.", "English proverb", "proverbi", "en", "medium"],
    ["Every rose has its thorn.", "English proverb", "proverbi", "en", "easy"],
    ["Ignorance is bliss.", "English proverb", "proverbi", "en", "easy"],
    ["It takes two to tango.", "English proverb", "proverbi", "en", "medium"],
    ["The more the merrier.", "English proverb", "proverbi", "en", "easy"],
    ["Half a loaf is better than none.", "English proverb", "proverbi", "en", "hard"],
    ["A fool and his money are soon parted.", "English proverb", "proverbi", "en", "hard"],
    ["The longest journey begins with a single step.", "Chinese proverb", "proverbi", "en", "hard"],
    ["Don't make a mountain out of a molehill.", "English proverb", "proverbi", "en", "hard"],
    ["Every picture tells a story.", "English proverb", "proverbi", "en", "hard"],
    ["The squeaky wheel gets the grease.", "English proverb", "proverbi", "en", "hard"]
  );
  return { QUOTES: QUOTES };
});
