from __future__ import annotations

import os
from pathlib import Path
from typing import Optional

from vertest.analysis.types import FunctionInfo, SourceUnit


class TestDriverGenerator:
    """Generates a C test driver (harness) for unit testing.
    The driver includes the UUT, sets up stubs, runs test cases,
    and reports pass/fail results."""

    def __init__(self, output_dir: str | Path):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate(
        self,
        unit: SourceUnit,
        target_function: str,
        test_cases: list[dict],
        stub_functions: list[FunctionInfo] | None = None,
    ) -> Path:
        driver_path = self.output_dir / f"test_{target_function}.c"

        func_info = self._find_function(unit, target_function)
        if not func_info:
            raise ValueError(f"Function '{target_function}' not found in {unit.file_path}")

        includes = self._collect_includes(unit)
        stub_declarations = ""
        if stub_functions:
            stub_decls = []
            for sf in stub_functions:
                stub_decls.append(f"extern int stub_{sf.name}_configure(int return_value);")
                stub_decls.append(f"extern int stub_{sf.name}_call_count_get(void);")
            stub_declarations = "\n".join(stub_decls)

        content = self._render_driver(
            target_function=target_function,
            source_file=unit.file_path,
            includes=includes,
            func_info=func_info,
            test_cases=test_cases,
            stub_declarations=stub_declarations,
        )
        driver_path.write_text(content)
        return driver_path

    def _render_driver(
        self,
        target_function: str,
        source_file: str,
        includes: list[str],
        func_info: FunctionInfo,
        test_cases: list[dict],
        stub_declarations: str,
    ) -> str:
        # Build a forward declaration for the function under test
        params_str = ", ".join(
            f"{p.type_name} {'*' if p.is_pointer else ''}{p.name or ''}"
            for p in func_info.parameters
        ) or "void"
        func_decl = f"{func_info.return_type or 'int'} {target_function}({params_str});"

        lines = [
            "/*",
            f" * Auto-generated test driver for {target_function}",
            " * Generated by VeriTest",
            " */",
            '#include <stdio.h>',
            '#include <stdlib.h>',
            '#include <string.h>',
            '#include <math.h>',
            '',
            func_decl,
            '',
            '/* Test result counters */',
            'static int vertest_pass_count = 0;',
            'static int vertest_fail_count = 0;',
            'static int vertest_test_index = 0;',
            '',
            '#define VERTEST_ASSERT(cond, msg) do { \\',
            '    vertest_test_index++; \\',
            '    if (!(cond)) { \\',
            '        fprintf(stderr, "FAIL [%d] %s\\n", vertest_test_index, msg); \\',
            '        vertest_fail_count++; \\',
            '    } else { \\',
            '        fprintf(stdout, "PASS [%d] %s\\n", vertest_test_index, msg); \\',
            '        vertest_pass_count++; \\',
            '    } \\',
            '} while(0)',
            '',
            '#define VERTEST_ASSERT_EQ(actual, expected, msg) \\',
            '    VERTEST_ASSERT((actual) == (expected), msg)',
            '',
            '#define VERTEST_ASSERT_NEAR(actual, expected, tol, msg) \\',
            '    VERTEST_ASSERT(fabs((double)(actual) - (double)(expected)) < (double)(tol), msg)',
            '',
            '#define VERTEST_ASSERT_STR_EQ(actual, expected, msg) \\',
            '    VERTEST_ASSERT(strcmp((actual), (expected)) == 0, msg)',
            '',
            '#define VERTEST_ASSERT_NULL(ptr, msg) \\',
            '    VERTEST_ASSERT((ptr) == NULL, msg)',
            '',
            '#define VERTEST_ASSERT_NOT_NULL(ptr, msg) \\',
            '    VERTEST_ASSERT((ptr) != NULL, msg)',
            '',
            '#define VERTEST_ASSERT_TRUE(cond, msg) \\',
            '    VERTEST_ASSERT((cond), msg)',
            '',
            '#define VERTEST_ASSERT_FALSE(cond, msg) \\',
            '    VERTEST_ASSERT(!(cond), msg)',
            '',
            stub_declarations,
            '',
        ]

        # Generate test case functions
        for i, tc in enumerate(test_cases):
            tc_name = tc.get("name", f"test_{i + 1}")
            lines.extend(self._render_test_case(tc_name, target_function, func_info, tc, i))

        # Main function
        lines.extend([
            '',
            'int main(void) {',
            '    fprintf(stdout, "VeriTest Test Runner\\n");',
            '    fprintf(stdout, "====================\\n");',
            '    fprintf(stdout, "Testing: %s\\n\\n", "' + target_function + '");',
            '',
        ])

        for i, tc in enumerate(test_cases):
            tc_name = tc.get("name", f"test_{i + 1}")
            lines.append(f'    run_{tc_name}();')

        lines.extend([
            '',
            '    fprintf(stdout, "\\n====================\\n");',
            '    fprintf(stdout, "Results: %d passed, %d failed\\n",',
            '            vertest_pass_count, vertest_fail_count);',
            '',
            '    return vertest_fail_count > 0 ? 1 : 0;',
            '}',
        ])

        return "\n".join(lines)

    def _render_test_case(
        self,
        name: str,
        target_function: str,
        func_info: FunctionInfo,
        tc: dict,
        index: int,
    ) -> list[str]:
        lines = [
            '',
            f'static void run_{name}(void) {{',
            f'    /* Test case: {name} */',
        ]

        # Stub configuration
        stubs = tc.get("stubs", {})
        for stub_name, stub_config in stubs.items():
            if isinstance(stub_config, list):
                for val in stub_config:
                    lines.append(f'    stub_{stub_name}_configure({val});')
            else:
                lines.append(f'    stub_{stub_name}_configure({stub_config});')

        # Build call arguments
        args = tc.get("args", {})
        arg_vals = []
        for param in func_info.parameters:
            if param.name in args:
                arg_vals.append(self._format_arg(param, args[param.name]))
            else:
                arg_vals.append(self._default_arg(param))

        # Declare result variable if not void
        return_type = func_info.return_type or "void"
        if return_type != "void":
            result_var = f"result_{index}"
            lines.append(f'    {return_type} {result_var};')
            lines.append(f'    {result_var} = {target_function}({", ".join(arg_vals)});')
        else:
            lines.append(f'    {target_function}({", ".join(arg_vals)});')
            result_var = None

        # Assertions
        assertions = tc.get("asserts", tc.get("expected", {}))
        for what, expected in assertions.items():
            if what == "return" and result_var:
                if isinstance(expected, str) and expected.startswith("~"):
                    tol = expected[1:]
                    lines.append(f'    VERTEST_ASSERT_NEAR({result_var}, {expected}, {tol}, "{name}: return != {expected}");')
                elif isinstance(expected, str):
                    lines.append(f'    VERTEST_ASSERT_STR_EQ({result_var}, "{expected}", "{name}: return != {expected}");')
                else:
                    lines.append(f'    VERTEST_ASSERT_EQ({result_var}, {expected}, "{name}: return != {expected}");')
            elif what.startswith("stub_calls_"):
                stub_name = what.replace("stub_calls_", "")
                lines.append(f'    VERTEST_ASSERT_EQ(stub_{stub_name}_call_count_get(), {expected}, "{name}: {stub_name} call count != {expected}");')

        lines.append('}')
        return lines

    @staticmethod
    def _collect_includes(unit: SourceUnit) -> list[str]:
        includes = []
        for inc in unit.includes:
            if inc.is_system:
                includes.append(f"#include <{inc.path}>")
            else:
                includes.append(f'#include "{inc.path}"')
        return includes

    @staticmethod
    def _find_function(unit: SourceUnit, name: str) -> FunctionInfo | None:
        for func in unit.functions:
            if func.name == name:
                return func
        return None

    @staticmethod
    def _format_arg(param, value):
        if value is None:
            return "0"
        if isinstance(value, str) and not value.startswith("("):
            return f'"{value}"'
        return str(value)

    @staticmethod
    def _default_arg(param: Parameter) -> str:
        if param.is_pointer:
            return "NULL"
        type_lower = param.type_name.lower().strip()
        if any(t in type_lower for t in ("int", "char", "short", "long", "size_t", "enum")):
            return "0"
        if any(t in type_lower for t in ("float", "double")):
            return "0.0"
        return "0"
