from __future__ import annotations

import os
from pathlib import Path
from typing import Optional

from vertest.analysis.types import FunctionInfo, Parameter


STUB_HEADER = """/*
 * Auto-generated by VeriTest - Stub Framework
 * DO NOT EDIT
 */
#ifndef VERTEST_STUBS_H
#define VERTEST_STUBS_H

#include <stdarg.h>
#include <stddef.h>
#include <setjmp.h>
#include <string.h>

/* Stub call recording structure */
typedef struct {
    const char* function_name;
    int call_count;
    int max_calls;
} vertest_stub_control_t;

/* Global stub control */
extern vertest_stub_control_t vertest_stub_controls[];

/* Reset all stub call counts */
void vertest_reset_all_stubs(void);

/* Configure stub return values at runtime */
int vertest_stub_return_int(const char* func_name, int default_val);
double vertest_stub_return_double(const char* func_name, double default_val);
const char* vertest_stub_return_string(const char* func_name, const char* default_val);

#endif /* VERTEST_STUBS_H */
"""

STUB_IMPL = """/*
 * Auto-generated by VeriTest - Stub Framework Implementation
 * DO NOT EDIT
 */
#include "vertest_stubs.h"

/* Record stub metadata */
typedef struct {
    const char* name;
    int current;
    int configured_values[64];
    int configured_count;
} vertest_stub_state_t;

static vertest_stub_state_t vertest_stub_states[256];
static int vertest_stub_count = 0;

static vertest_stub_state_t* vertest_find_stub(const char* name) {
    for (int i = 0; i < vertest_stub_count; i++) {
        if (strcmp(vertest_stub_states[i].name, name) == 0)
            return &vertest_stub_states[i];
    }
    return NULL;
}

void vertest_register_stub(const char* name) {
    if (vertest_find_stub(name)) return;
    if (vertest_stub_count < 256) {
        vertest_stub_states[vertest_stub_count].name = name;
        vertest_stub_states[vertest_stub_count].current = 0;
        vertest_stub_states[vertest_stub_count].configured_count = 0;
        vertest_stub_count++;
    }
}

void vertest_configure_stub_return(const char* name, int value) {
    vertest_stub_state_t* s = vertest_find_stub(name);
    if (!s) {
        vertest_register_stub(name);
        s = vertest_find_stub(name);
    }
    if (s && s->configured_count < 64) {
        s->configured_values[s->configured_count++] = value;
    }
}

void vertest_reset_all_stubs(void) {
    vertest_stub_count = 0;
}

int vertest_stub_return_int(const char* func_name, int default_val) {
    vertest_stub_state_t* s = vertest_find_stub(func_name);
    if (s && s->current < s->configured_count) {
        int val = s->configured_values[s->current];
        s->current++;
        return val;
    }
    return default_val;
}
"""


class StubGenerator:
    """Generates C stub functions for external dependencies."""

    def __init__(self, output_dir: str | Path):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate(self, functions: list[FunctionInfo]) -> tuple[Path, Path]:
        header_path = self.output_dir / "vertest_stubs.h"
        impl_path = self.output_dir / "vertest_stubs.c"
        lib_path = self.output_dir / "vertest_stub_lib.c"

        header_path.write_text(STUB_HEADER)

        impl_lines = [STUB_IMPL]
        impl_lines.append("")
        impl_path.write_text("\n".join(impl_lines))

        lib_lines = [
            '/* Auto-generated stub implementations by VeriTest */',
            '#include "vertest_stubs.h"',
            '',
        ]
        for i, func in enumerate(functions):
            stub = self._generate_stub(func, i)
            lib_lines.append(stub)
            lib_lines.append("")

        lib_path.write_text("\n".join(lib_lines))
        return header_path, lib_path

    def _generate_stub(self, func: FunctionInfo, idx: int) -> str:
        params = func.parameters
        return_type = func.return_type or "void"

        stub_name = f"stub_{func.name}"
        param_list = ", ".join(
            f"{p.type_name} {'*' if p.is_pointer else ''}{p.name}"
            for p in params
        )
        call_param_list = ", ".join(p.name for p in params)

        lines = [
            f"/* Stub for {func.name} */",
            f"static int {stub_name}_call_count = 0;",
            f"static int {stub_name}_config_count = 0;",
            f"static int {stub_name}_config_values[64];",
            "",
            f"void {stub_name}_configure(int return_value) {{",
            f"    if ({stub_name}_config_count < 64) {{",
            f"        {stub_name}_config_values[{stub_name}_config_count++] = return_value;",
            f"    }}",
            f"}}",
            "",
            f"int {stub_name}_call_count_get(void) {{",
            f"    return {stub_name}_call_count;",
            f"}}",
            "",
        ]

        if return_type == "void":
            lines.extend([
                f"{return_type} {func.name}({param_list}) {{",
                f"    (void)sizeof({call_param_list or '0'});",
                f"    {stub_name}_call_count++;",
                f"}}",
            ])
        else:
            lines.extend([
                f"{return_type} {func.name}({param_list}) {{",
                f"    (void)sizeof({call_param_list or '0'});",
                f"    {stub_name}_call_count++;",
                f"    if ({stub_name}_config_count > 0) {{",
                f"        return ({return_type}){stub_name}_config_values[--{stub_name}_config_count];",
                f"    }}",
                self._default_return(return_type),
                f"}}",
            ])

        return "\n".join(lines)

    @staticmethod
    def _default_return(return_type: str) -> str:
        rt = return_type.strip().rstrip("*")
        if rt in ("int", "short", "long", "char", "signed", "unsigned",
                   "size_t", "int32_t", "uint32_t", "int16_t", "uint16_t",
                   "int8_t", "uint8_t", "int64_t", "uint64_t", "bool", "_Bool"):
            return "    return 0;"
        elif rt in ("float", "double", "long double"):
            return "    return 0.0;"
        elif rt.endswith("*"):
            return "    return NULL;"
        else:
            return "    return 0;"

    @staticmethod
    def _map_type_to_return(t: str) -> str:
        t = t.strip()
        if t in ("int", "long", "short", "char", "size_t", "int32_t", "bool", "_Bool"):
            return "int"
        elif t in ("float", "double", "long double"):
            return "double"
        elif t.endswith("*"):
            return "pointer"
        return "int"
