/* universes.js — registro multiverso + Sakura Eterna (U-2) */
(function () {
'use strict';
/* --- personaggi U-2 (senza spoiler sui finali) --- */
const SCHARACTERS = [
  { name: 'Hana viva', role: 'nonna · 70 anni', desc: 'Gestisce ancora il locale. Burbera, tenera, e convinta che tu sia una ladra di vapore.' },
  { name: 'Aoi bambina', role: 'tu a 8 anni', desc: 'Ti ruba il chasen il primo giorno. Devi insegnarle a frullare senza piangere.' },
  { name: 'Il Giardiniere', role: 'mistero · notte', desc: 'Annaffia solo di notte. Conosce il tuo nome. Tu non conosci il suo.' },
];
try {
  if (window.MHStory && Array.isArray(window.MHStory.CHARACTERS)) {
    SCHARACTERS.forEach(c => {
      if (!window.MHStory.CHARACTERS.some(x => x.name === c.name)) window.MHStory.CHARACTERS.push(c);
    });
  }
} catch {}
/* --- fili (sottotrame U-2 con progresso) --- */
const THREADS = [
  { id: 'giardiniere', name: 'Il Giardiniere senza nome', icon: '🌙',
    hints: ['Annaffia solo di notte.', 'Conosce il tuo nome. Tu no il suo.', 'Le sue mani sanno di pioggia.', 'Canticchia la canzone di Hana.', 'Sotto il cappello: guarda bene.'] },
  { id: 'ricetta', name: 'La ricetta perduta', icon: '📜',
    hints: ['Hana ha dimenticato il koicha del ’64.', 'Solo le tue mani ricordano.', 'Il ’64 sa di ombrello di carta.', 'Insegnare è servire due volte.', 'La ricetta torna a casa.'] },
  { id: 'aoi-bimba', name: 'Aoi bambina', icon: '🎀',
    hints: ['Ti ha rubato il chasen.', 'Frulla troppo forte, come te.', 'Ha la febbre. Come te.', 'Tienile la fronte.', 'Promettile una cosa sola.'] },
];
const T = (t, c, m, mini, bias = -1, mech = null, quota = 0) => ({ moves: m, targetTile: t, targetCount: c, biasTile: bias, mini, mechanic: mech, quota });
const SCHAPTERS = [
  { n: 'S1', title: 'La mattina sbagliata', desc: 'Ti svegli in un mondo dove Hana non è mai morta. Nessuno ti riconosce. Tranne Mugi.', eps: ['s1', 's2', 's3', 's4', 's5'] },
  { n: 'S2', title: 'Potatura', desc: 'Insegnare alla nonna, curare la bambina, potare il passato. Poi scegliere il mattino.', eps: ['s6', 's7', 's8', 's9', 's10'] },
  { n: 'S3', title: 'Radici Profonde', desc: 'Il mondo del sogno continua anche da sveglia. La bambina cresce, il Giardiniere parla di più.', eps: ['s11', 's12', 's13', 's14', 's15'] },
  { n: 'S4', title: 'Il Seme', desc: 'Piantate qualcosa insieme. Quello che cresce non è quello che avete seminato.', eps: ['s16', 's17', 's18', 's19', 's20'] },
  { n: 'S5', title: 'Petali Sopra', desc: 'Il sogno chiede il conto. Le schiume più alte, le scelte più vere.', eps: ['s21', 's22', 's23', 's24', 's25'] },
];
const SSTORY = [
{id:'s1',chap:'S1',ep:1,kicker:'Sak.1-1 · Risveglio',title:'Il locale sbagliato',text:`Ti svegli sul tatami del retrobottega. Profumo di legna e sakura. Dal bancone, una voce impossibile: Hana, settantenne, schiena dritta, che frulla e brontola.\n\n"Tu chi sei? E quello cos'è?" indica Mugi, che hai nella borsa. Mugi ringhia — non a lei. Al suo stesso riflesso: sul bancone c'è un altro chasen, identico, fermo.\n\nLe tue mani tremano. Le sue no. Il mondo è quello giusto con una cucchiaiata di troppo.`,cliff:`Hana ti squadra: "Hai le mie mani. Spiegami. Dopo aver lavato le tazze."`,choiceA:{label:'«Sono tua nipote. Da un’altra pioggia.»',effect:'coraggio'},choiceB:{label:'Lavi le tazze in silenzio',effect:'dolcezza'},level:T(0,12,26,'awa'),letter:`Nota di Hana viva — "Chi entra senza bussare lava le tazze. Regola prima."`,ps:{coraggio:"Hai detto: sono tua nipote, e io ti ho voluto credere. Ma solo dopo le tazze: la regola non si sospende.",dolcezza:"Hai lavato le tazze in silenzio. Io non ho chiesto niente: ho guardato le mani, e sapevo da dove venivi."},threads:['giardiniere']},
{id:'s2',chap:'S1',ep:2,kicker:'Sak.1-2 · La ladra',title:'La ladra del vapore',text:`Hana ti ha ribattezzata "la ladra del vapore" e ti mette alla prova: un cliente che piange, uno yuzu che sveglia.\n\nLe tue mani sanno già tutto — le sue ricette, i suoi gesti. Lei ti guarda frullare e impallidisce: "Chi ti ha insegnato? Quella M... la faccio solo io."\n\nNon finisce la frase. Il vapore sale dritto, come a nascondervi.`,cliff:`"Domani torni. Con quel coso che ringhia," dice indicando Mugi. È quasi un invito.`,choiceA:{label:'«Tornerò. Ho molto da rubare.»',effect:'coraggio'},choiceB:{label:'«Grazie per lo yuzu.»',effect:'dolcezza'},level:T(2,14,26,'latte'),letter:`Nota di Hana viva — "Frulla come me. Sospetto come me. Indagherò."`,ps:{coraggio:"Hai detto: tornerò, ho molto da rubare. Ho cambiato le serrature due volte, e la chiave l'ho lasciata lì.",dolcezza:"Grazie per lo yuzu, hai detto. Io l'avevo messo lì apposta: è l'unico modo che conosco per sapere chi sei."},threads:['ricetta']},
{id:'s3',chap:'S1',ep:3,kicker:'Sak.1-3 · La bambina',title:'Otto anni e un chasen',text:`Una bambina di otto anni — TU a otto anni, nei vestiti della festa — ti ruba il chasen dal tavolo e scappa ridendo in giardino.\n\nLa rincorri tra i sakura in fiore. Cade, si sbuccia un ginocchio, non piange: "Nonna dice che il tè aspetta e le ginocchia no."\n\nLe insegni a frullare piano. Le sue mani tremano come le tue. Le tieni da dietro, come Hana fece con te. Il cerchio si chiude e si riapre.`,cliff:`"Resta a cena," dice la bambina. "Nonna fa il mochi. Tu sembri una che ha fame da anni."`,choiceA:{label:'Resti a cena (e piangi nel mochi)',effect:'dolcezza'},choiceB:{label:'«Devo capire dove sono.»',effect:'coraggio'},level:T(0,15,26,'awa'),letter:`Disegno della bambina — tu grande dentro una tazza, con scritto "la ladra buona".`,ps:{dolcezza:"Se sei restata a cena, hai pianto nel mochi. Ho fatto finta di niente: è la seconda volta che ti vedo.",coraggio:"Hai detto: devo capire dove sono. Io ti ho dato il chasen lo stesso: capire può aspettare, le mani no."},threads:['aoi-bimba']},
{id:'s4',chap:'S1',ep:4,kicker:'Sak.1-4 · Notte',title:'Il Giardiniere',text:`Di notte il giardino profuma diverso. Un uomo col cappello di paglia annaffia i sakura a lume di lanterna.\n\n"Annaffio quando nessuno guarda. I fiori sono timidi." Ti chiama per nome. Aoi. Tu non glielo hai mai detto.\n\n"Qui tutti sanno il tuo nome," sorride senza voltarsi. "È il resto che non sappiamo." Canticchia la canzone che Hana canta frullando.`,cliff:`Sparisce tra gli alberi prima che tu possa chiedere. Resta una pozzanghera a forma di ombrello.`,choiceA:{label:'Lo segui tra gli alberi',effect:'coraggio'},choiceB:{label:'Resti con la pozzanghera',effect:'dolcezza'},level:T(3,15,25,'respiro'),letter:`Foglia secca — sul retro, grafia ignota: "Di notte i nomi pesano meno."`,ps:{coraggio:"Hai seguito tra gli alberi, e le piante si sono aperte. Io, la mattina dopo, ho trovato le tue scarpe bagnate.",dolcezza:"Se sei restata con la pozzanghera fino a mezzanotte, era una mappa. Io l'ho vista e ho pensato: è già di casa."},threads:['giardiniere']},
{id:'s5',chap:'S1',ep:5,kicker:'Sak.1-5 · Soglia',title:'La lettera mai scritta',text:`Hana ti chiama all’alba, stravolta. Sul bancone: una lettera con la SUA grafia, che lei giura di non aver mai scritto.\n\n"Qualunque tazza sceglierai, io sarò nel vapore. H."\n\nÈ la lettera 25. La tua. Del tuo mondo. "Spiegami," dice Hana, e per la prima volta la sua voce trema. "Subito. Ti prego."\n\nLe racconti tutto: la morte, il debito, Takeshi, la pioggia. Lei ascolta senza interrompere, poi ti abbraccia come solo le nonne sanno.`,cliff:`"Allora resti," dice. "Finché non capiamo. E intanto mi insegni quel koicha che non ricordo più."`,choiceA:{label:'«Resto. E ti insegno tutto.»',effect:'dolcezza'},choiceB:{label:'«Resto. Ma ho paura.»',effect:'coraggio'},level:T(1,16,26,'latte'),letter:`Lettera impossibile — la 25, qui, adesso. Il vapore sa viaggiare.`,ps:{dolcezza:"Hai detto: resto, e ti insegno tutto. Ho iniziato dal koicha del '64: era l'unico che non ricordavo.",coraggio:"Hai detto: resto, ma ho paura. Io avevo paura anche. Solo che la mia era di essere quella che resta."},threads:['ricetta']},
{id:'s6',chap:'S2',ep:1,kicker:'Sak.2-1 · Ricetta',title:'Il koicha del ’64',text:`Hana viva ha dimenticato la ricetta del koicha del 1964 — quella di lei ventenne e Takeshi ragazzo. Proprio quella che tu conosci a memoria.\n\nGliela insegni cucchiaio dopo cucchiaio. Lei, la maestra, prende appunti come una scolara. Ogni tanto ride: "Ma io ero così brava?"\n\n"Sì, nonna. Eri così."`,cliff:`Assaggia, chiude gli occhi: "È lui. È esattamente lui. Come fai a saperlo?"`,choiceA:{label:'«Me l’ha insegnato tu. Altrove.»',effect:'dolcezza'},choiceB:{label:'«Le mani ricordano.»',effect:'coraggio'},level:T(2,17,27,'latte'),letter:`Appunti di Hana — "Il ’64: denso, amaro, due mochi. Come l’amore vero."`,ps:{dolcezza:"Hai detto: me l'ha insegnato tu, altrove. La stessa mano, due mondi: con certe cose non serve parlare.",coraggio:"Hai detto: le mani ricordano. Ti ho guardata frullare e ho pensato che le avessi viste in un sogno, ieri."},threads:['aoi-bimba']},
{id:'s7',chap:'S2',ep:2,kicker:'Sak.2-2 · Specchio',title:'Febbre allo specchio',text:`La bambina ha la febbre a 39. Febbre a 39. Come te nel Cap.3-3, ma stavolta sei TU quella con la mano sulla fronte.\n\nHana vuole tenere aperto. Tu vuoi chiudere. Litigate per amore — litigate IDENTICA a quella con Ren, e ridi piangendo a metà frase.\n\nHana ti guarda strano: "Ridi?" "Scusa. Déjà-vu."`,cliff:`La bambina dorme. Hana dorme sulla sedia. Tu vegli entrambe, chasen in mano come una spada.`,choiceA:{label:'Vegli tutta la notte',effect:'coraggio'},choiceB:{label:'Canti piano come Hana',effect:'dolcezza'},level:T(5,17,27,'respiro'),letter:`Termometro — 36.8 al mattino. "Le nonne guariscono tutto. Anche le nipoti impossibili."`,ps:{coraggio:`Sono sveglia anch'io, dall'altra parte della stanza. Non ti vegliavo: vegliavamo in due. Riposa.`,
        dolcezza:`Se le hai cantato piano, l'ha sentito tutta la casa. Io cantavo così a tua madre. È ereditario.`},threads:['giardiniere']},
{id:'s8',chap:'S2',ep:3,kicker:'Sak.2-3 · Duello',title:'Duello madre-figlia',text:`Hana ti sfida a duello di schiuma: nonna contro nipote venuta dal futuro, Yuki-bambina-no — qui il giudice è Aoi bambina con palette da 1 a 10.\n\n"Vediamo se nel tuo mondo frullano o solo piangono." Tre tazze a testa, sakura che nevica nel giardino.\n\nPareggio, ovviamente. La bambina alza due 10. Hana sbuffa: "Comprata." E ti abbraccia forte.`,cliff:`"Qualunque mondo sia il tuo," sussurra Hana, "lì mi manchi. Lo sento."`,choiceA:{label:'«Anche tu mi manchi. Sempre.»',effect:'dolcezza'},choiceB:{label:'«Tornerò a trovarti. Promesso.»',effect:'coraggio'},level:T(0,18,27,'awa'),letter:`Palette della bambina — due 10 e un cuore disegnato sopra.`,ps:{dolcezza:"Hai detto: anche tu mi manchi, sempre. Io e la bambina abbiamo fatto metà e metà: due '10' sul foglio.",coraggio:"Hai detto: tornerò a trovarti, promesso. Ho risposto: porta la bambina. Una promessa con qualcuno dentro pesa."},threads:['ricetta']},
{id:'s9',chap:'S2',ep:4,kicker:'Sak.2-4 · Potatura',title:'Il sakura vecchio',text:`Il Giardiniere pota il grande sakura del giardino. Lo guardi lavorare: ogni taglio è una carezza.\n\n"Ho piantato quest’albero il giorno dell’apertura. Avevo la tua età." Sessant’anni fa. Ma lui non ne dimostra quaranta.\n\n"Chi sei?" chiedi. Alza il cappello quel tanto che basta: un sorriso che conosci, occhi color tè freddo. Il cappello torna giù. "Il giardiniere."`,cliff:`Quella notte piove — qui piove piano, profuma di sakura. Domani dovrai scegliere.`,choiceA:{label:'«Resta. Ti prego, resta.» (a lui? al mondo?)',effect:'dolcezza'},choiceB:{label:'Prepari lo zaino in silenzio',effect:'coraggio'},level:T(3,19,28,'respiro'),letter:`Petalo potato — "Potare non è tagliare. È scegliere cosa fiorisce."`,ps:{dolcezza:"Hai detto: resta, ti prego. Io ho potato il ramo che ombrava il tè e ho lasciato stare: potare è anche questo.",coraggio:"Hai preparato lo zaino in silenzio. Io ho fatto il tè come se niente fosse: il tè serve anche per tacere."},threads:['aoi-bimba']},
{id:'s10',chap:'S2',ep:5,kicker:'Sak.2-5 · Mattino',title:'Scegli il mattino',text:`Alba rosa. Hana, la bambina, il Giardiniere (da lontano), Mugi che non ringhia più al suo doppio — ci gioca.\n\nHana ti porge una tazza: dentro, schiuma perfetta con un cuore. "L’hai fatta tu, stanotte, dormendo. Le mani sognano, a quanto pare."\n\nLa bevi. Sa di tutti i mattini possibili. Ora scegli in quale svegliarti domani.`,cliff:`Il vapore sale. Dritto nel tuo mondo — o in cerchio, qui. Il chasen non trema più.`,choiceA:{label:'🌸 RADICE SOGNATA — resto qui, nipote ritrovata',effect:'finale-radice-sognata'},choiceB:{label:'🌧️ PIOGGIA VERA — mi sveglio, e porto tutto con me',effect:'finale-pioggia-vera'},level:T(2,20,28,'latte'),letter:`Ultimo petalo — "Qualunque mattino sceglierai, io sarò nel vapore. H. (tutte le H.)"`,finaleNote:'Ultima scelta di Sakura Eterna: RESTARE nel sogno o SVEGLIARSI con tutto nel cuore. 🌸',threads:['giardiniere','ricetta','aoi-bimba']},
/* S3 — Radici Profonde */
{id:'s11',chap:'S3',ep:1,kicker:'Sak.3-1 · Ritorno',title:'Il sogno continua',text:`Dopo la scelta del mattino — qualunque sia stata — il sogno non finisce: continua di lato, come un fiume che si sdoppia. Hana viva ti aspetta al bancone come ogni mattina.\n\n"Hai dormito male. Hai parlato nel sonno. Dicevi 'pioggia'." Le sorridi: "Sognavo un altro locale. Uguale a questo, ma bagnato."\n\nLa bambina è cresciuta di un’estate: ti arriva alla spalla, frulla quasi bene. Mugi gioca col suo doppio senza più ringhiare.`,cliff:`Il Giardiniere lascia sulla porta un sacchetto di semi: "Piantali con lei. È ora."`,choiceA:{label:'Piantate i semi con la bambina',effect:'dolcezza'},choiceB:{label:'Chiedi prima cosa sono',effect:'coraggio'},level:T(0,18,27,'awa',-1,'bloom'),letter:`Sacchetto di semi — senza etichetta. Solo un fiocco rosa.`,ps:{dolcezza:"Avete piantato i semi con la bambina, sporche di terra in due. Io guardavo dalla porta e non ho detto niente.",coraggio:"Hai chiesto prima cosa sono: semi. Ti ho risposto solo quello, perché le domande vere vanno una alla volta."},threads:['aoi-bimba']},
{id:'s12',chap:'S3',ep:2,kicker:'Sak.3-2 · Quaderno',title:'Il quaderno delle due',text:`Tu e Hana iniziate un quaderno condiviso: lei scrive le ricette che ricorda, tu quelle che sai dal futuro. A pagina 10 le grafie si confondono.\n\n"Questa l’ho scritta io o tu?" ride Hana. "Tutte e due. Come tutto, qui."\n\nLa bambina ci disegna sopra: una tazza con due manici. "Così la teniamo insieme senza litigare."`,cliff:`A pagina 20 trovate una ricetta che nessuna delle due ha scritto: koicha del ’64, grafia del Giardiniere.`,choiceA:{label:'«Lui sa. Dobbiamo chiedergli.»',effect:'coraggio'},choiceB:{label:'Copiate la ricetta in silenzio',effect:'dolcezza'},level:T(2,18,27,'latte',-1,'bloom'),letter:`Pagina 20 — il ’64 in grafia ignota. Il quaderno sa più di voi.`,ps:{coraggio:"Hai detto: lui sa, dobbiamo chiedergli. Io ti ho dato la penna: certe domande vanno scritte, non dette.",dolcezza:"Avete copiato la ricetta in silenzio: una settimana nessuno ha detto niente. Il silenzio, con me, lo capisci."},threads:['ricetta']},
{id:'s13',chap:'S3',ep:3,kicker:'Sak.3-3 · Pioggia qui',title:'Piove anche nei sogni',text:`Per la prima volta, piove anche a Sakura Eterna. Pioggia vera, grigia, rumorosa. Hana la guarda dalla vetrina come un’estranea.\n\n"Da voi piove sempre?" chiede piano. "Quasi sempre." "E si vive lo stesso?" "Si vive di più, forse."\n\nIl Giardiniere non annaffia: sta fermo sotto la pioggia col cappello in mano. Per la prima volta lo vedi in faccia da lontano: sorride come Takeshi nelle foto vecchie.`,cliff:`La pioggia smette all’improvviso, come spenta. Lui rimette il cappello.`,choiceA:{label:'Gli porti un tè caldo sotto la pioggia',effect:'dolcezza'},choiceB:{label:'«Chi sei?» — stavolta davvero',effect:'coraggio'},level:T(3,19,27,'respiro',-1,'bloom'),letter:`Goccia su vetro — la bambina ci disegna intorno un ombrello.`,ps:{dolcezza:"Gli hai portato il tè caldo sotto la pioggia. Non ha chiesto come lo sapevi: ha bevuto, e basta.",coraggio:"Hai chiesto: chi sei, stavolta davvero. Io taccio: certe domande si fanno due volte, la terza in giardino."},threads:['giardiniere']},
{id:'s14',chap:'S3',ep:4,kicker:'Sak.3-4 · Febbre due',title:'La maestra bambina',text:`La bambina ora insegna a FRULLARE a un bambino del vicinato, con le tue stesse parole: "Il cuore va mosso a cerchi." La guardi e ti manca il fiato: stai guardando te stessa diventare Hana.\n\nHana viva ti stringe il braccio: "Vedi? Il cerchio non si rompe. Si allarga."\n\nQuella sera la bambina ti chiede: "Quando sarò grande come te, mi ricorderò di te?" Non sai cosa rispondere. Dici la verità: "Spero di sì. Io mi ricordo di te da sempre."`,cliff:`Lei annuisce seria, poi ride e ti sporca il naso di schiuma. Patto sigillato.`,choiceA:{label:'Patto di schiuma (naso sporco anche lei)',effect:'dolcezza'},choiceB:{label:'Le prometti di tornare ogni sogno',effect:'coraggio'},level:T(1,19,27,'awa',-1,'bloom'),letter:`Naso di schiuma — foto mentale da tenere per sempre.`,ps:{dolcezza:"Patto di schiuma, naso sporco. Lei ha sporcato anche me: due macchie sulla stessa foto, ed è giusto così.",coraggio:"Le hai promesso di tornare ogni sogno. L'ho sentito da due stanze: torni ogni mattina. Le promesse si onorano."},threads:['aoi-bimba']},
{id:'s15',chap:'S3',ep:5,kicker:'Sak.3-5 · Germoglio',title:'Cosa cresce',text:`I semi del Giardiniere sono germogliati: piantine che profumano di tè prima ancora di avere foglie. Hana le annusa e resta muta un minuto intero.\n\n"Queste... queste le piantava mio padre. Pensavo il seme fosse estinto." Ti guarda con occhi nuovi: "Chi ti manda, Aoi?"\n\nLe racconti del tuo mondo per la centesima volta, ma stavolta aggiungi tutto: Takeshi, la pioggia, i finali. Lei ascolta, poi dice solo: "Che fortuna, due mondi. Che fatica."`,cliff:`I germogli, nella notte, crescono di un dito. Li ha annaffiati qualcuno. Indovina chi.`,choiceA:{label:'Ringrazi il Giardiniere di notte',effect:'dolcezza'},choiceB:{label:'Monti la guardia per vederlo',effect:'coraggio'},level:T(5,20,28,'latte',-1,'bloom'),letter:`Foglia prima — la metti nel quaderno a pagina 1. Ricomincia tutto.`,ps:{dolcezza:"Hai ringraziato il Giardiniere di notte. Lui: ringrazia le foglie. Io non ho detto che ero sveglia anch'io.",coraggio:"Hai montato la guardia per vederlo, e ti sei addormentata sul verandino. Io ti ho coperta. Lui sorrideva."},threads:['ricetta']},
/* S4 — Il Seme */
{id:'s16',chap:'S4',ep:1,kicker:'Sak.4-1 · Guardia',title:'Lo vedi annaffiare',text:`Monti la guardia tutta la notte, nascosta tra i sakura. Alle tre, lui arriva con l’annaffiatoio di rame, e annaffia cantando la canzone di Hana — con le PAROLE, che nemmeno Hana ricorda più.\n\nTi scopre subito, ovviamente. "Bra Brava, sentinella. Vieni, ti insegno la seconda strofa."\n\nLa canta. Parla di un giardiniere che piantò un albero per una ragazza che sposò un altro. "Storia vera?" chiedi. "Le storie vere sono quelle che annaffi."`,cliff:`Ti regala l’annaffiatoio di rame. "È ora che lo tenga una Aoi."`,choiceA:{label:'«Raccontami la storia vera.»',effect:'coraggio'},choiceB:{label:'Annaffi con lui in silenzio',effect:'dolcezza'},level:T(2,20,27,'latte',-1,'bloom',60),letter:`Annaffiatoio di rame — pesa come un segreto ben tenuto.`,ps:{coraggio:"Hai chiesto: raccontami la storia vera. Io c'ero. Non ti ho fermata, ma ti ho fatto il tè mentre parlavi.",dolcezza:"Avete annaffiato in silenzio, e il giardino ha smesso di aspettare. Io guardavo, con il vostro nome in bocca."},threads:['giardiniere']},
{id:'s17',chap:'S4',ep:2,kicker:'Sak.4-2 · Rame',title:'Lezione di rame',text:`Con l’annaffiatoio di rame annaffi i germogli ogni mattina con la bambina. Crescono a vista d’occhio: a metà capitolo sono arbusti, a fine chissà.\n\nHana scherza: "Nel tuo mondo annaffi così anche i debiti?" "Li ho annaffiati di lacrime. Funziona meno."\n\nRidete. Poi lei diventa seria: "Aoi. Se un giorno non mi trovi al bancone, annaffia lo stesso. Le piante non sanno dei lutti." Il cuore ti cade nelle scarpe.`,cliff:`"Nonna, stai bene?" "Benissimo. Ma i sogni finiscono, piccola ladra. Anche i belli. Preparati."`,choiceA:{label:'«Non finirà. Lo impedisco.»',effect:'rabbia'},choiceB:{label:'Annaffi lo stesso, come ordinato',effect:'coraggio'},level:T(0,21,28,'awa',-1,'bloom',60),letter:`Goccia di rame — l’acqua che esce sa di monete antiche e promesse.`,ps:{rabbia:"Hai detto: non finirà, lo impedisco. Ti ho servito il tè in silenzio: non ti ho detto né sì né no.",coraggio:"Hai annaffiato come ordinato, e sei tornata anche il giorno dopo, quando non era più ordinato niente."},threads:['aoi-bimba']},
{id:'s18',chap:'S4',ep:3,kicker:'Sak.4-3 · Arbusto',title:'Il tè che non esiste',text:`Gli arbusti fanno le prime foglie: le assaggiate — sanno di un tè che non esiste in nessun mondo. Lo battezzate "Sakura Eterna", ovviamente, e ne fate tre tazze.\n\nLa prima a Hana: piange. La seconda alla bambina: ride. La terza a te: sa di pioggia E di sole insieme, impossibile e vero.\n\nIl Giardiniere rifiuta la sua: "Io li coltivo, non li bevo. Qualcuno deve restare sobrio, qui."`,cliff:`Hana propone: presentarlo al festival del mondo vero? Ma quale mondo è "vero"?`,choiceA:{label:'«Questo è vero. Ora.»',effect:'dolcezza'},choiceB:{label:'«Sono veri entrambi. Fatica doppia.»',effect:'coraggio'},level:T(3,21,27,'respiro',-1,'bloom',65),letter:`Tre foglie — una per Hana, una per la bambina, una per te. La quarta manca: è per chi legge.`,ps:{dolcezza:"Hai detto: questo è vero, ora. Ho guardato i due mondi insieme, e non ho più contato le differenze.",coraggio:"Hai detto: sono veri entrambi, fatica doppia. Io ho fatto il doppio del tè: è la mia risposta all'impossibile."},threads:['ricetta']},
{id:'s19',chap:'S4',ep:4,kicker:'Sak.4-4 · Sobrio',title:'Chi non beve',text:`Tormentata dalla frase del Giardiniere, lo affronti: perché coltiva un tè che non beve? Lui si siede — per la prima volta, si SIEDE — e ti racconta.\n\n"Ho bevuto una volta. Ho sognato una vita intera: pioggia, una nipote mai nata, un ombrello nero. Mi sono svegliato piangendo e ho deciso: mai più. Io resto sveglio, così i sogni restano vostri."\n\nCapisci tutto e niente. Gli prendi la mano: è calda. I fantasmi non hanno mani calde. O forse sì.`,cliff:`"Bevi con me, stavolta," gli dici. Lui guarda la tazza come un burrone.`,choiceA:{label:'Bevete insieme, mano nella mano',effect:'dolcezza'},choiceB:{label:'Bevi tu per primo, per fargli coraggio',effect:'coraggio'},level:T(1,22,28,'awa',-1,'bloom',65),letter:`Mano calda — prova che i giardinieri esistono davvero.`,ps:{dolcezza:"Avete bevuto insieme, mano nella mano, e un'ora nessuno ha detto niente. Io ero due tavoli più in là.",coraggio:"Hai bevuto per primo, per fargli coraggio. Lui ha bevuto dopo. È l'unico modo che funziona con chi ha paura."},threads:['giardiniere']},
{id:'s20',chap:'S4',ep:5,kicker:'Sak.4-5 · Sogno dentro',title:'Il sogno del Giardiniere',text:`Beve. Si addormenta sulla tua spalla come un bambino. E sogna ad alta voce: parla di pioggia, di una Hana giovane che ride, di una promessa sotto un ombrello di carta.\n\nSono i tuoi ricordi. O i suoi. O gli stessi, da due rive diverse dello stesso fiume.\n\nSi sveglia all’alba, sereno per la prima volta: "Allora esiste davvero, la pioggia. Pensavo di averla inventata per non sentirmi solo."`,cliff:`Da quel giorno annaffia anche di giorno. E ride. Il giardino non l’aveva mai sentito ridere.`,choiceA:{label:'«Benvenuto nel giorno.»',effect:'dolcezza'},choiceB:{label:'Gli mostri come si frulla',effect:'coraggio'},level:T(5,22,28,'latte',-1,'bloom',70),letter:`Risata del giardino — le foglie tremano tutte insieme, applauso verde.`,ps:{dolcezza:"Hai detto: benvenuto nel giorno. Da lì ha annaffiato di giorno, e ha riso. Sapevo che aspettava un permesso.",coraggio:"Gli hai mostrato come si frulla, e ha provato col cucchiaio. Ha fatto schiuma per errore: quella conta."},threads:['aoi-bimba']},
/* S5 — Petali Sopra */
{id:'s21',chap:'S5',ep:1,kicker:'Sak.5-1 · Raccolto',title:'Il primo raccolto',text:`Gli arbusti sono alberi bassi carichi di foglie di Sakura Eterna. Primo raccolto vero: lo fate tutte insieme — Hana, tu, la bambina, il Giardiniere che ride ancora.\n\nNe vengono venticinque tazze. Le numerate. La numero 1 a Hana, la 25 alla bambina. La tua quale sarà? "La prossima," dici. "Ce ne sarà sempre una prossima."\n\nHana ti guarda strano. Quello sguardo lì. Quello dei conti che tornano troppo bene.`,cliff:`"Aoi," dice piano. "Quante tazze mancano, nel tuo mondo?" Non sai rispondere.`,choiceA:{label:'«Tante. Troppe. Le servo tutte.»',effect:'coraggio'},choiceB:{label:'«Quelle giuste. Come queste.»',effect:'dolcezza'},level:T(2,22,27,'latte',-1,'bloom',70),letter:`Tazza n.13 — la tua. Sa di promesse mantenute a metà, benissimo così.`,ps:{coraggio:"Hai detto: tante, troppe, le servo tutte. Io ti ho versato la tazza n.13 e ho detto: una alla volta, ma tutte.",dolcezza:"Hai detto: quelle giuste, come queste. Io ho contato le tazze: tante quante le persone venute."},threads:['ricetta']},
{id:'s22',chap:'S5',ep:2,kicker:'Sak.5-2 · Conti',title:'I conti del sogno',text:`Hana fa i conti del sogno ad alta voce, come si fa coi debiti veri: "Ogni sogno chiede un prezzo. Il nostro qual è?"\n\nNessuno risponde. Mugi — entrambi i Mugi, ormai inseparabili — dormono intrecciati. La risposta dorme con loro: il prezzo è svegliarsi, un giorno.\n\nMa non oggi. Oggi si serve: vassoi altissimi, schiume al 75% o niente, clienti-petali che non aspettano. Il sogno chiede il conto IN schiuma.`,cliff:`Il Giardiniere paga per tutti: pota l’albero vecchio per far luce ai nuovi. Piange potando. Ride piangendo.`,choiceA:{label:'Poti con lui, in silenzio',effect:'coraggio'},choiceB:{label:'Gli tieni la scala e canti',effect:'dolcezza'},level:T(0,23,28,'awa',-1,'bloom',75),letter:`Ramo potato — lo pianti. Tra sessant’anni qualcuno chiederà chi era.`,ps:{coraggio:"Avete potato in silenzio, e le lacrime non si contano. Io ero dietro, e ho contato solo i rami: sette.",dolcezza:"Gli hai tenuto la scala e hai cantato. Lui ha potato cantando: è la cosa più difficile. Io lo sapevo già."},threads:['giardiniere']},
{id:'s23',chap:'S5',ep:3,kicker:'Sak.5-3 · Scala',title:'Tenere la scala',text:`Gli tieni la scala mentre pota e canti la seconda strofa — quella che ti ha insegnato. Lui si ferma, cesoie a mezz’aria.\n\n"La sai." "Me l’hai insegnata tu." "Non te l’ho insegnata. Te la sei ricordata." Scende dalla scala, ti guarda dritto: "Aoi. Io sono... ero... Lascia stare. L’importante è la scala. Tienila sempre, a chi pota."\n\nNon finisce la frase. Non serve. Le scale tenute sono le uniche verità.`,cliff:`Quella notte sogni la pioggia così forte che ti svegli assetata. Bevi sakura. Torni a dormire.`,choiceA:{label:'«So chi sei. Non serve dirlo.»',effect:'dolcezza'},choiceB:{label:'«Dimmelo. Voglio sentirlo.»',effect:'coraggio'},level:T(4,22,27,'respiro',4,'bloom',75),letter:`Scala tenuta — in piedi da sola, adesso. Le cose tenute stanno su.`,ps:{dolcezza:"Hai detto: so chi sei, non serve dirlo. Io ho messo la mano sulla tua, e l'ho saputo anch'io.",coraggio:"Hai detto: dimmelo, voglio sentirlo. Io l'ho detto piano, una volta sola. Poi tè, in silenzio."},threads:['aoi-bimba']},
{id:'s24',chap:'S5',ep:4,kicker:'Sak.5-4 · Penultima qui',title:'La festa dei due mondi',text:`Festa grande: inviti tutti e due i mondi — o meglio, inviti tutti QUI, e brindate ANCHE al mondo di là, con una tazza vuota per la Pioggia.\n\nHana brinda: "A mia nipote, che vive due volte e si lamenta il doppio." Risate. La bambina brinda: "Alla ladra buona!" Il Giardiniere brinda senza parole, alzando l’annaffiatoio.\n\nServi il giro più difficile di sempre: vassoi pieni, schiuma all’80%, mani che sanno. Le mani sognano E vegliano, adesso.`,cliff:`A mezzanotte il vapore si ferma a mezz’aria. Il sogno trattiene il fiato. Domani si sceglie — di nuovo, per sempre.`,choiceA:{label:'«Qualunque alba, la servo.»',effect:'coraggio'},choiceB:{label:'Ballate tutti sotto i petali',effect:'dolcezza'},level:T(3,24,28,'respiro',-1,'bloom',80),letter:`Mezzanotte ferma — il vapore sospeso sembra neve che ha cambiato idea.`,ps:{coraggio:"Hai detto: qualunque alba, la servo. Ho contato le tazze da riempire: tante quante le persone che torneranno.",dolcezza:"Avete ballato sotto i petali, e la bambina è finita sulla testa del Giardiniere. Io ho guardato: e basta."},threads:['ricetta']},
{id:'s25',chap:'S5',ep:5,kicker:'Sak.5-5 · Voto',title:'Il voto dei petali',text:`Alba doppia: sole qui, pioggia di là — le senti entrambe sulla pelle, e non fa male. Fa il solletico dell’infinito.\n\nHana, la bambina e il Giardiniere ti aspettano in giardino con due tazze: una di sakura, una d’acqua di pioggia conservata in un barattolo dal giorno che piovve qui.\n\n"Non devi scegliere il mondo," dice Hana. "Devi promettere come starci. Il voto dei petali: dillo forte." Prendi il chasen. Le mani non tremano. Non tremano in nessun mondo, ormai.`,cliff:`Bevi prima una, poi l’altra. Sanno della stessa cosa, da due rive. Il voto sale col vapore.`,choiceA:{label:'«Ci sto con tutto. Sempre.»',effect:'dolcezza'},choiceB:{label:'«Ci sto. E torno. Sempre.»',effect:'coraggio'},level:T(1,24,28,'awa',-1,'bloom',85),letter:`Voto dei petali — detto forte, udito ovunque. Anche nella Pioggia.`,ps:{dolcezza:"Hai detto: ci sto con tutto, sempre. Io ho preso una tazza da te, e l'abbiamo bevuta col vapore che saliva.",coraggio:"Hai detto: ci sto, e torno, sempre. Ho contato le volte che sei tornata: sono tutte, non ne manca una."},threads:['giardiniere']},
];
/* ================= U-3 · NOTTE YOKAI 🌙 ================= */
const YCHARACTERS = [
  { name: 'Padrona Senza Volto', role: 'locandiera · maschere', desc: 'Gestisce la locanda del Villaggio Sommerso. Presta volti a chi ha dimenticato il proprio.' },
  { name: 'Baku', role: 'mangiasogni · amico', desc: 'Tasso-tapirone che mangia solo gli incubi. Russa come un tuono gentile.' },
  { name: 'Kitsune Postino', role: 'corriere · nove code?', desc: 'Consegna lettere tra i mondi. Conosce Sōma di nome. Chissà perché sorride.' },
];
try {
  if (window.MHStory && Array.isArray(window.MHStory.CHARACTERS)) {
    YCHARACTERS.forEach(c => {
      if (!window.MHStory.CHARACTERS.some(x => x.name === c.name)) window.MHStory.CHARACTERS.push(c);
    });
  }
} catch {}
const YTHREADS = [
  { id: 'maschera', name: 'La maschera della Padrona', icon: '🎭',
    hints: ['Presta volti, non li ruba.', 'Dietro c’è una critica famosa.', 'Stroncò Hana una volta. Pianse un anno.', 'Chiede perdono servendo.', 'Il volto vero è l’ultimo servito.'] },
  { id: 'sogni', name: 'I sogni di Baku', icon: '💤',
    hints: ['Mangia solo incubi.', 'Il tuo su Hana è il più grosso.', 'Digerire fa russare.', 'Sogna per te mentre dorme.', 'Colazione: un’alba leggera.'] },
  { id: 'lanterna', name: 'La lanterna spenta', icon: '🏮',
    hints: ['Una lanterna non si accende.', 'Aspetta il nome giusto.', 'I nomi veri scottano.', 'Dillo piano, di notte.', 'Luce per tornare.'] },
];
const YCHAPTERS = [
  { n: 'Y1', title: 'Il Villaggio Sommerso', desc: 'Tè ti guida oltre il cancello del tempio, a mezzanotte. Di là è sempre notte fonda.', eps: ['y1', 'y2', 'y3', 'y4', 'y5'] },
  { n: 'Y2', title: 'La Parata delle Lanterne', desc: 'Sfilata di spiriti, maschere e bancarelle. Il tuo banco del tè è l’unico per vivi.', eps: ['y6', 'y7', 'y8', 'y9', 'y10'] },
  { n: 'Y3', title: 'Il Teatro Vuoto', desc: 'Metti in scena la storia di Hana e Takeshi per chi non dorme mai. Le più dure.', eps: ['y11', 'y12', 'y13', 'y14', 'y15'] },
];
const YSTORY = [
{id:'y1',chap:'Y1',ep:1,kicker:'Yok.1-1 · Cancello',title:'Tè oltrepassa',text:`Mezzanotte al tempio. Tè fissa il cancello di pietra e miagola una volta — il cancello si apre su scale che scendono. Sotto: un villaggio intero sotto una luna fissa, bancarelle accese, profumo di tè e muschio.\n\n"Chi entra col gatto è ospite," dice una voce senza volto. "Chi entra senza tè è cena. Tu hai entrambi, vedo." Una locandiera senza lineamenti ti porge una maschera neutra: "Per le prime ore. Poi scegli la tua."\n\nMugi trema nella borsa. Gli sussurri: "Anch’io."`,cliff:`Sulla locanda, un’insegna: "A chi serve di notte, la notte serve."`,choiceA:{label:'Indossi la maschera neutra',effect:'coraggio'},choiceB:{label:'«Resto a faccia scoperta.»',effect:'dolcezza'},level:T(1,15,25,'latte',-1,'ink'),letter:`Maschera neutra — liscia come un "ciao" non detto.`,ps:{coraggio:"La maschera indossata pesa come un debito gentile: si restituisce con un inchino, e il viso torna suo.",dolcezza:"Restare a faccia scoperta costa quanto una maschera, e dice una cosa sola: questa faccia resta, e basta."},threads:['maschera']},
{id:'y2',chap:'Y1',ep:2,kicker:'Yok.1-2 · Locanda',title:'La Padrona',text:`La Padrona Senza Volto ti assume al banco del tè: sei l’unica viva nel raggio di tre sogni, e i vivi fanno la schiuma migliore — "sa di sveglia".\n\nIl vassoio, però, si macchia da solo: inchiostro vivo che avanza ogni tre mosse e inghiotte le tessere. Lo pulisci coi match vicini, in fretta, ridendo per non piangere.\n\n"Bra Brava," dice la Padrona. "Hana faceva così. Veloce e allegra." Si blocca: "Hana... perché ho detto Hana?"`,cliff:`Dietro il bancone, una vecchia recensione ingiallita: stroncatura di un chashitsu, firmata con un nome famoso.`,choiceA:{label:'Leggi la firma',effect:'coraggio'},choiceB:{label:'La rimetti a posto senza leggere',effect:'dolcezza'},level:T(3,16,26,'respiro',-1,'ink'),letter:`Macchia pulita — l’inchiostro sa di sampietrini bagnati.`,ps:{coraggio:"La firma si legge una volta sola: poi diventa una macchia, e le macchie non si riutilizzano.",dolcezza:"Rimetterla a posto senza leggere è l'unico modo di tenere una locanda: la verità aspetta, l'inchiostro no."},threads:['sogni']},
{id:'y3',chap:'Y1',ep:3,kicker:'Yok.1-3 · Firma',title:'La critica',text:`La firma è di una critica gastronomica temutissima, ritiratasi dopo aver stroncato — per invidia, ammise anni dopo — proprio il chashitsu Hana. Hana le rispose invitandola a bere. Diventarono quasi amiche.\n\n"Ho passato trent’anni a prestare volti," dice la Padrona, "perché col mio avevo fatto male." Ti porge la maschera più bella: "Tienla. Tu il volto lo usi bene."\n\nRifiutarla sarebbe crudele. Accettarla, un patto. Prendi la maschera e le prometti una tazza all’alba.`,cliff:`"All’alba non ci sono mai," ride lei. "Ma la tazza lasciala lo stesso."`,choiceA:{label:'«L’alba ti troverà.»',effect:'dolcezza'},choiceB:{label:'«Allora bevo io per due.»',effect:'coraggio'},level:T(0,17,26,'awa',-1,'ink'),letter:`Maschera bella — pesa come un perdono accettato.`,ps:{dolcezza:"L'alba non trova nessuno, al Villaggio: prende in prestito un'ora e lascia il debito aperto.",coraggio:"Bere per due è la regola del villaggio: la tazza raddoppia, la notte no, e il sonno si divide."},threads:['lanterna']},
{id:'y4',chap:'Y1',ep:4,kicker:'Yok.1-4 · Russare',title:'Baku',text:`Sotto il tuo banco dorme un tasso grosso come un armadio: Baku, mangiasogni. Russa così forte che le tazze tremano — e i clienti adorano il "sottofondo".\n\n"Diglielo, il tuo incubo," suggerisce la Padrona. "Quello con Hana che chiama e tu non trovi la porta." Come fa a saperlo? Qui i sogni si sentono russare attraverso i muri.\n\nGlielo racconti tutto d’un fiato. Baku, dormendo, allunga una zampa e ti accarezza la caviglia. Il russare cambia tono: sta masticando.`,cliff:`Ti svegli — avevi dormito in piedi? — più leggera di tre notti.`,choiceA:{label:'«Grazie, Baku. Tieni il resto.»',effect:'dolcezza'},choiceB:{label:'Gli lasci un mochi sul naso',effect:'coraggio'},level:T(2,17,26,'latte',-1,'ink'),letter:`Mochi mangiato — dal naso in su, senza svegliarsi. Talento.`,ps:{dolcezza:"Grazie si dice una volta sola al tasso, e il resto si tiene per la notte: è il suo stipendio.",coraggio:"Un mochi sul naso è l'unico inchino che Baku accetta: riceve omaggi solo da sopra, e dorme meglio."},threads:['maschera']},
{id:'y5',chap:'Y1',ep:5,kicker:'Yok.1-5 · Kitsune',title:'Posta tra mondi',text:`Un volpacchiotto col berretto da postino inciampa nel tuo banco: è il Kitsune Postino, corriere tra i mondi. "Lettera per... Aoi? Ne ho tre, di Aoi diverse. Rete pessima, qui."\n\nUna è per te: mittente Sōma, mondo Pioggia. "Il nipote ha fatto il giro da solo. Pensavo ti facesse piacere saperlo. Il tuo tè manca anche qui sotto."\n\nPiangi ridendo. Il Kitsune finge di guardare altrove e ti lascia un biscotto a forma di luna.`,cliff:`"Se mai vuoi spedire SOGNI," dice, "io li porto. I sogni pesano meno delle lettere."`,choiceA:{label:'Spedisci un sogno a Hana',effect:'dolcezza'},choiceB:{label:'Spedisci un incubo a Baku (da mangiare)',effect:'coraggio'},level:T(5,18,27,'respiro',-1,'ink'),letter:`Biscotto-luna — sa di burro e di posta arrivata.`,ps:{dolcezza:"Un sogno spedito a Hana pesa meno di una lettera, e arriva in tre giorni: i sogni viaggiano meglio di notte.",coraggio:"L'incubo spedito a Baku si mangia in piedi, e il tasso ringrazia con un rombo. Poi dorme leggero."},threads:['sogni']},
{id:'y6',chap:'Y2',ep:1,kicker:'Yok.2-1 · Parata',title:'La sfilata',text:`Notte di parata: cento spiriti sfilano con lanterne, il tuo banco è l’unica tappa "per vivi e stanchi". Servi senza fermarti mentre tutto sfila.\n\nTra i carri, uno fermo: sopra, una lanterna SPENTA con sopra scritto il tuo nome. Aoi. La tua grafia? No: quella di Hana.\n\nLa Padrona impallidisce — cosa impossibile senza volto, eppure succede: "Quella lanterna aspetta da sessant’anni. Non toccarla finché non sai il perché."`,cliff:`Il carro riparte da solo. La lanterna spenta ti segue con lo sguardo. Le lanterne non hanno occhi. Questa sì.`,choiceA:{label:'La segui tra la folla',effect:'coraggio'},choiceB:{label:'Torni al banco (il dovere prima)',effect:'dolcezza'},level:T(1,19,27,'awa',-1,'ink'),letter:`Coriandolo di parata — a forma di piccole lune. Ne tieni una manciata.`,ps:{coraggio:"Seguire la lanterna nella folla costa il turno intero: si torna con i piedi sporchi e gli occhi aperti.",dolcezza:"Tornare al banco prima che la sfilata finisca è il dovere, e il dovere al Villaggio non si negozia."},threads:['lanterna']},
{id:'y7',chap:'Y2',ep:2,kicker:'Yok.2-2 · Nome',title:'Il nome che scotta',text:`Baku ti spiega le lanterne spente, russando a metà: "Aspettano il nome vero di qualcuno. I nomi veri scottano, per questo nessuno li dice... e le lanterne restano spente... ronf..."\n\nIl tuo nome, sulla lanterna, è scritto da Hana. Quale nome aspetta, allora? Il tuo? Il suo? Quello del Giardiniere, che qui tutti conoscono e nessuno nomina?\n\nServi il turno più tosto finora: inchiostro che corre, schiuma al 60% o la parata ti fischia. Le mani sanno. Le mani sanno sempre, ormai.`,cliff:`A fine turno la lanterna è più vicina. Non l’hai vista muoversi. Nessuno l’ha vista muoversi.`,choiceA:{label:'«Il mio nome è Aoi. Accenditi.»',effect:'coraggio'},choiceB:{label:'Le offri tè invece di nomi',effect:'dolcezza'},level:T(0,20,27,'latte',-1,'ink',60),letter:`Fischio di parata — in realtà erano applausi. Gli spiriti fischiano ridendo.`,ps:{coraggio:"Il nome è la chiave e la lanterna la usa: detta una volta sola, e per un attimo il villaggio è illuminato.",dolcezza:"Il tè, alla lanterna, si offre senza nome: bere insieme non accende niente, e non è poco."},threads:['maschera']},
{id:'y8',chap:'Y2',ep:3,kicker:'Yok.2-3 · Doppio',title:'Due Aoi',text:`Nella folla vedi TE STESSA: un’altra Aoi con la maschera bella, che serve a un altro banco. Vi guardate. Vi inchinate. Nessuna delle due scappa.\n\n"Sei quella della Pioggia o quella del Sogno?" chiede lei. "Pioggia." "Io Sakura. Ci manca quella dell’Estate, poi siamo al completo." Ridete come sorelle.\n\nVi scambiate una tessera portafortuna: lei ti dà un petalo, tu le dai una goccia (di sudore, dicono i maligni; di pioggia, dici tu).`,cliff:`La lanterna spenta, lontana, sembra accendersi di un millimetro. O è la parata che abbaglia?`,choiceA:{label:'«Ci vediamo a ogni parata.»',effect:'dolcezza'},choiceB:{label:'Le chiedi del Giardiniere',effect:'coraggio'},level:T(3,20,27,'respiro',-1,'ink',60),letter:`Petalo scambiato — profuma di un mondo dove non piove mai.`,ps:{dolcezza:"Ogni parata è un appuntamento senza posto fisico: ci si vede dove finisce la musica, e ci si riconosce.",coraggio:"Del Giardiniere si può chiedere solo una cosa per notte, e le risposte non tornano mai nel posto giusto."},threads:['sogni']},
{id:'y9',chap:'Y2',ep:4,kicker:'Yok.2-4 · Teatro',title:'Il palco vuoto',text:`La Padrona ti porta al Teatro Vuoto: cinquecento posti, sipario chiuso, polvere di secoli. "Qui si raccontano storie vere a chi non dorme mai. Tocca a te, domani."\n\nDovrai mettere in scena la storia di Hana e Takeshi. Con che faccia? Con la tua, dice la Padrona, prestandoti il suo volto migliore "per le scene difficili".\n\nProvi tutta la notte col gatto Tè come unico spettatore. Lui sbadiglia alle scene tristi e fa le fusa a quelle dolci. Critico perfetto.`,cliff:`Dietro il sipario, qualcuno piange piano. Non è tristezza: è prova generale del pubblico.`,choiceA:{label:'Provi fino all’alba (che non viene)',effect:'coraggio'},choiceB:{label:'Dormi un’ora sulla spalla di Baku',effect:'dolcezza'},level:T(2,21,27,'awa',-1,'ink',65),letter:`Biglietto del Teatro — posto H-ANA, prima fila. Tuo, per sempre.`,ps:{coraggio:"Provare fino all'alba, al Teatro, è come contare le stelle: si prova, e l'alba non viene mai.",dolcezza:"Dormire un'ora sulla spalla di Baku è l'unico sonno che non chiede riscatto: lui sogna, tu riposi."},threads:['lanterna']},
{id:'y10',chap:'Y2',ep:5,kicker:'Yok.2-5 · Prove',title:'Hana e Takeshi (prove)',text:`Prove generali: racconti i sessant’anni in un’ora. Il koicha del ’64 lo prepari davvero, sul palco, e il profumo fa piangere tre file.\n\nBaku mangia gli incubi del pubblico durante l’intervallo e russa nel finale — applauso a parte. La Padrona, in platea, si toglie la maschera per la prima volta: sotto c’è un volto normale, stanco, buono.\n\n"Domani sera si va in scena," dice. "E la lanterna verrà a vedere. Lo sento."`,cliff:`La lanterna spenta è già lì, in ultima fila. Puntuale come un rimorso.`,choiceA:{label:'«Domani. Per tutti.»',effect:'coraggio'},choiceB:{label:'Le porti tè in ultima fila',effect:'dolcezza'},level:T(4,21,27,'latte',4,'ink',65),letter:`Volto della Padrona — normale, stanco, buono. Il più bello.`,ps:{coraggio:"Domani, per tutti: è la battuta che chiude le prove al Villaggio. La plateia espira, e la notte si accorcia.",dolcezza:"Portare il tè in ultima fila è l'unico posto dove la Padrona beve: il resto del teatro lo ascolta soltanto."},threads:['maschera']},
{id:'y11',chap:'Y3',ep:1,kicker:'Yok.3-1 · Sipario',title:'Si va in scena',text:`Sipario. Cinquecento spiriti. Racconti Hana ventenne e Takeshi ragazzo, l’ombrello di carta, le lettere, la guerra, i quarant’anni di carta.\n\nL’inchiostro invade il palco-vassoio come non mai: macchie ovunque, schiuma al 70% o la storia affoga. Servi e reciti insieme, mani e voce, senza rete.\n\nA metà spettacolo capisci: non stai recitando. Stai RICORDANDO per tutti loro.`,cliff:`Dalla platea, un singhiozzo collettivo. Anche i fantasmi hanno il nodo in gola, a quanto pare.`,choiceA:{label:'Continui senza guardare (voce ferma)',effect:'coraggio'},choiceB:{label:'Guardali e sorridi tra le lacrime',effect:'dolcezza'},level:T(1,22,27,'awa',-1,'ink',70),letter:`Nodo in gola — cinquecento, tutti insieme. Record del villaggio.`,ps:{coraggio:"Continuare senza guardare, con la voce ferma, è il mestiere: gli spiriti capiscono, e applaudono di più.",dolcezza:"Guardarli e sorridere tra le lacrime è come bere dal bicchiere rotto: si beve lo stesso, e con più sete."},threads:['sogni']},
{id:'y12',chap:'Y3',ep:2,kicker:'Yok.3-2 · Intervallo',title:'L’intervallo di Baku',text:`Intervallo: Baku fa il suo numero — mangia in diretta l’incubo di uno spettatore (un esame mai dato, classico) e scoreggia scintille verdi. Standing ovation.\n\nPoi tocca al tuo, di incubo: quello con Hana che chiama e tu non trovi la porta. Lo racconti al microfono invece di darmelo? Baku ti guarda: "Dillo. Poi lo mangio. Poi non c’è più."\n\nLo dici. Lui lo mangia. Rutta una stellina. Non c’è più. Non c’è davvero più — controlli, la mattina dopo, ed è vero.`,cliff:`In camerino trovi un biglietto: "Grazie per la cena. — B." Accanto, un mochi rosicchiato a forma di luna.`,choiceA:{label:'«Il prossimo lo divido con te.»',effect:'dolcezza'},choiceB:{label:'Gli affidi tutti gli incubi futuri',effect:'coraggio'},level:T(5,22,27,'respiro',-1,'ink',70),letter:`Stellina ruttata — la tieni in tasca. Pesa come niente. Vale tutto.`,ps:{dolcezza:"Il prossimo lo divido con te: all'intervallo le porzioni che restano si mettono in tasca, e durano di più.",coraggio:"Gli incubi futuri si affidano come pacchi: non si paga la consegna, si paga il coraggio di averli contati."},threads:['lanterna']},
{id:'y13',chap:'Y3',ep:3,kicker:'Yok.3-3 · Atto secondo',title:'L’atto della pioggia',text:`Secondo atto: la pioggia. Sul palco fai piovere davvero — secchi d’acqua dai ballatoi, tecnici-spirito efficientissimi. Il pubblico impazzisce di gioia: qui non piove da secoli.\n\nRacconti Takeshi sotto la pioggia vera, l’ultimo tè, l’ombrello piegato. La lanterna in ultima fila trema. Trema forte.\n\nLa schiuma deve reggere il 75% sotto la pioggia di scena. Le mani fanno da sole. Tu guardi solo la lanterna.`,cliff:`Un bagliore, dentro il vetro spento. Piccolo. Come un’alba in miniatura.`,choiceA:{label:'«Forza. Quasi.» (sottovoce)',effect:'coraggio'},choiceB:{label:'Le dedichi la scena, a voce alta',effect:'dolcezza'},level:T(0,23,28,'latte',-1,'ink',75),letter:`Goccia di scena — vera, salata, tua. La migliore.`,ps:{coraggio:"Forza, quasi: si dice al sipario, non agli attori. Al Villaggio il sipario va incoraggiato.",dolcezza:"Dedicare la scena a voce alta, in teatro, si chiama offrire il nome: e i nomi, al Villaggio, sono valuta."},threads:['maschera']},
{id:'y14',chap:'Y3',ep:4,kicker:'Yok.3-4 · Bagliore',title:'Cosa brucia',text:`Il bagliore cresce: dentro la lanterna c’è un nome che brucia piano da sessant’anni. È il nome che Hana non disse mai ad alta voce — quello vero del Giardiniere? Quello di Takeshi prima della guerra? Il tuo?\n\nLa Padrona sale sul palco — senza maschera — e dice al pubblico: "Questa storia la finiamo insieme. Ognuno dica un nome che non dice mai."\n\nCinquecento nomi sussurrati fanno più luce di cinquecento lanterne. La tua dice il suo nome ad alta voce, per tutti.`,cliff:`La lanterna si accende. Tutta. Il teatro diventa giorno per tre secondi.`,choiceA:{label:'Piangi in piedi, inchinandoti',effect:'dolcezza'},choiceB:{label:'Ridi in piedi, inchinandoti',effect:'coraggio'},level:T(3,24,28,'respiro',-1,'ink',80),letter:`Tre secondi di giorno — in tasca con la stellina. Scorta di luce.`,ps:{dolcezza:"Piangere in piedi ringrazia l'illuminazione: per tre secondi, il teatro ti restituisce il viso.",coraggio:"Ridere in piedi, inchinandandoti, è la controfigura: il giorno dura tre secondi e si festeggia come un anno."},threads:['sogni']},
{id:'y15',chap:'Y3',ep:5,kicker:'Yok.3-5 · Alba',title:'La lanterna accesa',text:`Finale: la lanterna accesa viene sul palco da sola e si posa tra le tue mani. Dentro, un biglietto con la grafia di Hana: "Per chi serve di notte. Accendi gli altri."\n\nLa Padrona ti offre il teatro: "Resta. Cantastorie residente. Pagamento: applausi e mochi." Baku russa approvando. Il Kitsune ha già pronto un contratto (diffida dei contratti dei kitsune).\n\nMa l’alba — vera, del tuo mondo — sta per sorgere. Senti il profumo di pioggia vera da sopra il cancello. Devi scegliere dove bere il prossimo tè.`,cliff:`Tè ti guarda. Mugi ti guarda. Due gatti, due mondi, una sola Aoi.`,choiceA:{label:'🏮 MASCHERA — resto cantastorie, torno a ogni luna nuova',effect:'finale-maschera'},choiceB:{label:'🌅 ALBA — torno all’alba vera con la lanterna accesa',effect:'finale-alba'},level:T(2,25,28,'awa',-1,'ink',85),letter:`Lanterna accesa — luce per tornare. O per restare. La porti comunque.`,finaleNote:'Ultima scelta della Notte Yokai: RESTARE cantastorie o TORNARE all’alba con la luce. 🏮',threads:['lanterna','maschera','sogni']},
];
const YENDINGS = {
  'finale-maschera': { title: 'Finale: MASCHERA 🏮', text: `Resti. Ogni luna nuova torni al Teatro Vuoto e racconti una storia vera: la tua, quella di Hana, quella di chiunque abbia bisogno di essere ricordato.\n\nLa Padrona ti ha dato la maschera più bella "per le scene difficili". Non la usi quasi mai. Il tuo volto basta, ormai.\n\nNel mondo di sopra è sempre notte fonda quando manchi — ma torni sempre prima che il tè si freddi. I due mondi bevono insieme, ormai. Come due tazze della stessa teiera.` },
  'finale-alba': { title: 'Finale: ALBA 🌅', text: `Torni all’alba vera con la lanterna accesa in mano. A Kyoto piove, e la pioggia sulla lanterna fa un suono che è quasi musica.\n\nAppendi la lanterna all’ingresso del chashitsu: da allora non si è mai spenta. I clienti dicono che fa luce anche di giorno. Yuki ci ha disegnato sopra una tazza.\n\nBaku ti ha lasciato un biglietto: "Se sogni male, urlami. Sento anche da sotto." Dormi benissimo, da allora. Quasi sempre.` },
};
/* ================= U-4 · MAREA D'ESTATE 🌊 ================= */
const ECHARACTERS = [
  { name: 'Umi', role: 'ragazza · mare', desc: '16 anni, non entra in acqua da quando il mare si è preso suo fratello. Ti guarda servire e impara.' },
  { name: 'Gin', role: 'faraio · faro', desc: '71 anni, ultimo guardiano del faro spento. Aspetta "la nave giusta" da quarant’anni.' },
  { name: 'Nonna Ondina', role: 'gelataia · molo', desc: 'Fa granite al tè da cinquant’anni. Dice che il freddo conserva i ricordi.' },
];
try {
  if (window.MHStory && Array.isArray(window.MHStory.CHARACTERS)) {
    ECHARACTERS.forEach(c => {
      if (!window.MHStory.CHARACTERS.some(x => x.name === c.name)) window.MHStory.CHARACTERS.push(c);
    });
  }
} catch {}
const ETHREADS = [
  { id: 'onda', name: 'L’onda di Umi', icon: '🌊',
    hints: ['Non entra in acqua.', 'Il mare si è preso suo fratello.', 'Guarda servire e impara.', 'Un piede dentro, poi l’altro.', 'Nuota. Finalmente nuota.'] },
  { id: 'faro', name: 'Il faro spento', icon: '🗼',
    hints: ['Spento da quarant’anni.', 'Gin aspetta la nave giusta.', 'Serve olio, vetro e coraggio.', 'La luce torna.', 'Per chi si è perso.'] },
  { id: 'conchiglia', name: 'La conchiglia', icon: '🐚',
    hints: ['Umi la stringe sempre.', 'Dentro c’è il mare del fratello.', 'Le conchiglie ricordano.', 'Ascoltala con lei.', 'Due mari, una sola riva.'] },
];
const ECHAPTERS = [
  { n: 'E1', title: 'Sale e Sole', desc: 'Tetto da riparare, stand estivo sulla spiaggia. Tè freddo, clienti caldi.', eps: ['e1', 'e2', 'e3', 'e4', 'e5'] },
  { n: 'E2', title: 'Il Faro', desc: 'Riaccendere una luce spenta da quarant’anni. Serve olio, vetro e coraggio.', eps: ['e6', 'e7', 'e8', 'e9', 'e10'] },
  { n: 'E3', title: "L'Ultima Onda", desc: 'Il tifone arriva. Le tazze più dure di tutti i mondi. Ratio fino a 0.93.', eps: ['e11', 'e12', 'e13', 'e14', 'e15'] },
];
const ESTORY = [
{id:'e1',chap:'E1',ep:1,kicker:'Est.1-1 · Stand',title:'Tetto rotto, mare aperto',text:`Agosto. Il tetto del chashitsu — quello ricostruito in Cap.9 — perde di nuovo, stavolta per un temporale estivo. Muratore disponibile: tra tre settimane. Soluzione di Hana (dal Diario): "Vai dove la gente ha sete."\n\nMonti uno stand sulla spiaggia: tè freddo, granite con Nonna Ondina, ombrellone rattoppato. Il primo cliente è una ragazza di sedici anni che fissa il mare senza entrarci: Umi.\n\n"Un tè freddo. Senza ghiaccio." Strano, con questo caldo. Ma i gusti strani sono ordini precisi, qui lo sai.`,cliff:`Umi stringe una conchiglia e non la molla mai. Nemmeno per bere.`,choiceA:{label:'«Senza ghiaccio. Subito.»',effect:'dolcezza'},choiceB:{label:'«Il ghiaccio aiuta. Fidati.»',effect:'coraggio'},level:T(2,19,27,'latte',-1,'gelo'),letter:`Graniglia di Ondina — "Il freddo conserva i ricordi. Anche quelli brutti."`,ps:{dolcezza:"Senza ghiaccio, subito: il primo servizio è anche il più difficile. La graniglia aspetta, e non è contenta.",coraggio:"Il ghiaccio aiuta davvero: lo dice Ondina, e una volta sola. Fidati, al molo, è parola che si usa male."},threads:['onda']},
{id:'e2',chap:'E1',ep:2,kicker:'Est.1-2 · Conchiglia',title:'Cosa c’è dentro',text:`Umi torna ogni giorno alla stessa ora. Terzo giorno, ti mostra la conchiglia: dentro, incisa col coltellino, una data e un nome — suo fratello, preso dal mare due anni fa.\n\n"Da allora non entro. Se entro, lui dov’è? Se non entrava lui..." La logica del lutto non ha maniglie. Le servi un tè e non aggiungi niente. A volte il silenzio è la schiuma migliore.\n\nOndina, passando, dice: "Le conchiglie ricordano. Ma non trattengono. Ricorda la differenza, piccola."`,cliff:`Umi ti chiede: "Tu hai mai perso qualcuno?" Pensi a Hana. Annuisci. Basta.`,choiceA:{label:'Le racconti Hana (un poco)',effect:'dolcezza'},choiceB:{label:'«Dimmi di lui.»',effect:'coraggio'},level:T(0,20,27,'awa',-1,'gelo'),letter:`Data incisa — la ricopi sul quaderno. I nomi incisi non affondano.`,ps:{dolcezza:"Hana si racconta un poco alla volta, come la marea: a Umi basta una data, e il resto va a onde.",coraggio:"Dimmi di lui: la domanda più difficile, e l'unica che si può fare. Si risponde con una data."},threads:['faro']},
{id:'e3',chap:'E1',ep:3,kicker:'Est.1-3 · Faro',title:'La luce spenta',text:`In cima al promontorio, un faro spento da quarant’anni. Il guardiano Gin, 71 anni, ci vive ancora: "Aspetto la nave giusta."\n\n"Quale nave?" "Quella che riporta mio figlio. Partì marinaio, non tornò. Il faro, spento, è la mia protesta contro il mare."\n\nGli porti tè freddo ogni sera. Lui ti racconta rotte e tempeste. Tu gli racconti Hana e Takeshi. Due attese si riconoscono dall’odore.`,cliff:`"Se il faro si riaccendesse," dice Gin, "sarebbe per qualcuno che torna. Non per chi parte."`,choiceA:{label:'«Allora riaccendiamolo.»',effect:'coraggio'},choiceB:{label:'Porti Umi a conoscerlo',effect:'dolcezza'},level:T(3,20,27,'respiro',-1,'gelo'),letter:`Mappa delle rotte — Gin te ne regala una: "Per non perderti mai."`,ps:{coraggio:"Riaccenderlo insieme costa un anno di lavoro e una notte di burrasca: Gin dice sì prima della domanda.",dolcezza:"Portare Umi a conoscerlo serve a una cosa sola: il faro smette di essere un monumento e diventa un lavoro."},threads:['conchiglia']},
{id:'e4',chap:'E1',ep:4,kicker:'Est.1-4 · Piedi',title:'Un piede dentro',text:`Porti Umi al faro. Gin le mostra le lampade, gli ingranaggi, il diario delle navi. Lei ascolta seria, poi chiede: "Se si riaccende, mio fratello lo vede, da dove è?"\n\nGin, ruvido: "Da dove è, vede tutto. Ma sì. Lo vedrebbe."\n\nQuella sera Umi bagna i piedi. Solo i piedi, sulla riva, tenendoti la mano così forte che ti resta il segno. "È freddo," ride piangendo. "Il freddo conserva i ricordi, dice Ondina. Allora li conservo bene."`,cliff:`La conchiglia, per la prima volta, resta nella borsa mentre fa il bagno ai piedi.`,choiceA:{label:'Le tieni la mano senza parlare',effect:'dolcezza'},choiceB:{label:'«Domani le caviglie.»',effect:'coraggio'},level:T(1,21,28,'awa',-1,'gelo'),letter:`Segno sulla mano — lo tieni come un braccialetto per un giorno.`,ps:{dolcezza:"Tenerle la mano senza parlare dura una mezz'ora. Il segno resta un giorno: poi il sale lo cancella.",coraggio:"Domani le caviglie: è un impegno che si prende al molo, e al molo gli impegni si onorano con la marea."},threads:['onda']},
{id:'e5',chap:'E1',ep:5,kicker:'Est.1-5 · Olio',title:'Serve olio',text:`Per riaccendere il faro serve olio speciale, vetro nuovo e un elettricista che non ha paura dei posti vecchi. Fai la colletta sulla spiaggia: i bagnanti donano, Ondina offre le granite di una settimana, Mika lancia la raccolta online.\n\nRaccolto tutto in tre giorni. Gin guarda la cifra e piange come un bambino: "Quarant’anni ad aspettare, e bastava chiedere."\n\n"Chiedere è la cosa più difficile," dici. "Dopo restare." Lui annuisce: sa di cosa parli, anche senza sapere niente.`,cliff:`L’elettricista arriva lunedì. Il vetro giovedì. L’olio... l’olio manca ancora.`,choiceA:{label:'Cercate l’olio insieme a Gin',effect:'coraggio'},choiceB:{label:'Festa intanto: granite per tutti',effect:'dolcezza'},level:T(5,21,28,'latte',-1,'gelo'),letter:`Ricevuta della colletta — firmata da mezza spiaggia.`,ps:{coraggio:"Cercare l'olio con Gin richiede due pomeriggi e una barca. La latta era dietro le reti, come sempre.",dolcezza:"Festa intanto: granite per tutti, e la ricevuta si firma da sola. Mezza spiaggia ha già il portafoglio."},threads:['faro']},
{id:'e6',chap:'E2',ep:1,kicker:'Est.2-1 · Vetro',title:'Il vetro giusto',text:`Il vetro del faro non si trova più in commercio: serve un pezzo curvo soffiato a mano. L’unico soffiatore rimasto abita a due paesi di distanza e ha smesso dieci anni fa.\n\nCi vai con Umi — che ormai entra in acqua fino alle caviglie — e lo convinci con un thermos di tè freddo e la storia di Gin. Lui piange anche lui (quest’estate piangono tutti) e riaccende la fornace.\n\nMentre il vetro si forma, pensi alle tazze: anche tu soffi vita in cose fragili, ogni giorno.`,cliff:`Il vetro riesce al secondo tentativo. Il primo si è rotto "per emozione", dice il soffiatore.`,choiceA:{label:'Paghi il doppio (vale il doppio)',effect:'dolcezza'},choiceB:{label:'Gli offri tè gratis per un anno',effect:'coraggio'},level:T(2,22,28,'latte',-1,'mix',65),letter:`Bolla nel vetro — il soffiatore l’ha lasciata apposta: "Per la luce."`,ps:{dolcezza:"Pagare il doppio per un vetro rotto una volta: il soffiatore chiama giusto il prezzo, e ha ragione.",coraggio:"Tè gratis per un anno a chi soffia il vetro del faro: l'unico modo per ripagare un mestiere."},threads:['conchiglia']},
{id:'e7',chap:'E2',ep:2,kicker:'Est.2-2 · Caviglie',title:'Le caviglie',text:`Umi entra fino alle caviglie. Poi alle ginocchia, un pomeriggio che non dimenticherai: ride, spruzza, poi si ferma e guarda l’orizzonte a lungo.\n\n"Ciao," dice piano all’acqua. Non sai a chi. Non chiedi. Le tieni l’asciugamano come si tiene una scala a chi pota.\n\nQuella sera lascia la conchiglia SUL BANCO mentre beve. Progressi. Il lutto si appoggia, ogni tanto, e respira.`,cliff:`"Domani," dice, "provo a nuotare. Tu guardami. Prometti di guardarmi."`,choiceA:{label:'«Ti guardo. Promesso.»',effect:'coraggio'},choiceB:{label:'Nuoti con lei, piano',effect:'dolcezza'},level:T(0,22,27,'awa',-1,'gelo',70),letter:`Asciugamano tenuto — secondo mestiere dopo il tè: tenere.`,ps:{coraggio:"Ti guardo, promesso: la promessa si tiene dal gradino. Umi conta i passi, e se ne manca uno si ricomincia.",dolcezza:"Nuotare con lei, piano, è la parte difficile: due persone in un metro d'acqua, e nessuna fa la capra."},threads:['onda']},
{id:'e8',chap:'E2',ep:3,kicker:'Est.2-3 · Nuoto',title:'Nuota',text:`Umi nuota. Dieci bracciate, poi torna a riva tremando e ridendo e piangendo tutto insieme — il gusto esatto dell’usucha quando manca qualcuno, ma al contrario: quando qualcuno TORNA, anche solo nell’acqua.\n\nTutta la spiaggia applaude. Ondina piange nella granita. Gin, dal faro, suona la sirena a mano: tre colpi lunghi, saluto dei ritorni.\n\nQuella sera Umi dorme sul tuo ombrellone rattoppato come fosse il letto più morbido del mondo. Forse lo è.`,cliff:`Nella sabbia, dove ha lasciato la conchiglia, resta un’impronta a forma di cuore. Casualità? No. Mai.`,choiceA:{label:'Fotografi l’impronta per lei',effect:'dolcezza'},choiceB:{label:'La lasci al mare (le cose restano)',effect:'coraggio'},level:T(3,22,27,'respiro',-1,'mix',70),letter:`Impronta-cuore — la foto va sulla mensola, accanto alla lanterna.`,ps:{dolcezza:"Fotografare l'impronta per lei serve: la sabbia si cancella, la foto no. Va accanto alla lanterna.",coraggio:"Lasciarla al mare funziona: le cose restano e ci tornano dentro. La conchiglia rientra a ogni onda."},threads:['faro']},
{id:'e9',chap:'E2',ep:4,kicker:'Est.2-4 · Sirena',title:'Tre colpi',text:`Gin ti spiega i tre colpi di sirena: uno per chi parte, due per chi torna, tre per chi è tornato DENTRO — nel senso di dentro di sé. "Umi ha avuto i suoi tre colpi."\n\nL’olio arriva finalmente: un fusto intero donato da un armatore che lesse di voi online. "Mio padre era marinaio," scrive. "Accendete anche per lui."\n\nMontate tutto in un giorno e una notte. Il faro è pronto. Manca solo... accenderlo. Gin rimanda: "Domani." Da una settimana dice domani.`,cliff:`Capisci: ha paura. Quarant’anni di attesa non si accendono con un interruttore.`,choiceA:{label:'«Accendiamo insieme. Ora.»',effect:'coraggio'},choiceB:{label:'Aspetti il suo domani (pazienza)',effect:'dolcezza'},level:T(1,23,28,'awa',-1,'gelo',75),letter:`Fusto d’olio — sopra, scritto a mano: "Anche per lui."`,ps:{coraggio:"Accendere insieme, ora: la mano di Gin copre la tua sull'interruttore. Da solo non si accende.",dolcezza:"Aspettare il suo domani è la pazienza del molo: quattro giorni, un secchio d'olio, nessuna fretta."},threads:['conchiglia']},
{id:'e10',chap:'E2',ep:5,kicker:'Est.2-5 · Interruttore',title:'Luce',text:`Lo convinci — o meglio, vi convincete: tu, Umi, Ondina, mezza spiaggia salita al faro. Gin ha la mano sull’interruttore da dieci minuti.\n\n"Al tre," dici. "Uno... due..." Lui preme al due e mezzo, perché i coraggiosi barano. LUCE. Un fascio bianco che taglia il tramonto e arriva al mare, lontano.\n\nSilenzio. Poi urla, pianti, abbracci. Umi grida al mare: "Vedi?! Vedi?!" Il mare, per una volta, sembra rispondere schiumando più forte.`,cliff:`Quella notte il faro resta acceso. Prima notte luminosa dopo quarant’anni bui.`,choiceA:{label:'Veglia il faro con Gin',effect:'dolcezza'},choiceB:{label:'Torni a dormire (finalmente) allo stand',effect:'coraggio'},level:T(4,22,27,'latte',4,'mix',75),letter:`Prima notte di luce — la segni sul muro dello stand: una riga bianca.`,ps:{dolcezza:"Vegliare il faro con Gin si fa in due turni: lui guarda l'orizzonte, tu il tè. Nessuno dei due guarda l'altro.",coraggio:"Tornare a dormire allo stand è il riposo più meritato dell'estate: porta aperta, e il faro veglia da sé."},threads:['onda']},
{id:'e11',chap:'E3',ep:1,kicker:'Est.3-1 · Tifone',title:'Arriva grosso',text:`Meteo: tifone in arrivo tra cinque giorni, grosso. Lo stand va smontato, il chashitsu — tetto ancora fragile — va protetto. E il faro? "Resta acceso," dice Gin. "I tifoni rispettano la luce. Quasi sempre."\n\nOrganizzi la difesa come una festa al contrario: tavoli dentro, vetri nastrati, thermos pieni per chi resta. Umi non vuole lasciare la spiaggia: "Il mare si arrabbia, ma io non scappo più."\n\nI vassoi si fanno durissimi: gelo d’agosto (il tifone porta freddo assurdo) e schiuma all’80% o niente. Le mani sanno. Devono sapere.`,cliff:`Ondina chiude la gelateria con un cartello: "Torniamo dopo l’onda. Il freddo aspetta."`,choiceA:{label:'Smonti lo stand cantando',effect:'coraggio'},choiceB:{label:'Ultimo giro di granite gratis',effect:'dolcezza'},level:T(5,23,28,'latte',-1,'gelo',80),letter:`Cartello di Ondina — lo fotografi. Filosofia da molo.`,ps:{coraggio:"Smontare lo stand cantando: quattro persone e un tifone. La musica copre i pezzetti. Metodo Ondina.",dolcezza:"L'ultimo giro di granite gratis finisce alle tre. Ondina chiude il cassetto per ultimo, come sempre."},threads:['faro']},
{id:'e12',chap:'E3',ep:2,kicker:'Est.3-2 · Nastro',title:'Vetri nastrati',text:`Nastrate i vetri del chashitsu a X, come bende su ferite future. Yuki disegna sulle X: diventano aquiloni, pesci, tazze volanti. "Così se si rompono, volano via contenti."\n\nRen arriva da Kyoto col furgoncino pieno di assi. Mika coi follower diventati di nuovo braccia. Kiku manda coperte (sempre coperte, benedetta).\n\nDi notte il vento prova le difese: fischia, spinge, desiste. Per ora. Il peggio arriva domani, dicono. Il peggio arriva sempre domani, e poi si affronta.`,cliff:`Umi dorme da te, sul futon accanto a Mugi e Tè. "Se l’onda viene, svegliami. Voglio vederla in faccia."`,choiceA:{label:'«Ti sveglio. Promesso.»',effect:'coraggio'},choiceB:{label:'Le racconti una storia finché dorme',effect:'dolcezza'},level:T(0,24,28,'awa',-1,'mix',80),letter:`X nastrate — Yuki ne firma una: opera protettiva n.1.`,ps:{coraggio:"Svegliarla, promesso, e non prima: la promessa al molo vale fino all'alba, e l'alba arriva sempre.",dolcezza:"Raccontare una storia finché dorme è il lavoro più lungo del giorno: alla terza pagina la voce si ferma."},threads:['conchiglia']},
{id:'e13',chap:'E3',ep:3,kicker:'Est.3-3 · Occhio',title:'L’occhio',text:`Il tifone arriva all’alba. Poi, a mezzogiorno, l’occhio: silenzio irreale, sole obliquo, mare di vetro. Tutti escono a guardare, storditi.\n\nUmi cammina fino alla riva, sola. Si ferma dove l’acqua lambisce. Resta lì un minuto intero, conchiglia in mano, a guardare l’orizzonte dentro l’occhio del tifone.\n\nTorna indietro camminando piano. Ti abbraccia senza dire niente. Non serve niente. L’occhio riparte, il vento anche. Ma qualcosa, in lei, è restato fermo per sempre.`,cliff:`La conchiglia resta nella SUA mano, ma la mano non trema più.`,choiceA:{label:'La tieni stretta fino alla fine del vento',effect:'dolcezza'},choiceB:{label:'Le prepari il tè più caldo di sempre',effect:'coraggio'},level:T(2,25,28,'latte',-1,'gelo',85),letter:`Minuto fermo — il più lungo e il più breve della tua vita.`,ps:{dolcezza:"Tenerla stretta fino alla fine del vento: l'occhio dura un minuto esatto, e nessuno lo tocca.",coraggio:"Il tè più caldo di sempre è la risposta giusta: contro il tifone non serve il coraggio, serve la temperatura."},threads:['onda']},
{id:'e14',chap:'E3',ep:4,kicker:'Est.3-4 · Faro acceso',title:'Il faro nel tifone',text:`Nel pieno del tifone, il faro RESTA ACCESO. Lo vedete dalla finestra sbarrata: un dito di luce che gira, gira, non molla.\n\nGin è lassù da solo, da due giorni. Nessuno può raggiungerlo. Umi piange: "Non di nuovo. Non un altro che aspetta da solo."\n\nAllora fai l’unica cosa possibile: accendi TUTTE le lanterne, le candele, i telefoni, e li metti alla finestra verso il faro. "Così vede che lo vediamo." Mezza costa fa lo stesso, passaparola.`,cliff:`Dalla torre, tre colpi di sirena. Uno... due... tre. È tornato dentro. Siete tornati dentro, tutti.`,choiceA:{label:'Piangi ridendo con Umi',effect:'dolcezza'},choiceB:{label:'Conti i colpi ad alta voce',effect:'coraggio'},level:T(3,25,28,'respiro',-1,'mix',85),letter:`Tre colpi nel tifone — la colonna sonora dell’estate.`,ps:{dolcezza:"Piangere ridendo con Umi è la colonna sonora giusta: dal molo si sente, e Ondina dice che è tifone bello.",coraggio:"Contare i colpi ad alta voce serve a contarli bene: alla fine sono tre, e il tre era dentro da quarant'anni."},threads:['faro']},
{id:'e15',chap:'E3',ep:5,kicker:'Est.3-5 · Dopo',title:'Dopo l’onda',text:`Il tifone passa. Danni: pochi. Miracoli: tanti. Lo stand è in piedi (l’ombrellone no, pace all’ombrellone). Il faro è acceso. Umi nuota. Gin piange sorridendo da tre giorni.\n\nUltima sera d’estate: festa sulla spiaggia ricostruita. Ondina offre granite a tutti, Mika filma, Ren balla malissimo, Yuki disegna l’onda con dentro una tazza.\n\nTieni in mano due scelte, come due tazze: tenere lo stand ogni estate, o affidarlo a Umi e Ondina e tornare al chashitsu a tempo pieno. Il mare aspetta la risposta. Il mare sa aspettare.`,cliff:`Umi ti porge la conchiglia. "Tienla tu, d’inverno. In primavera me la ridai. Patto?"`,choiceA:{label:'🌊 MAREA — stand ogni estate + chashitsu d’inverno, per sempre',effect:'finale-marea'},choiceB:{label:'🗼 FARO — affidi tutto a Umi e Ondina, torni a Kyoto col faro nel cuore',effect:'finale-faro'},level:T(1,26,28,'awa',-1,'mix',90),letter:`Conchiglia in prestito — pesa come un patto. Leggera come il mare.`,finaleNote:'Ultima scelta della Marea: tenere TUTTO o affidare tutto. Il mare approva entrambe. 🌊',threads:['onda','faro','conchiglia']},
];
const EENDINGS = {
  'finale-marea': { title: 'Finale: MAREA 🌊', text: `Ogni estate stand, ogni inverno chashitsu: doppia vita, doppia schiuma. Umi lavora con te d’estate e studia da infermiera d’inverno — come sua madre, dice, "ma con più mare".\n\nGin tiene il faro acceso ogni notte. Ondina congela i ricordi in granite. La conchiglia viaggia: inverni a Kyoto, primavere in spiaggia.\n\nHai due case e un solo cuore. Basta e avanza: il cuore, d’estate, si allarga.` },
  'finale-faro': { title: 'Finale: FARO 🗼', text: `Affidi lo stand a Umi e Ondina — "Granite e Tè", insegna nuova — e torni a Kyoto a tempo pieno. Ma ogni mese torni: il faro si vede anche da lontano, se sai dove guardare.\n\nUmi nuota ogni giorno, ormai. Ti manda foto delle onde con didascalie serie: "Oggi il mare era di buon umore."\n\nGin ti ha lasciato in eredità il diario delle navi. Sulla prima pagina: "Per chi accende." Accendi, ogni giorno. In tutti i sensi.` },
};
const SENDINGS = {
  'finale-radice-sognata': { title: 'Finale: RADICE SOGNATA 🌸', text: `Rest. La mattina dopo ti svegli nello stesso tatami, e Hana è in cucina. Vera. Viva. Tua.\n\nDiventi la seconda frullina del chashitsu: lei insegna, tu ricordi il futuro e lo trasformi in ricette. Aoi bambina cresce con due nonne — una viva, una nel vapore.\n\nIl Giardiniere continua ad annaffiare di notte. Non hai mai guardato sotto il cappello. Alcuni misteri sono tazze da non finire mai.\n\nA volte sogni la pioggia. Ti svegli, e fuori nevica sakura. Sorridi: hai scelto il mattino giusto.` },
  'finale-pioggia-vera': { title: 'Finale: PIOGGIA VERA 🌧️', text: `Ti svegli nel tuo locale, sotto la pioggia vera. Sul bancone: un petalo rosa, impossibile, profumato.\n\nHana è morta anche qui. Ma le tue mani ricordano tutto: il koicha del ’64 torna perfetto al primo tentativo. Takeshi piange: "È lei. Due volte lei."\n\nPorti con te la bambina che eri: da oggi frulli piano, ridi forte, e quando hai paura pensi a una nonna viva che ti ha detto "resta".\n\nHai lasciato un mondo. Hai tenuto tutto. (+3 mosse regalo del sogno, una volta sola.)` },
};
/* --- fili del canone (sottotrame Pioggia con progresso) --- */
const CANON_THREADS = [
  { id: 'soma-junior', name: 'Il nipote postino', icon: '📮',
    hints: ['Inciampa sullo zerbino, primo giorno.', 'Cartolina: primo giro da solo.', 'Non ha perso niente. Quasi.', 'La divisa gli va larga. Il cuore no.', 'Consegna completata, generazione due.'] },
  { id: 'moka', name: 'Moka la giudice', icon: '🐈',
    hints: ['Una zampa tigrata nella live.', 'Giudice suprema della schiuma.', 'Verdetto: fusa.', 'Alleanza felina in vista.', 'Due gatti, un solo locale.'] },
];
/* --- registro universi --- */
function canonChapters() {
  return window.MHStory.CHAPTERS.map(ch => ({
    n: ch.n, title: ch.title, desc: ch.desc,
    eps: window.MHStory.STORY.filter(e => e.chap === ch.n).map(e => e.id),
  }));
}
const UNIVERSES = [
  { id: 'pioggia', name: 'Pioggia', icon: '🌧️', theme: 'pioggia', skin: 'canon', mechanic: null,
    desc: 'Il canone: 45 tazze sotto la pioggia di Kyoto.',
    unlock: { type: 'always' }, threads: CANON_THREADS,
    get chapters() { return canonChapters(); },
    get story() { return window.MHStory.STORY; },
    get endings() { return window.MHStory.ENDINGS; } },
  { id: 'sakura', name: 'Sakura Eterna', icon: '🌸', theme: 'sakura', skin: 'sakura', mechanic: 'bloom', bloomRate: 0.12,
    desc: 'What-if: 25 tazze in un mondo dove Hana non è mai morta.',
    unlock: { type: 'finale', uid: 'pioggia' }, threads: THREADS,
    chapters: SCHAPTERS, story: SSTORY, endings: SENDINGS },
  { id: 'yokai', name: 'Notte Yokai', icon: '🌙', theme: 'yokai', skin: 'yokai', mechanic: 'ink',
    desc: '15 tazze nel villaggio sotto la luna: inchiostro vivo, maschere, parate.',
    unlock: { type: 'finale', uid: 'sakura' }, threads: YTHREADS,
    chapters: YCHAPTERS, story: YSTORY, endings: YENDINGS },
  { id: 'estate', name: "Marea d'Estate", icon: '🌊', theme: 'estate', skin: 'estate', mechanic: 'gelo',
    desc: '15 tazze di sale e sole: stand in spiaggia, faro spento, tifone. Le più dure.',
    unlock: { type: 'finale', uid: 'yokai' }, threads: ETHREADS,
    chapters: ECHAPTERS, story: ESTORY, endings: EENDINGS },
];
/* --- helper multiverso --- */
function freshProg(uid) {
  const u = UNIVERSES.find(x => x.id === uid);
  const first = u ? u.story[0].id : 1;
  return { stars: {}, unlocked: first, choices: {}, endings: [], letters: [], totalStars: 0, threads: {} };
}
function ensureSave() {
  const s = window.MH.save;
  if (!s.progress) {
    s.progress = {
      pioggia: {
        stars: s.stars || {}, unlocked: s.unlocked || 1, choices: s.choices || {},
        endings: s.endings || [], letters: s.letters || [], totalStars: s.totalStars || 0, threads: {},
      },
    };
    delete s.stars; delete s.unlocked; delete s.choices; delete s.endings; delete s.letters; delete s.totalStars;
  }
  if (!s.progress.sakura) s.progress.sakura = freshProg('sakura');
  if (!s.progress.pioggia) s.progress.pioggia = freshProg('pioggia');
  // B1: validare contro il registro, non con una allowlist: Yokai/Estate
  // venivano resettati a Pioggia a ogni reload, rendendoli irraggiungibili.
  if (!UNIVERSES.some(u => u.id === s.universe)) s.universe = 'pioggia';
  return s;
}
function active() {
  ensureSave();
  return UNIVERSES.find(u => u.id === window.MH.save.universe) || UNIVERSES[0];
}
function prog(uid) {
  ensureSave();
  const id = uid || window.MH.save.universe;
  if (!window.MH.save.progress[id]) window.MH.save.progress[id] = freshProg(id);
  return window.MH.save.progress[id];
}
function findEp(id, uid) {
  const u = uid ? UNIVERSES.find(x => x.id === uid) : active();
  return u.story.find(s => s.id === id);
}
function epIndex(id, uid) {
  const u = uid ? UNIVERSES.find(x => x.id === uid) : active();
  return u.story.findIndex(s => s.id === id);
}
function nextId(id, uid) {
  const u = uid ? UNIVERSES.find(x => x.id === uid) : active();
  const i = u.story.findIndex(s => s.id === id);
  return (i >= 0 && i + 1 < u.story.length) ? u.story[i + 1].id : null;
}
/* B2: gli id dei mondi non canonici sono stringhe ('y1', 'e1', 's1'): confrontare
   un id con Math.max produceva NaN → JSON null → epIndex -1 → saga intera sbloccata.
   Qui si confrontano le POSIZIONI nella saga, mai gli id grezzi. */
function advanceUnlocked(prog, uid, id) {
  if (!prog || prog.unlocked === 'complete') return false;
  const target = epIndex(id, uid);
  if (target < 0) return false;
  const cur = epIndex(prog.unlocked, uid);
  if (cur < 0 || target > cur) { prog.unlocked = id; return true; }
  return false;
}
function completeUniverse(prog) {
  if (!prog || prog.unlocked === 'complete') return false;
  prog.unlocked = 'complete';
  return true;
}
function tileEmoji(i) {
  const skin = active().skin;
  const set = (window.MHTiles.SKINS && window.MHTiles.SKINS[skin]) || window.MHTiles.TILES;
  return set[i] ? set[i].emoji : window.MHTiles.TILES[i].emoji;
}
function sakuraUnlocked() {
  ensureSave();
  return (window.MH.save.progress.pioggia.endings || []).length > 0;
}
function universeUnlocked(def) {
  ensureSave();
  if (!def || !def.unlock || def.unlock.type === 'always') return true;
  if (def.unlock.type === 'finale') {
    const uid = def.unlock.uid || 'pioggia';
    return (window.MH.save.progress[uid] && window.MH.save.progress[uid].endings || []).length > 0;
  }
  return false;
}
function setUniverse(id) {
  const u = UNIVERSES.find(x => x.id === id);
  if (!u) return false;
  if (!universeUnlocked(u)) return false;
  window.MH.save.universe = id;
  applyTheme();
  window.MHSave.writeSave(window.MH.save);
  return true;
}
function applyTheme() {
  ensureSave();
  try { document.body.dataset.universe = active().theme; } catch {}
}
window.MHU = {
  UNIVERSES, THREADS, CANON_THREADS, SCHAPTERS, SSTORY, SENDINGS, SCHARACTERS,
  YTHREADS, YCHAPTERS, YSTORY, YENDINGS, YCHARACTERS,
  ETHREADS, ECHAPTERS, ESTORY, EENDINGS, ECHARACTERS,
  active, prog, findEp, epIndex, nextId, tileEmoji, advanceUnlocked, completeUniverse,
  sakuraUnlocked, universeUnlocked, setUniverse, applyTheme, ensureSave, freshProg,
};
})();
